Add Menu component
FrontHeads/tanchiki pull request #10
Opened 2022-11-28 16:57 UTC by andreyatx

Add Menu component(burger-menu)
Add MenuLink component(reuse in main menu)
Add basic tests

TBD: better tests

2022-11-28 22:01 UTC, DmitriiNazimov requested changes
Написал что можно исправить в Слак. Остальным пока можно ревью не проводить, т.к. есть смысл дождаться внесения исправлений.

2022-11-29 14:39 UTC, DmitriiNazimov approved these changes

2022-11-29 14:46 UTC, sdelfi approved these changes

2022-11-29 14:46 UTC, sdelfi commented on packages/client/src/components/Menu/Menu.test.tsx
> +    render(
В проекте есть helper renderWithRouter, можно в будущем им пользоваться. 
Правда, он еще подгружает объект user, который в данном кейсе излишний. 
Это больше для информации

2022-11-29 15:39 UTC, Olegas requested changes

2022-11-29 15:39 UTC, Olegas commented on packages/client/src/components/Menu/Menu.tsx
> +    document.addEventListener('mousedown', handler);
Нужно не забыть убрать подписку при размонтировании компонента.

2022-11-29 15:39 UTC, Olegas commented on packages/client/src/components/Menu/Menu.tsx
> +    <div data-testid="menu" className="menu" ref={menuRef}>
menuRef по факту нигде не используется (только логируется при mousedown). Он точно нужен?

2022-11-29 15:39 UTC, Olegas commented on packages/client/src/components/Menu/Menu.tsx
> +        <div className={'menu__icon-line ' + (isOpen ? 'menu__icon-line_open' : '')}></div>
Совет: для сборки имен классов, в том числе и зависимо от каких-либо параметров, посмотрите на утилиту classnames https://www.npmjs.com/package/classnames

2022-11-29 15:39 UTC, Olegas commented on packages/client/src/components/Menu/Menu.tsx
> +        <div className={'menu__icon-line ' + (isOpen ? 'menu__icon-line_open' : '')}></div>
Вот эта конструкция `'menu__icon-line ' + (isOpen ? 'menu__icon-line_open' : '')` повторяется трижды. Можно вынести ее в переменную и убрать копипасту.

2022-11-29 15:39 UTC, Olegas commented on packages/client/src/components/MenuLink/MenuLink.tsx
> +      <NavLink onClick={() => handleNavigate()} className="menu__link" to={to}>
Совет: тут можно написать короче и не создавать новую функцию: `<NavLink onClick={handleNavigate} ...>`

2022-11-29 16:26 UTC, andreyatx commented on packages/client/src/components/Menu/Menu.tsx
> +    <div data-testid="menu" className="menu" ref={menuRef}>
он используется в условии
```
   if (!menuRef.current?.contains(e.target as HTMLElement)) {
        setIsOpen(false);
      }
```

2022-11-29 17:17 UTC, Olegas commented on packages/client/src/components/Menu/Menu.tsx
> +    <div data-testid="menu" className="menu" ref={menuRef}>
Ох, прошу прощения, не заметил (

2022-11-29 17:18 UTC, Olegas approved these changes

2022-11-29 17:19 UTC, Olegas commented
Супер!

2022-11-29 20:05 UTC, merged