Add SignUp page(no logic)
FrontHeads/tanchiki pull request #11
Opened 2022-11-28 17:34 UTC by andreyatx

add sign up page

2022-11-28 21:56 UTC, DmitriiNazimov requested changes

2022-11-28 21:56 UTC, DmitriiNazimov commented on packages/client/src/pages/SignUp/SignUp.tsx
> +  const formData: SignUpForm = {
Возможно стоит вынести в отдельный файл SignUpData или хотя бы вне SignUp. Здесь как-то глаз режет. Но это вопрос дискусионный, хотелось бы увидеть мнение коллег.

2022-11-28 21:56 UTC, DmitriiNazimov commented on packages/client/src/pages/SignUp/SignUp.tsx
> +    <Form handlerSubmit={submitHandler} header="Вход">
Заголовок д.б. "Регистрация" а не "Вход".

2022-11-29 00:21 UTC, sdelfi approved these changes
Замечаний у меня нет, кроме тех, что Дмитрий отметил. 
Есть пару моментов на обсуждение, но это не относится к PR, может быть доработано после обсуждения отдельно.

2022-11-29 00:21 UTC, sdelfi commented on packages/client/src/pages/SignUp/SignUp.tsx
> +  const formData: SignUpForm = {
Надо в принципе определиться со структурой страниц, где есть формы. Начинал делать профиль и там тоже возникает вопрос хранения набора полей, например.

2022-11-29 00:21 UTC, sdelfi commented on packages/client/src/pages/SignUp/SignUp.tsx
> +      <FormField
В профиле у себя я вынес список полей в отдельный массив (подглядел у Дмитрия в модуле 1), правда, разбил на 2 списка. 
![image](https://user-images.githubusercontent.com/1927032/204407646-322c46a5-cac6-4e90-988e-2638b4891297.png)

Предлагаю обсудить, как предложил ранее. 

Просто если прописать список в коде - выглядит громоздко. Хотя тут опять же - дело вкуса.

2022-11-29 09:15 UTC, sapomaro requested changes
Вроде, всё работает. Единственное - нужно поменять тип поля повторного ввода пароля. Вопросы с дублированием кода полей и вынесением их данных в отдельный файл можно обсудить на синке.

2022-11-29 09:15 UTC, sapomaro commented on packages/client/src/pages/SignUp/SignUp.tsx
> +        type="password_check"
Здесь должен быть тип password, иначе поле повторения пароля не скрывает вводимый текст.

2022-11-29 10:11 UTC, sapomaro approved these changes

2022-11-29 12:11 UTC, DmitriiNazimov commented on packages/client/src/pages/SignUp/SignUp.tsx
> +        type="password_check"
Алексей правильно обратил внимание. Там проблема не только с типом у поля "Повторите пароль", у остальных полей тоже. 

Список допустимых типов для input https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

Соответственно там д.б. email, text, но таких input type как "login" или "first_name" быть не может, они недопустимы.

2022-11-29 13:49 UTC, DmitriiNazimov commented on packages/client/src/pages/SignUp/SignUp.tsx
> +        type="text"
Кроме типа text у input есть и другие типы. Например email и телефон.

2022-11-29 14:29 UTC, DmitriiNazimov approved these changes

2022-11-29 16:12 UTC, Olegas commented on packages/client/src/pages/SignUp/SignUp.tsx
> +  const [responseBody, setResponseBody] = useState<SignUpForm>(formData);
Может быть request а не response? Мы ведь тут запрос собираем (на сервер) а не ответ?

2022-11-29 16:12 UTC, Olegas commented on packages/client/src/pages/SignUp/SignUp.tsx
> +        placeholder="+7 800 555 35 35"
🤣

2022-11-29 21:29 UTC, sdelfi commented
Полагаю, что после того, как будет апрувнут UserProfile - здесь нужно будет сделать правки в структуре

2022-11-30 06:16 UTC, Olegas approved these changes

2022-11-30 09:35 UTC, merged