feat(redux) redux-toolkit + redux-thunk integration
FrontHeads/tanchiki pull request #12
Opened 2022-11-29 00:08 UTC by sdelfi

add redux, redux-toolkit, redux-thunk packages
add app and auth reducers
add auth thunks
add signin handler
add loader component
update Http util (add axios interseptor to catch and rethrow response body from API errors)
add auth API

2022-11-29 16:14 UTC, sdelfi commented
@Olegas решили пригласить параллельно на ревью, т.к. React-Toolkit + Redux + Redux-Thunk из нас особо никто не знает, поэтому наши замечания будут чисто по стилю кода, а не по архитектуре и реализации store.

2022-11-30 11:46 UTC, Gramoteev approved these changes
Сделал аппрув, есть пара не критичных замечаний по коду

2022-11-30 11:46 UTC, Gramoteev commented on packages/client/src/pages/SignIn/SignIn.tsx
>  export const SignIn: React.FC = () => {
Можно упростить до FC

2022-11-30 11:46 UTC, Gramoteev commented on packages/client/src/pages/SignIn/SignIn.tsx
>    const [responseBody, setResponseBody] = useState<LoginForm>(formData);
название переменной поменять на request

2022-11-30 16:52 UTC, sapomaro approved these changes

2022-11-30 16:54 UTC, sdelfi commented
@Olegas наверное замучили, но этот PR важен для нас, затрагивает многие страницы и при обновлении develop конфликты возникают.
Прошу посмотреть как будет возможность. Спасибо

2022-11-30 18:47 UTC, Olegas requested changes
В целом направление правильное. Из самого redux основной вопрос к thunk me(). Более детально уточнил вопрос по месту

2022-11-30 18:47 UTC, Olegas commented on packages/client/src/components/Loader/Loader.tsx
> +export const Loader: React.FC = () => {
Нет импорта React

2022-11-30 18:47 UTC, Olegas commented on packages/client/src/layouts/Root/Root.css
> +
Пустые строки? А зачем такие изменения?

2022-11-30 18:47 UTC, Olegas commented on packages/client/src/pages/SignIn/SignIn.tsx
> +      await dispatch(authThunks.signIn(requestBody));
Для чего здесь async/await? Кто ждет результат этого диспатча?

2022-11-30 18:47 UTC, Olegas commented on packages/client/src/store/store.ts
> +  middleware: getDefaultMiddleware => getDefaultMiddleware().concat(),
Кажется concat() тут лишний. По крайней мере сейчас, пока нет никаких других мидлвар, кроме стандартной

2022-11-30 18:47 UTC, Olegas commented on packages/client/src/api/authAPI.ts
> +import { API_ENDPOINTS } from '../config/constants';
Константы с URL - 👍

2022-11-30 18:47 UTC, Olegas commented on packages/client/src/api/authAPI.ts
> +import { Http } from '../utils/Http';
Немного непривычный нейминг. HTTP это ведь аббревиатура. Каждый раз как вижу Http хочется исправить на HTTP )

2022-11-30 18:47 UTC, Olegas commented on packages/client/src/layouts/Root/Root.tsx
> +    <main className={cn('layout', `layout_state_${isLoading ? 'loading' : 'idle'}`)}>
Совет: classnames позволяет писать вот так:
```
cn('layout', {
  'layout_state_loading': isLoading,
  'layout_state_idle': !isLoading
});
```
Эффект будет одинаковый с текущим решением, но...

В чем польза? Например так имя класса видно целиком и его например можно найти поиском по полному вхождению. Такое помогает рефакторить в будущем.

2022-11-30 18:47 UTC, Olegas commented on packages/client/src/store/features/auth/auth.test.ts
> +import MockAdapter from 'axios-mock-adapter';
Всегда пишете тесты - молодцы! 👍

2022-11-30 18:47 UTC, Olegas commented on packages/client/src/store/features/auth/authThunks.ts
> +export const me = createAsyncThunk('auth/me', async (_, { dispatch }) => {
Вот это действие вызывает вопрос. А оно точно нужно? Остальные по бизнесу понятны - логин, регистрация, выход. А что такое me? Оно когда-то нужно отдельно от sigin/signup?

2022-11-30 18:47 UTC, Olegas commented on packages/client/src/components/Loader/Loader.css
> +@import url("../../variables.css");
Обратите внимание - у вас не чистый CSS, а на самом деле это Sass. По хорошему расширение бы сделать .scss

2022-11-30 19:06 UTC, sdelfi commented on packages/client/src/store/features/auth/authThunks.ts
> +export const me = createAsyncThunk('auth/me', async (_, { dispatch }) => {
Отдельно будет использоваться.
В первом модуле была логика - делаем запрос auth/me при каждом входе на сайт. Если ошибка, то значит пользователь не авторизован. 
В противном случае подгружаем в стор данные профиля юзера.

2022-11-30 19:08 UTC, sdelfi commented on packages/client/src/components/Loader/Loader.css
> +@import url("../../variables.css");
Я с PostCSS не работал ранее, но тут, похоже, это не Sass, а CSS с модулями. 
Предлагаю этот момент обсудить/исправить не в рамках данного PR, т.к. если меняем расширение, то это нужно делать во всем проекте, как мне кажется.

2022-11-30 19:11 UTC, sdelfi commented on packages/client/src/layouts/Root/Root.tsx
> +    <main className={cn('layout', `layout_state_${isLoading ? 'loading' : 'idle'}`)}>
Спасибо. 
Мне нравится это изменение.

2022-11-30 19:11 UTC, sdelfi commented on packages/client/src/api/authAPI.ts
> +import { Http } from '../utils/Http';
Согласен

2022-11-30 19:12 UTC, sdelfi commented on packages/client/src/store/store.ts
> +  middleware: getDefaultMiddleware => getDefaultMiddleware().concat(),
Сначала была цель подключить Redux-Thunk, затем выяснилось, что в этом нет необходимости при использовании  Redux-Tookit, а заготовка осталась

2022-11-30 19:13 UTC, sdelfi commented on packages/client/src/layouts/Root/Root.css
> +
Полагаю, при merge появились. Поправил

2022-11-30 19:16 UTC, sdelfi commented
@Olegas спасибо за ревью. Все поправил.
В целом, архитектурно сделано нормально или есть над чем поработать?
Интеграция заняла около одного дня, потому что по документации одна структура и показалось местами что-то громоздко, перегружено. В разных статьях используется разный подход.
Цель была сделать лаконично, легко читаемо и функционально.

2022-11-30 19:43 UTC, Olegas approved these changes

2022-11-30 19:44 UTC, merged