Add game engine
FrontHeads/tanchiki pull request #13
Opened 2022-11-29 08:42 UTC by sapomaro

Добавлено:
- базовая версия игрового движка с тестами (packages/client/src/game);
- документация к движку (docs/gameEngine.md) - будет дополняться;
- заглушка страницы с игрой и роут к ней (packages/client/src/pages/Game) - для ручной проверки работы движка по ссылке /game;
- dev-зависимость на клиенте jest-canvas-mock (без неё падают тесты, т.к. jest-environment-jsdom кидает ошибки при встрече с canvas).

2022-11-29 21:50 UTC, sdelfi approved these changes
Критичных замечаний нет, пару вопросов только. Локально запустил игру - все работает без ошибок.
По логике/архитектуре оценку дать не могу, но выглядит для меня все логично

2022-11-29 21:50 UTC, sdelfi commented on packages/client/src/pages/Game/Game.tsx
> +      <div id="tanchiki-game" style={{ border: '10px solid grey' }}></div>
Полагаю, inline стили временные? Если да, то все ок

2022-11-29 21:50 UTC, sdelfi commented on packages/client/src/pages/Game/Game.tsx
> +    const game = new Tanchiki(document.querySelector('#tanchiki-game'));
Возможно, через ref обращаться будет правильней.

2022-11-29 21:50 UTC, sdelfi commented on packages/client/src/game/services/Controller.ts
> +export type ControllerTypeT = Array<'wasd' | 'arrows'>;
Почему наименование ControllerTypeT, а не ControllerType? 
Если это отсылка что это type, то мне кажется, что тут это не нужно, т.к. мы по умолчанию используем type, а не interface.
Хотя момент именования типов мы не обсуждали, может есть другое мнение.

2022-11-30 07:15 UTC, DmitriiNazimov approved these changes

2022-11-30 07:15 UTC, DmitriiNazimov commented on packages/client/src/game/utils/index.ts
> +export { EventBus } from '../../utils/EventBus';
Мне кажется не стоит создавать index.ts в пустой папке Utils в Game, а лучше создать index.ts в папке Utils в корне Client.

2022-11-30 08:42 UTC, sapomaro commented on packages/client/src/pages/Game/Game.tsx
> +      <div id="tanchiki-game" style={{ border: '10px solid grey' }}></div>
Да, временно для заглушки.

2022-11-30 08:55 UTC, sapomaro commented on packages/client/src/game/services/Controller.ts
> +export type ControllerTypeT = Array<'wasd' | 'arrows'>;
Надо это обсудить, кстати. Один подход - приписывать что-то к названиям типов (чтобы их лучше различать в коде), другой - нет.

2022-11-30 09:00 UTC, sapomaro commented on packages/client/src/game/utils/index.ts
> +export { EventBus } from '../../utils/EventBus';
Это сделано, чтобы не менять пути в коде игровых классов, поскольку это, получается, внешняя для движка зависимость. Наверно, имеет смысл спросить у наставника, как в таком случае быть.

2022-11-30 19:36 UTC, Olegas requested changes
Очень очень и очень круто! Молодцы. 👍
Но есть некоторые моменты по коду которые надо обсудить...

2022-11-30 19:36 UTC, Olegas commented on packages/client/src/game/utils/index.ts
> +export { EventBus } from '../../utils/EventBus';
Выглядит очень странно. Есть утилита которая по факту внешняя для игры, но она зачем-то притворяется внутренней. Если она нужна только игре - давайте сложим ее в игру и все. Если она нужна еще кому-то - просто по честному импортируйте ее из игры. А такой реэкспорт - я не понимаю какая от него польза.

2022-11-30 19:36 UTC, Olegas commented on packages/client/src/game/typings/index.ts
> +export type DirectionT = 'UP' | 'DOWN' | 'LEFT' | 'RIGHT';
Кажется ранее в приложении не было такой нотации - добавлять к типу букву Т в конце.

2022-11-30 19:36 UTC, Olegas commented on packages/client/src/game/typings/index.ts
> +export type DirectionT = 'UP' | 'DOWN' | 'LEFT' | 'RIGHT';
Я бы еще рассмотрел возможность перписать это на enum. Какая польза? Допустим надо найти в коде все места, где используется какое-либо направление - ищем использование Enum и все находим. Или нужно переименовать внутреннее значение (допустим сделать их числовыми (угол поворота) - c enum это будет сделать проще.

2022-11-30 19:36 UTC, Olegas commented on packages/client/src/game/services/View.ts
> +  constructor({ width, height }: Pick<View, 'width' | 'height'>, root: HTMLElement | null) {
А какой смысл давать стартовать при случае root = null? Я бы тут на уровне типа отрезал возможность такую. Иначе получается что все создали но приложение не работает

2022-11-30 19:36 UTC, Olegas commented on packages/client/src/game/services/View.ts
> +    this.layers[layerId].entities.delete(entity);
А не нужно ли здесь отписаться от событий (тех, что в функции bindEntityToLayer)?

2022-11-30 19:36 UTC, Olegas commented on packages/client/src/game/services/Game.ts
> +  constructor(root: HTMLElement | null) {
Если вы хотите сделать только один возможный экземпляр игры, то лучше:
1. сделать static create(root) { тут создание экземляра или взятие существующего }
2. конструктор объявить как private что бы никто его снаружи не мог позвать (TS проверит это)

2022-11-30 19:36 UTC, Olegas commented on packages/client/src/game/entities/Entity.ts
> +export class Entity extends EventBus {
Подсказка по неймингу. Обычно EventBus - это просто сама по себе шина. А тут на самом деле больше похоже на EventEmitter

2022-11-30 19:36 UTC, Olegas commented on packages/client/src/game/entities/Entity.ts
> +  constructor(props: Partial<Entity>) {
Мне кажется это не очень хорошая затея - делать тут Partial<Entity>. Потому что получается сюда вообще что угодно можно передать. Можно например передать сюда свойство, одноименное методу, и все с громким фейерверком сломается. 

Я бы выделил отдельный тип который описывал только те свойства, которые реально законно передавать через конструктор.

2022-11-30 19:36 UTC, Olegas commented on packages/client/src/game/entities/Entity.ts
> +  spawn({ posX, posY }: Pick<Entity, 'posX' | 'posY'>) {
Вот этот тип posX, posY оно много где встречается. Его лучше объявить отдельно и использовать там, где надо передать позицию

2022-11-30 19:36 UTC, Olegas commented on packages/client/src/game/entities/Entity.ts
> +    this.lastRect = { ...this.getRect(), ...{ posX, posY } };
Здесь кажется лишним второй объект
Достаточно написать
```
{
   ...this.getRect(),
   posX,
   posY
}
```
и не тратить ресурсы на создание объекта, его перебор и т.п.

2022-11-30 19:36 UTC, Olegas commented on packages/client/src/game/entities/Projectile.ts
> +  constructor(props: Partial<EntityDynamic> & Pick<Tank, 'shootSpeed' | 'direction'>) {
Очень странно что пуля ссылается на танк для определения своих свойств. Такой зависимости точно быть не должно

2022-11-30 19:36 UTC, Olegas commented on packages/client/src/game/entities/Tank.ts
> +    Object.assign(projectile, this.calculateProjectilePos(projectile));
Несколько странно - менять свойства объекта не через его API. Такие изменения не просто отследить при отладке и сложно найти при рефакторинге.
Если это задается только при создании объекта - этому место в параметрах конструктора.

2022-11-30 19:36 UTC, Olegas commented on packages/client/src/game/services/Controller.ts
> +    }
Для чего может потребоваться контроллер, который умеет И в wasd И в стрелки одновременно?

2022-11-30 19:36 UTC, Olegas commented on packages/client/src/game/services/Controller.ts
> +    }
Кажется контроллер можно абстрагировать от кнопок, на которые он реагирует. Отдавать ему не тип в конструктор, а прямо конфигурацию и не делать if а то registerEventsForWasd а если if b то registerEventsForArrows

2022-11-30 19:36 UTC, Olegas commented on packages/client/src/game/services/Controller.ts
> +    document.addEventListener('keydown', (event: KeyboardEvent) => {
Нигде нет отписки от событий. Игра закончится, пользователь уйдет в лидерборд или форум, а обработчикик останутся. Пользователь будет писать сообщение и у него хорошо если просто в консоли ошибки будут лететь а может и приложение покрэшиться.

2022-11-30 19:36 UTC, Olegas commented on packages/client/src/game/services/Controller.ts
> +        case 'KeyD':
Для Space нет keyup? Это правильно? Или типа нельзя стрелять очередями а зажать вперед и ехать - можно?

2022-11-30 19:36 UTC, Olegas commented on packages/client/src/game/services/Game.ts
> +}
Не хватает методе деинициализации игры. Надо наверное все разобрать и от всего отписаться? Почему это может быть нужно описал выше в комментариях к Controller

2022-12-01 14:11 UTC, sapomaro commented on packages/client/src/game/services/Controller.ts
> +    }
Контроллер, который умеет одновременно отслеживать обе раскладки, пригодится для однопользовательской игры.

2022-12-01 14:12 UTC, sapomaro commented on packages/client/src/game/services/Controller.ts
> +        case 'KeyD':
Очередями в реальной игре стрелять нельзя. Более того, там потом будет ограничение на количество одновременно выпущенных снарядов (можно будет один или два в зависимости от набранных бонусов).

2022-12-01 14:14 UTC, sapomaro commented
@Olegas, большое спасибо за ревью! Внёс ряд исправлений, прошу посмотреть.

2022-12-01 14:42 UTC, Olegas approved these changes
Огромная работа тут! Молодцы! Я оставлю три камента но в целом - апрув. По каментам можно отдельно обсудить.

2022-12-01 14:42 UTC, Olegas commented on packages/client/src/game/typings/index.ts
> +export type EntitySettings = Pos & Partial<Size> & Partial<Pick<Entity, 'direction' | 'type' | 'role' | 'color'>>;
Я еще немного поворчу на тему циклического типа... У нас сейчас получается что для того что бы определить Entity, нам нужно определить EntitySettings который в свою очередь зависит от Entity.
И получается что структура компонента (то, как хранятся его свойства) влияет на то, какие свойства он принимает.

Представьте например, что завтра вы решили входящие параметры как есть сложить в свойство params. И удалили их Entity поля direction, type, role и color. И у вас внезапно разваливается определение типа, описывающего входящие параметры.

Я бы явно определил тип с direction, type, role и color и его использовал.

2022-12-01 14:42 UTC, Olegas commented on packages/client/src/game/services/Zone.ts
> +  constructor({ width, height }: Pick<Zone, 'width' | 'height'>) {
Для width+height у вас уже появился тип - Size

2022-12-01 14:42 UTC, Olegas commented on packages/client/src/game/services/Controller.ts
> +  };
С биндингом я видимо не смог идею донести... Давайте пока так зальем, но на работоспособность не влияет. Тут скорее архитектурный вопрос.

Давайте я PR нарисую - покажу идею

2022-12-01 15:10 UTC, sapomaro commented on packages/client/src/game/typings/index.ts
> +export type EntitySettings = Pos & Partial<Size> & Partial<Pick<Entity, 'direction' | 'type' | 'role' | 'color'>>;
Я тогда в следующем PR вынесу все эти вещи (type, role) в отдельные типы, чтобы не было такого нагромождения.

2022-12-01 15:17 UTC, Olegas commented on packages/client/src/game/typings/index.ts
> +export type EntitySettings = Pos & Partial<Size> & Partial<Pick<Entity, 'direction' | 'type' | 'role' | 'color'>>;
Да, ок. И самое главное что бы пропсы от самого Entity не зависели

2022-12-01 15:19 UTC, merged