Update error page
FrontHeads/tanchiki pull request #17
Opened 2022-11-30 18:48 UTC by DmitriiNazimov

- Добавил Layout на страницу с ошибками
- Запилил дизайн страницы с ошибками
- Покрыл тестами страницу с ошибками
- Для компонента кнопки добавил аттрибут data-testid, чтобы ее можно было тестировать.

2022-11-30 18:59 UTC, DmitriiNazimov commented
Тест роутера "catch wrong route" фактически дублирует тесты страницы ErrorPage. Возможно имеет смысл оставить что-то одно. С другой стороны, в будущем эти тесты могут разойтись в плане тестирования функционала. 

В общем я пока оставил и те и другие тесты, но если будут рекомендации какие-то тесты убрать - уберу.

2022-11-30 19:32 UTC, sdelfi approved these changes

2022-11-30 19:32 UTC, sdelfi commented on packages/client/src/components/Button/Button.tsx
> +    <button type={type} {...props} onClick={onClick} className={buttonClassNames}>
Раз мы передаем через spread параметры, то можно тогда убрать onClick, т.к. они передаются в <button> без каких-либо изменений
```suggestion
    export const Button: FC<ButtonProps> = ({ type = 'button', text, className, variant, testId }) => {
    ....
    <button {...props} type={type} className={buttonClassNames}>
```

2022-11-30 19:32 UTC, sdelfi commented on packages/client/src/config/router.tsx
> +        path: Paths.Home,
Хорошо подметил

2022-11-30 19:38 UTC, Olegas approved these changes

2022-11-30 19:39 UTC, Olegas approved these changes

2022-12-01 04:41 UTC, Olegas requested changes

2022-12-01 04:41 UTC, Olegas commented on packages/client/src/pages/Home/Home.tsx
> +import { HTTP } from '../../utils/Http';
Так, здесь что-то пошло не так. И файл и папка называются большими буквами. А тут опять стало маленькими. Недавно переименовали, буквально вчера вечером.

2022-12-01 08:08 UTC, sapomaro requested changes
Глянул код, всё работает, только есть пара небольших моментов. Из-за переименований папки HTTP у меня начал ругаться тайпскрипт в одном месте и не проходит линтинг.
Плюс обнаружил один косяк по вёрстке, но он, видимо, появился до этого.

2022-12-01 08:08 UTC, sapomaro commented on packages/client/src/api/authAPI.ts
> +import { HTTP } from '../utils/Http';
У меня здесь ругается тайпскрипт: `src/api/authAPI.ts(2,22): error TS1261: Already included file name 'ХХХ/packages/client/src/utils/Http/index.tsx' differs from file name 'ХХХ/packages/client/src/utils/HTTP/index.tsx' only in casing`.

2022-12-01 08:08 UTC, sapomaro commented on packages/client/src/layouts/Root/Root.tsx
> +      {children}
Разделители наезжают на другие элементы при сжатии страницы по вертикали (скрин прилагается). Проблема, судя по всему, со стилями корневого лэйаута.
![errorpage_screen1](https://user-images.githubusercontent.com/2198393/204997437-dc2b51a9-b8fb-43e0-a2cd-aa5812d5c50e.jpg)

2022-12-01 08:11 UTC, Olegas commented on packages/client/src/api/authAPI.ts
> +import { HTTP } from '../utils/Http';
Надо сделать что бы везде (во всем проекте) было одинаковым кейсом (большими буквами) и все станет на свои места.

2022-12-01 08:36 UTC, sapomaro approved these changes

2022-12-01 08:37 UTC, DmitriiNazimov commented
Я еще не все исправил. Запушил коммиты чтобы убедиться что линтинг проходит. У меня локально почему-то не показывались проблемы из-за которых в прошлый раз не прошел линтинг на гитхаб.

2022-12-01 08:44 UTC, sapomaro commented
> 
Проблема была в наименовании путей. Что касается вёрстки, то тут надо решить, где исправлять - формально это не совсем относится к таске со страницей с ошибками.

2022-12-01 09:24 UTC, DmitriiNazimov commented
Так, кажется больше проблем нет. С наименованием папки HTTP возникли проблемы после вливания ветки develop. Имена файлов и классов поменялись на HTTP, а имя папки почему-то так и осталось Http. 

По верстке проблема была именно на ErrorPage. На других страницах проверил - похожих проблем не обнаружил.

2022-12-01 09:24 UTC, sdelfi commented on packages/client/src/components/Button/typings.tsx
> +  testId?: string;
Это тоже тогда убрать нужно

2022-12-01 09:39 UTC, Olegas approved these changes

2022-12-01 09:42 UTC, merged