Add Home page
FrontHeads/tanchiki pull request #19
Opened 2022-12-01 11:06 UTC by andreyatx

2022-12-01 11:30 UTC, DmitriiNazimov commented
На экране мобильного не влезает танк в меню и появляется горизонтальный скролл.
<img width="457" alt="Снимок экрана 2022-12-01 в 14 13 54" src="https://user-images.githubusercontent.com/49460860/205041823-9ec263cf-02e6-4a19-98a4-1dbacaf8ce2e.png">

2022-12-01 14:11 UTC, sdelfi approved these changes
Все хорошо, просьба только ссылки в меню заменить со статичных на константы.

2022-12-01 14:11 UTC, sdelfi commented on packages/client/src/components/Menu/MenuData.tsx
> +  { id: 7, title: 'Профиль игрока', to: '/profile' },
Это хорошо, что поменял, спасибо.

У нас в conf/constants.tsx есть enum Paths с массивом ссылок на страницы. Давай пока ты работаешь с этим файлов - поменяешь текст на enum

2022-12-01 14:11 UTC, sdelfi commented on packages/client/src/components/MenuLink/typings.ts
> +  handleNavigate?: () => void;
Я правильно понимаю, что это для обработки logout, например, можно использовать?

2022-12-01 14:36 UTC, andreyatx commented on packages/client/src/components/MenuLink/typings.ts
> +  handleNavigate?: () => void;
Да, можно. Изначально сделал, чтобы бургер-меню закрывалось при нажатии на ссылку

2022-12-02 10:02 UTC, sdelfi commented
Тесты не подходят.
Посмотри в сторону mock для axios. Либо убрать из home запрос на backend,  это демонстрационный код

2022-12-02 10:04 UTC, DmitriiNazimov commented
Убирать запрос не надо. Надо научиться их обрабатывать чтобы тесты не падали. +1 за мок на axios. Думаю стоит искать более широко: "testing-library http request mocking" или типа того.

2022-12-02 10:22 UTC, sdelfi commented
У нас уже есть тесты с подменой ответа на запрос. 
С телефона сейчас, просто посмотреть файлы тестов authApi, вроде там есть

2022-12-02 10:59 UTC, sdelfi commented
https://github.com/FrontHeads/tanchiki/blob/develop/packages/client/src/store/features/auth/auth.test.ts


Тут пример

2022-12-02 11:43 UTC, DmitriiNazimov commented
Не про этот PR, но заодно можно поправить. На странице leaderboard почему-то уехал заголовок с центра налево.
<img width="484" alt="Снимок экрана 2022-12-02 в 14 42 29" src="https://user-images.githubusercontent.com/49460860/205285265-7d5f0acc-21ff-4d50-a2cd-327fcbc7ee52.png">

2022-12-02 11:50 UTC, Gramoteev requested changes

2022-12-02 11:50 UTC, Gramoteev commented on packages/client/src/pages/Home/Home.css
> +
Стили блока menu не должны быть в компонентe home. Если у меню нужно добавить специфичные стили, для текущей страницы, то лучше это делать через mixin блока home-menu. либо вынести конфликтующий css код в модификаторы меню

2022-12-02 11:57 UTC, DmitriiNazimov requested changes

2022-12-02 11:57 UTC, DmitriiNazimov commented on packages/client/src/components/MenuLink/MenuLink.test.tsx
> +    console.log(typeof renderedMenu);
Console.log надо убрать.

2022-12-02 11:57 UTC, DmitriiNazimov commented on packages/client/src/index.css
> +.menu-nav {
У нас есть .menu-nav в Home.css и здесь, т.е. у нас идет дублирование. В одном месте точно надо убрать.

2022-12-02 11:57 UTC, DmitriiNazimov commented on packages/client/src/pages/Home/Home.tsx
> +    <div className="menu">
Выглядит странно что у нас картинка .promo-img обернута в тег с классом menu. Лучше вынести

2022-12-02 11:57 UTC, DmitriiNazimov commented on packages/client/src/pages/Home/Home.test.tsx
> +describe('Home page', () => {
Т.к. мы тестируем тут не отдельный компонент, а страницу целиком и это входная страница, думаю стоит проверить что у нас на ней отображается логотип, футер и promo-img.

2022-12-02 12:40 UTC, andreyatx commented on packages/client/src/pages/Home/Home.test.tsx
> +describe('Home page', () => {
Тесты с отображением лого и футера есть в layout. По-моему они там и рендерятся

2022-12-02 13:08 UTC, DmitriiNazimov commented on packages/client/src/pages/Home/Home.test.tsx
> +describe('Home page', () => {
В Layout мы проверяем что лого и футер вообще в принципе рендерятся. А здесь хотелось бы проверить что они точно рендерятся на главной странице, где их наличие важно, в отличие от других страниц.

2022-12-02 17:01 UTC, Gramoteev approved these changes

2022-12-02 17:47 UTC, andreyatx commented
@Olegas можете подскать, так нормально писать тест? В файле _Home.test.tsx_

2022-12-02 18:43 UTC, Olegas commented on packages/client/src/components/MenuLink/MenuLink.tsx
> +      <NavLink onClick={handleNavigate} className="menu__link" to={`${to}`}>
А зачем так? Бывают URL не строки?

2022-12-02 18:43 UTC, Olegas commented on packages/client/src/pages/Home/Home.test.tsx
> +describe('Home page', () => {
@DmitriiNazimov но ведь в разметке Home нет ничего про лого и футер? Кто их рендерит? Если их рендерит не Home то не надо их проверять в тестах Home. По факту лого и футер рендерит кто-то другой. Вот его тестах и надо их проверять. А если мы говорим о взаимодействии то это уже не unit-тесты получаются.

2022-12-02 18:43 UTC, DmitriiNazimov approved these changes

2022-12-02 18:54 UTC, DmitriiNazimov commented
@Olegas вот похоже у нас в данном случае получился не юнит-тест, видимо интеграционный. У нас же не запрещено писать интеграционные тесты? :) Вопрос в том написали ли мы этот тест с допустимой степенью корявости и в допустимом ли месте. 

Что касается необходимости такого теста - мне кажется он адекватен, чтобы проверить что у нас главная страница собирается так, как мы от нее ждем.

2022-12-02 19:04 UTC, Olegas commented
@DmitriiNazimov конечно не запрещено! Интеграционные тесты это супер! Но я бы тогда не складывал его рядом с компонентом а завел отдельную папку где-то на уровне корня проекта. Что бы было понятно - вот тут мы тестируем компонент Home и не ждем ничего кроме того что он умеет. А тут мы уже держим интеграционные тесты

2022-12-03 07:01 UTC, DmitriiNazimov commented
@Olegas у нас есть папка tests в корне проекта, там сейчас лежат только тесты роутера. Наверное тогда этот интеграционный тест можно вынести в tests/integration/home.test.tsx?

2022-12-03 08:11 UTC, andreyatx commented on packages/client/src/components/MenuLink/MenuLink.tsx
> +      <NavLink onClick={handleNavigate} className="menu__link" to={`${to}`}>
Да, я там намудрил, сделав свойство to необязательным, чтобы не вешать его на ссылку logout :)

2022-12-03 12:55 UTC, Olegas approved these changes

2022-12-03 13:13 UTC, merged