Add registration api
FrontHeads/tanchiki pull request #24
Opened 2022-12-03 13:41 UTC by andreyatx

Add registration functionality
Add logout feature

2022-12-03 13:58 UTC, DmitriiNazimov commented
При логауте надо чтобы делало редирект на главную и показывалось уведомление "Мы будем скучать!", а то сейчас как-будто ничего не происходит.

2022-12-03 14:02 UTC, DmitriiNazimov commented
Аналогично и при регистрации: 
1. Редирект на главную вроде есть, но мне показалось что не наверх страницы, а внизу страница остается. Если так, то надо принудительно скроллить наверх.
2. Нужно чтобы показывалось уведомление "Успех! Теперь одним танкистом больше!"

2022-12-03 14:04 UTC, sdelfi approved these changes
По registration API замечаний нет, все отлично.

Есть пару моментов, оставил комментарии, но, возможно, это не в этом PR нужно править.

2022-12-03 14:04 UTC, sdelfi commented on packages/client/src/pages/SignUp/SignUp.tsx
> +    navigate(Paths.Home);
Можно показывать toast об успешной регистрации.
Но механизм проверки на авторизацию для роутов еще поменяю (protected routes, авторизованный не может зайти на login, signup страницы, неавторизованный не может попасть в приватные разделы), пока можно, наверное, оставить так.

2022-12-03 14:04 UTC, sdelfi commented on packages/client/src/pages/SignUp/SignUp.tsx
>          type="email"
Мы планировали использовтаь единый стиль для форм, т.к. настройки полей отдельно и потом в цикле выводить.
В signin и в user profile секции так сделано уже. 
Хотя это не registration api, но при желании можно отрефакторить.
С другой стороны - грядет еще интеграция вализации форм, возможно, там структура поменяется.

2022-12-03 14:04 UTC, sdelfi commented on packages/client/src/pages/SignUp/SignUp.tsx
> +        {error && `Error: ${error}`}
Уже интегрированы toast. Посмотри пример в signin компоненте

2022-12-03 14:04 UTC, sdelfi commented on packages/client/src/components/Menu/Menu.tsx
> +    dispatch(authThunks.logout());
Я бы добавил async + await  (дождаться выполнения thunk) и после сделать редирект на главную.
А так все отлично в плане логики

2022-12-04 21:42 UTC, DmitriiNazimov commented
Тут работы еще не закончены, PR не готов для полноценного ревью.

2022-12-04 21:46 UTC, DmitriiNazimov requested changes
Надо выполнить все TODO из последнего пуша.

2022-12-04 21:46 UTC, DmitriiNazimov commented on packages/client/src/pages/SignUp/SignUp.tsx
> +import { formInitialState, signUpInputFields as signUpFieldList } from './data';
Тут импорт переименовался, а не сам signUpInputFields. Надо переименовать signUpInputFields в signUpFieldList

2022-12-05 10:26 UTC, sapomaro commented on packages/client/src/layouts/Root/Root.tsx
>          {location?.pathname !== Paths.Game && (
Имеет смысл отходить от практики использования оператора && в сторону тернарного ? (https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Conditional_Operator) - это позволит избежать появления при рендеринге случайных нулей и другого возможного мусора. См. раздел "Условный рендеринг" в https://habr.com/ru/post/541320/.

2022-12-05 10:41 UTC, DmitriiNazimov commented on packages/client/src/layouts/Root/Root.tsx
>          {location?.pathname !== Paths.Game && (
Да, тернарный оператор лучше.

2022-12-05 12:49 UTC, DmitriiNazimov approved these changes

2022-12-05 13:04 UTC, DmitriiNazimov commented
@Olegas этот PR проверен командой и готов к ревью.

2022-12-05 13:07 UTC, DmitriiNazimov commented on packages/client/src/layouts/Root/Root.tsx
>          {location?.pathname !== Paths.Game && (
Не стал это исправлять в одном месте здесь. По хорошему надо пройтись по всему проекту и исправить. Добавлю в задачи.

2022-12-05 13:23 UTC, Olegas requested changes

2022-12-05 13:23 UTC, Olegas commented on packages/client/src/components/MenuLink/MenuLink.tsx
> +export const MenuLink: FC<MenuLinkProps> = ({ title, to, clickHandler }) => {
Обычно обработчики событий имеют названия вида onSomething

2022-12-05 13:23 UTC, Olegas commented on packages/client/src/components/Navigation/Navigation.tsx
> +      if (!error) {
Вот это очень странный участок. Error тут интересует на момент старта обработчика? Или расчет на то, что error поменяется в процессе await dispatch?

2022-12-05 13:23 UTC, Olegas commented on packages/client/src/store/features/auth/authSlice.ts
> +      // который ставит isLoading=false
Полезные комментарии - 👍

2022-12-05 13:23 UTC, Olegas commented on packages/client/src/store/features/ui/typings.ts
> +export interface uiState {
Типы и интерфейсы обычно именуются с большой буквы. А UI это к тому же еще и аббревиатура

2022-12-05 13:26 UTC, sdelfi commented on packages/client/src/components/Navigation/Navigation.tsx
> +      if (!error) {
Во время  await dispatch в error может прийти ошибка с API.
Но наверное да, error нужно слушать в корне компонента в данном случае.
Мы обсуждали вывод ошибки с командой вчера, но упустили этот момент.

2022-12-05 13:28 UTC, DmitriiNazimov commented on packages/client/src/components/Navigation/Navigation.tsx
> +      if (!error) {
Станислав, поправишь этот момент?

2022-12-05 13:41 UTC, andreyatx commented on packages/client/src/components/MenuLink/MenuLink.tsx
> +export const MenuLink: FC<MenuLinkProps> = ({ title, to, clickHandler }) => {
Я так понимаю, название самой функции, где прописана логика можно оставить clickHandler? @Olegas

2022-12-05 15:11 UTC, DmitriiNazimov requested changes
Изменения которые я делал затерлись следующими коммитами. Необходимо их вернуть.

2022-12-05 16:57 UTC, DmitriiNazimov commented on packages/client/src/components/Navigation/Navigation.tsx
> +      if (!error) {
@Olegas мы посовещались и пришли к выводу, что в данном случае изменения кода не требуются. 

Код работает как Вы и предположили - error может поменяться в процессе await dispatch. 

Возможно по этому поводу мог бы пригодится комментарий, но мы проговорили этот момент на синке, все поняли как это работает и поэтому комментарий не требуется. 

Т.е. если замечание было только по поводу того, что этот участок кода не очень понятен, то этот вопрос мы в команде решили, а если тут есть какие-то ошибки которые мы не видим, то просьба указать на них конкретно :)

2022-12-05 17:24 UTC, DmitriiNazimov approved these changes

2022-12-05 17:26 UTC, DmitriiNazimov commented
Кажется все замечания исправлены.

2022-12-05 18:39 UTC, Olegas commented on packages/client/src/components/Navigation/Navigation.tsx
> +      if (!error) {
Я считаю что этот участок кода в принципе не будет работать правильно. Я напишу пример. Пока не сливайте. С меня объяснение почему.

2022-12-05 18:40 UTC, Olegas requested changes
Участок с обработкой ошибки неработоспособен. С меня пример.

2022-12-05 18:55 UTC, Olegas commented
Вот пример: https://playcode.io/1027863

Смотрите что происходит... Компонент - это функция. Каждый раз при запуске этой функции объявляются и инициализируются все переменные. Одна из таких переменных - clickHandler в которой лежит анонимная асинхронная функция. Эта функция создает замыкание через которое видит переменную error содержащую текущую ошибку, полученную из redux store. Она пока пустая. Пока все хорошо

Далее, пользователь нажимает и срабатывает clickHandler. Он запускает API-вызов и ожидает. Где-то внутри, во время этого API-вызова происходит ошибка. Она записывается в redux store после чего у нашего компонента случается перерисовка, вызванная изменениями в store.

Снова вызывается функция компонента, инициализируются переменные, одна их которых содержит анонимную асинхронную функцию, которая создает замыкание и видит переменную error которая содержит ошибку. ВНИМАНИЕ - в clickHandler лежит другая, новая функция, никак не связанная с тем, что мы получили в первом абзаце.

Далее заканчивается await и управление возвращается в наш первый clickHandler, в ту точку где мы делали await, он смотрит на переменную error - она пустая. Потому что это другое лексическое окружение, другое замыкание, в этой "параллельной вселенной" error не заполнен. Вот тут все и сломалось.

В моем примере по ссылке функция longFunction имитирует API-вызов которого мы дожидаемся. Внутри timeout имитирует поход в сеть. Т.к. у меня там нет redux я просто передал в нее сеттер что бы сымитировать выставление ошибки. Как мы видим, компонент перерисовался, ошибка на экран выведена. Но в логе консоли видно что после await ошибка все еще пустая.

2022-12-05 18:56 UTC, Olegas commented on packages/client/src/components/Navigation/Navigation.tsx
> +      if (!error) {
Написал ниже пояснение с примером - почему это не работает

2022-12-06 11:56 UTC, sdelfi commented
> Вот пример: https://playcode.io/1027863

Спасибо большое, что пояснили. Полезно знать. 
В итоге переделал немного код, теперь работает как нужно, ошибки отлавилваются.. 
Thunk позволяет через  then().catch() получить результат выполнения и отловить ошибки.

2022-12-06 12:01 UTC, Olegas approved these changes

2022-12-06 12:02 UTC, Olegas commented
Теперь все супер, молодцы!

2022-12-06 12:03 UTC, Olegas commented on packages/client/src/components/MenuLink/MenuLink.tsx
> +export const MenuLink: FC<MenuLinkProps> = ({ title, to, clickHandler }) => {
@andreyatx Название функции может быть какое угодно, а проп лучше называть onClick.

2022-12-06 12:13 UTC, merged