Add protected and public routes.
FrontHeads/tanchiki pull request #26
Opened 2022-12-04 17:55 UTC by sdelfi

add protected routes
add test setup script with global mocks
change redux store structure

BREAKING CHANGE:
change routes config file structure

2022-12-04 19:16 UTC, Olegas commented on packages/client/src/layouts/Root/Root.tsx
> +  if (data) data.user.then(response => response && dispatch(authActions.setUserProfile(response.data)));
Я бы это завернул в useEffect что бы это не повторялось по нескольку раз

2022-12-04 19:16 UTC, Olegas commented on packages/client/src/layouts/Root/Root.tsx
> +          <main className={'layout'}>
Можно просто `className="layout"`

2022-12-04 19:26 UTC, sdelfi commented
У меня в этом PR тесты рандомно падают. Еще делаю изменения по части тестов и рендеринга компонентов

2022-12-04 22:44 UTC, DmitriiNazimov requested changes
Т.к. PR был непростой проверил код тщательно. Надо кое-что поправить.

2022-12-04 22:44 UTC, DmitriiNazimov commented on packages/client/src/components/PublicRoutes/PublicRoutes.tsx
> +  if (auth) {
Сейчас если залогиненный юзер пытается попасть на страницу авторизации или регистрации его просто молча перекидывает на главную.

Нужно сделать чтобы ему показывало тост "Вы уже авторизованы". И наверное лучше чтобы не редеректило на главную, а пользователь оставался там где он есть.

2022-12-04 22:44 UTC, DmitriiNazimov commented on packages/client/src/config/router.tsx
> +  const user = authAPI.me().catch(() => null);
Тут нужны комментарии как это работает. Не очевидно. Или переписать более понятно.

2022-12-04 22:44 UTC, DmitriiNazimov commented on packages/client/src/layouts/Root/Root.tsx
> +    if (data) data.user.then(response => response && dispatch(authActions.setUserProfile(response.data)));
Над useEffect не хватает пустой строки. 
Не стоит писать этот if в одну строку - нечитаемо. Лучше разбить if по строкам.

Хотя с тем чтобы разбить на строки есть проблемы, видимо преттиер шалит. Но хотя бы if добавить фигурные скобки надо. Стоит придерживаться одного стиля для if-конструкций (со скобками).

2022-12-04 22:44 UTC, DmitriiNazimov commented on packages/client/src/pages/SignIn/SignIn.tsx
> +  const isLoading = useAppSelector(authSelectors.isLoading);
Может лучше через деструктуризацию совместно с error?

2022-12-04 22:44 UTC, DmitriiNazimov commented on packages/client/src/utils/HTTP/HTTP.tsx
> +export type Response<T> = {
Предлагаю этот тип назвать ResponseType, потому что когда из HTTP импортируется Response - это вызывает растерянность. 

Например в Root на 13 строке такой импорт.

2022-12-04 22:44 UTC, DmitriiNazimov commented on packages/client/src/utils/testing-utils.tsx
> +import { render, screen, waitFor, waitForElementToBeRemoved } from '@testing-library/react';
Этому файлу остро не хватает комментариев что тут вообще происходит и зачем. Сложно.

2022-12-04 22:44 UTC, DmitriiNazimov commented on packages/client/src/utils/testing-utils.tsx
> +export const sleep = (ms = 300) => {
Sleep уже можно удалить.

2022-12-04 22:44 UTC, DmitriiNazimov commented on packages/client/src/tests/setup.ts
> +// jest.mock('react-router-dom', () => {
С комментариями надо разобраться. Или удалить или раскомментировать и причесать.

2022-12-04 22:57 UTC, sdelfi commented on packages/client/src/pages/SignIn/SignIn.tsx
> +  const isLoading = useAppSelector(authSelectors.isLoading);
Тогда читаем лишние переменные, если брать authSelectors.all. Будет красиво, но в ущерб производительности.

2022-12-04 23:03 UTC, sdelfi commented on packages/client/src/components/PublicRoutes/PublicRoutes.tsx
> +  if (auth) {
Такое было сделано, но есть проблема, которую не придумал как решить. Уже забыл что именно было.

Плюс у нас не будет ссылок на такие страницы, только если прямой переход и это уведомление становится уже не таким важным.

А чтобы редиректить назад - нужно как-то узнать предыдущую страницу. Убил время на это, но не нашел способа решения.

2022-12-04 23:04 UTC, sdelfi commented on packages/client/src/layouts/Root/Root.tsx
> +          <main className={'layout'}>
Исправил

2022-12-04 23:04 UTC, sdelfi commented on packages/client/src/layouts/Root/Root.tsx
> +  if (data) data.user.then(response => response && dispatch(authActions.setUserProfile(response.data)));
Поправил

2022-12-04 23:04 UTC, sdelfi commented on packages/client/src/tests/setup.ts
> +// jest.mock('react-router-dom', () => {
Ага, подчищу, упустил.
Было много мусора :)

2022-12-05 07:14 UTC, Olegas commented on packages/client/src/layouts/Root/Root.tsx
> +  if (data) data.user.then(response => response && dispatch(authActions.setUserProfile(response.data)));
А что тут не так? Зачем закомментировали? Что-то не работает с useEffect?

2022-12-05 07:16 UTC, Olegas commented on packages/client/src/pages/SignIn/SignIn.tsx
> +  const isLoading = useAppSelector(authSelectors.isLoading);
А где потеря производительности? Чем один селектор + деструкт хуже нескольких? Есть замеры? Какие-то актуальные данные по производительности тут?

2022-12-05 07:37 UTC, sdelfi commented on packages/client/src/pages/SignIn/SignIn.tsx
> +  const isLoading = useAppSelector(authSelectors.isLoading);
Предположение.
В сторе 4 переменные.
Точечными селекторами я беру 2 переменные.
Если я селектором заберу всё переменные и деструктуризирую только 2, то оставшиеся переменные не при изменении не будут тригерить ререндер компонента?
В данном случае селекторые берут конкретную одну переменную, которую мы используем.

Если не будут, то тогда не ясно для чего эти селекторы придумали, когда можно всегда брать весь стор и деструктуризировать только нужные переменные?

2022-12-05 07:41 UTC, sdelfi commented on packages/client/src/layouts/Root/Root.tsx
> +  if (data) data.user.then(response => response && dispatch(authActions.setUserProfile(response.data)));
Не совсем понял вопроса. Я обернул в useEffect данный кусок кода, как и советовали:

![image](https://user-images.githubusercontent.com/1927032/205580749-beba6efb-15f1-439d-98cc-ae67fa805847.png)

2022-12-05 07:46 UTC, sdelfi commented on packages/client/src/layouts/Root/Root.tsx
> +    if (data) data.user.then(response => response && dispatch(authActions.setUserProfile(response.data)));
> Над useEffect не хватает пустой строки.

В данном случае это связный блок кода, поэтому переноса строки не сделано.

if разделил

![image](https://user-images.githubusercontent.com/1927032/205581753-45247281-18a1-4a45-ac62-2511fbe7991c.png)

2022-12-05 07:47 UTC, sdelfi commented on packages/client/src/pages/SignIn/SignIn.tsx
> +  const isLoading = useAppSelector(authSelectors.isLoading);
Переделал на выборку всего куска стора и деструктуризацию двух переменных одной строкой
![image](https://user-images.githubusercontent.com/1927032/205581932-4e2d1060-cf0d-4593-a4f1-08d3e48aee41.png)

2022-12-05 07:51 UTC, Olegas commented on packages/client/src/pages/SignIn/SignIn.tsx
> +  const isLoading = useAppSelector(authSelectors.isLoading);
Ты совершенно прав, если в сторе 4 поля, взять все, но деструктурировать 2 то при изменении тех двух не взятых все равно будет перерисовка. НО, у меня есть два аргумента.
1. Это преждевременная оптимизация. В угоду оптимизации, которая не факт что нужна (а тут точно проблема? есть жалобы? есть замеры в миллисекундах? какой импакт вообще?), наносим вред читаемости
2. Если посмотреть на переменные, которые деструктурируем (isLoading, error, isAuthenticated) то становится понятно, что а) их можно как минимум собрать в отдельный селектор потому что они меняются все разом всегда б) текущая форма стейта авторизации не предполагает что какое-то поле внутри поменяется в отрыве от всего остального (то есть по факту проблемы нет и можно всегда брать все).

2022-12-05 07:52 UTC, Olegas commented on packages/client/src/layouts/Root/Root.tsx
> +    if (data) data.user.then(response => response && dispatch(authActions.setUserProfile(response.data)));
Упс, извиняюсь, видмио посмотрел какой-то не тот комит. Сейчас все верно

2022-12-05 07:53 UTC, Olegas commented on packages/client/src/layouts/Root/Root.tsx
> +    if (data) data.user.then(response => response && dispatch(authActions.setUserProfile(response.data)));
И блок с таким форматирование читается сильно лучше. Супер!

2022-12-05 07:58 UTC, sdelfi commented on packages/client/src/utils/testing-utils.tsx
> +export const sleep = (ms = 300) => {
Удалил

2022-12-05 07:59 UTC, DmitriiNazimov commented on packages/client/src/pages/SignIn/SignIn.tsx
> +  const isLoading = useAppSelector(authSelectors.isLoading);
Мне кажется просто в ``authSelectors`` лишним является селектор ``userProfile``, поэтому и не хочется брать все селекторы из ``authSelectors``. Возможно стоит вынести ``userProfile`` в другое место и тогда спокойно можно всегда брать ``authSelectors.all``. 

Либо можно создать селектор типа ``authSelectors.checkAuth`` и туда положить все кроме ``userProfile``.

А еще в данном конкретном случае можно было записать вот так:  
`const [error, isLoading] = [useAppSelector(authSelectors.error), useAppSelector(authSelectors.isLoading)];`

2022-12-05 08:01 UTC, sdelfi commented on packages/client/src/utils/testing-utils.tsx
> +import { render, screen, waitFor, waitForElementToBeRemoved } from '@testing-library/react';
Если речь про renderWithRouter, то сделал небольшой рефакторинг, должно стать более понятно.

2022-12-05 08:01 UTC, Olegas commented on packages/client/src/pages/SignIn/SignIn.tsx
> +  const isLoading = useAppSelector(authSelectors.isLoading);
> Мне кажется просто в `authSelectors` лишним является селектор `userProfile`, поэтому и не хочется брать все селекторы из `authSelectors`. Возможно стоит вынести `userProfile` в другое место и тогда спокойно можно всегда брать `authSelectors.all`.
> 
> Либо можно создать селектор типа `authSelectors.checkAuth` и туда положить все кроме `userProfile`.

👍

2022-12-05 08:14 UTC, sdelfi commented
Все исправления запушил

2022-12-05 08:19 UTC, sdelfi commented on packages/client/src/pages/SignIn/SignIn.tsx
> +  const isLoading = useAppSelector(authSelectors.isLoading);
> const [error, isLoading] = [useAppSelector(authSelectors.error), useAppSelector(authSelectors.isLoading)];

Не вижу принципиально разницы между двумя строчками и этой. Такая читается сложнее.

А вот селектор сделать под - идея нравится. Заливаю

2022-12-05 08:25 UTC, Gramoteev approved these changes

2022-12-05 08:32 UTC, sdelfi commented on packages/client/src/pages/SignIn/SignIn.tsx
> +  const isLoading = useAppSelector(authSelectors.isLoading);
> Возможно стоит вынести userProfile

Я его как раз переместил из appSlice, т.к. в authSlice для обновления профиля приходилось делать много телодвижений. 
Пока предлагаю все-таки оставить здесь.
Посмотрим как оно будет, когда Дмитрий будет делать свой slice для работы с профилем.

2022-12-05 09:21 UTC, DmitriiNazimov commented on packages/client/src/components/PublicRoutes/PublicRoutes.tsx
> +  if (auth) {
Давай хотя бы тост добавим с пояснением "Вы уже авторизованы". Ссылка может вылезти если где-то накосячим или пользователь ее может в избранное зачем-то добавить, или внешняя ссылка может быть. 

Чтобы редиректить назад у роутера должно быть что-то вроде navigate.back(), но это не обязательно. Достаточно тост добавить.

2022-12-05 09:25 UTC, sdelfi commented on packages/client/src/components/PublicRoutes/PublicRoutes.tsx
> +  if (auth) {
> что-то вроде navigate.back()
Там сложнее. Нужно вернуть ReactElement, т.е. компонент <Navigate>, а у него нет функционала возврата назад, я искал.
Через navigate(-1) пробовал - работает некорректно. 

> Давай хотя бы тост добавим с пояснением "Вы уже авторизованы"
Но этот тост всплывет в ненужных местах, например, после успешной авторизации, т.к. идет ререндер signIn после изменения isAuthenicated, а в этот момент уже сработает PublicRoutes и отобразит "вы уже авторизованы."
Как решить - не придумал, но тоже об этом думал вчера и красивого решения не нашел.

2022-12-05 09:26 UTC, DmitriiNazimov commented on packages/client/src/config/router.tsx
> +  const user = authAPI.me().catch(() => null);
Вижу добавил комментарий, теперь все понятно! Только многострочные комментарии лучше оформлять вот такой нотацией со звездами 
`/**
 * Делаем предзагрузку данных пользователя, проверяя - авторизован или нет
catch сделан, чтобы в случае ошибки (куки не валидны, пользователь не авторизован)
пользователю не отображалось это сообщение, т.к. при проверке авторизации в этом нет
необходимости
 */`

2022-12-05 09:44 UTC, DmitriiNazimov commented on packages/client/src/components/PublicRoutes/PublicRoutes.tsx
> +  if (auth) {
А если вот так? Вроде все нормально, кроме того что запись немного костыльная, но если не получилось придумать более изящное решение, то лучше так, чем никак. 

```
  if (auth) {
    if (location.pathname === Paths.SignIn || location.pathname === Paths.SignUp) {
      toast.success('Вы уже авторизованы!');
    }

    const to = location.state?.from?.pathname || Paths.Home;
    return <Navigate to={to} replace={true} />;
  }
```

И возможно ``location.state?.from?.pathname`` можно убрать, я так понимаю все равно всегда идет редирект на главную?

2022-12-05 09:46 UTC, DmitriiNazimov approved these changes

2022-12-05 09:48 UTC, sdelfi commented on packages/client/src/components/PublicRoutes/PublicRoutes.tsx
> +  if (auth) {
Убирать не надо, потому что это работает. Если ты зашёл по прямой ссылке на профиль -тебя кидает на авторизацию, ты подходишь авторизацию и тебя кидает обратно на профиль за счёт этой from

2022-12-05 09:49 UTC, sdelfi commented on packages/client/src/components/PublicRoutes/PublicRoutes.tsx
> +  if (auth) {
Твой код взят из ProtectedRoutes,  а сообщение нужно выводить в PublicRoutes

2022-12-05 10:24 UTC, DmitriiNazimov commented on packages/client/src/components/PublicRoutes/PublicRoutes.tsx
> +  if (auth) {
Код был с ProtectedRoutes, но проблему он не решил так как я думал. При успешном залогинивании все равно показывает "Вы уже авторизованы".

Предлагаю решить проблему другим путем: показывать тост 'Вы авторизованы!', т.е. без слова "уже". Тогда при успешном залогинивании это будет как уведомление об успешном залогинивании, а при повторном заходе на страницу залогинивания это будет сообщение из которого пользователь поймет, что он уже залогинен. 

И все довольны.

2022-12-05 10:26 UTC, sdelfi commented on packages/client/src/components/PublicRoutes/PublicRoutes.tsx
> +  if (auth) {
Добавлю, хорошо. Но после регистрации тоже будет такое сообщение :)

2022-12-05 10:42 UTC, DmitriiNazimov commented on packages/client/src/components/PublicRoutes/PublicRoutes.tsx
> +  if (auth) {
Не вижу ничего страшного. Там будет 2 уведомления:
"Успех! Теперь одним танкистом больше!" и "Вы авторизованы!". Они друг-другу не противоречат, а даже дополняют.

2022-12-05 10:53 UTC, sdelfi commented on packages/client/src/components/PublicRoutes/PublicRoutes.tsx
> +  if (auth) {
"Успех! Теперь одним танкистом больше!"  - а это тоже не будет работать как сделано сейчас :)

Добавил "Вы авторизованы!".
Полагаю, на этом пока можем закончить

2022-12-05 13:28 UTC, sdelfi commented
@Olegas прошу заглянуть сюда. Все замечания устранены, на сколько я могу видеть.

2022-12-05 13:34 UTC, Olegas commented on packages/client/src/store/features/auth/authSlice.ts
> +      state.isAuthenticated = payload !== null;
Я бы посоветовал не делать вычисляемых полей в стейте. Если isAuthenticated вычисляется по наличию профиля, я бы это закопал в селекторе что бы в стейте была только исходная, а не производная информация.

2022-12-05 13:42 UTC, sdelfi commented on packages/client/src/store/features/auth/authSlice.ts
> +      state.isAuthenticated = payload !== null;
Немного уточню.

Т.е. имеется ввиду не хранить isAuthenticated как часть state, а в селекторах просто сделать вычисление isAuthenticated на базе наличия данных профиля? 
Или имеете ввиду что-то иное?

У меня была такая задумка - сейчас у нас для понимания авторизован или нет делается запрос к /me и оттуда же тянется профиль. Т.е. да, isAuthenticated всегда будет определяться наличием данных профиля или нет.

В будущем будет oAuth, т.е. мы, как понимаю, будем хранить токен и на его основе определять - авторизован или нет. А данные профиля будут не зависеть от isAuthenticated. 
Т.е. открываем приложение, видим isAuthenticated  === true и идем за данными профиля в /me в секциях приложения, где нужны эти данные (если уже не были загружены). Т.е. я вижу в будущем что эти сущности будут независимыми. 
Стоит ли в таком случае сейчас делать указанную оптимизацию?

2022-12-05 13:48 UTC, Olegas commented on packages/client/src/store/features/auth/authSlice.ts
> +      state.isAuthenticated = payload !== null;
> Т.е. имеется ввиду не хранить isAuthenticated как часть state, а в селекторах просто сделать вычисление isAuthenticated на базе наличия данных профиля?

Да

> В будущем будет oAuth, т.е. мы, как понимаю, будем хранить токен и на его основе определять - авторизован или нет.

Кажется тут нет противоречия и просто авторизован или нет будет вычисляться из того есть токен или нет. Т.е. при переходе на oAuth поменяется селектор

2022-12-05 14:09 UTC, sdelfi commented on packages/client/src/store/features/auth/authSlice.ts
> +      state.isAuthenticated = payload !== null;
Да, этот момент упустил. 
Поправил, залил

2022-12-05 14:11 UTC, Olegas approved these changes

2022-12-05 14:11 UTC, Olegas commented
Отлично, спасибо!

2022-12-05 14:15 UTC, merged