Task/40 Forum
FrontHeads/tanchiki pull request #27
Opened 2022-12-07 11:47 UTC by Gramoteev

Добавил Форум, с роутингом.

2022-12-07 13:08 UTC, sdelfi requested changes
Все супер, молодец!

Оставил пару некритичных замечаний.

2022-12-07 13:08 UTC, sdelfi commented on packages/client/src/components/Dropdown/Dropdown.css
> +    & > li {
Думаю, что лучше заменить обращение к тегу на класс
Т.е. dropdown__menu-item, например. 
Не критично, но более похоже на БЭМ.

Аналогично с "> li > button"

2022-12-07 13:08 UTC, sdelfi commented on packages/client/src/components/Dropdown/Dropdown.css
> +    & > li {
Посмотрел, у тебя li имеет класс 
`<li key={index} className="menu-item">
`
Сам класс все же поменял бы на dropdown__menu-item

2022-12-07 13:08 UTC, sdelfi commented on packages/client/src/components/Dropdown/Dropdown.test.tsx
> +    const handleClick = jest.fn();
А без mock не работает?
Просто хорошо бы проверять, что после клика меню раскрылось и тогда нужна оригинальная функция. 

Если какие-то сложности без mock, то можно оставить как есть, не критично

2022-12-07 13:08 UTC, sdelfi commented on packages/client/src/components/Dropdown/Dropdown.tsx
> +            <li key={index} className="menu-item">
В соседнем комменте писал, но продублирую - имя класса должно быть, например, dropdown__menu-item

2022-12-07 13:08 UTC, sdelfi commented on packages/client/src/components/Dropdown/Dropdown.tsx
> +      {cloneElement(trigger, {
Интересно сделано, не встречал такого

2022-12-07 13:08 UTC, sdelfi commented on packages/client/src/components/Footer/Footer.tsx
> +        <span>FrontHeads team, {year}</span>
Супер

2022-12-07 13:08 UTC, sdelfi commented on packages/client/src/pages/Forum/Forum.test.tsx
> +    render(<Forum />, { wrapper: MemoryRouter });
Попробуй` renderWithRouter({component: <Forum />}), ` чтобы был единый стиль в тестах.

renderWithRouter - подгружает store  + корректно роутер (MemoryRouter - не является data router, поэтому в некоторых кейсах ругается)

2022-12-07 13:08 UTC, sdelfi commented on packages/client/src/pages/Forum/ForumSection/ForumSection.test.tsx
> +    render(<ForumSection />, { wrapper: MemoryRouter });
Попробуй` renderWithRouter({component: <Forum />}), ` чтобы был единый стиль в тестах.

renderWithRouter - подгружает store  + корректно роутер (MemoryRouter - не является data router, поэтому в некоторых кейсах ругается)

2022-12-07 13:08 UTC, sdelfi commented on packages/client/src/pages/Forum/ForumSection/ForumSection.tsx
> +      <div className="breadcrumbs breadcrumbs_margins_wide">
Надо будет подумать над выносом хлебных крошек в отдельный компонент. Пока не критично, но заметочку сделать

2022-12-07 13:08 UTC, sdelfi commented on packages/client/src/pages/Forum/ForumSectionList/ForumSectionList.test.tsx
> +    render(
Дублируется структура, которую ты передаешь в рендер. 
Может вынести в переменную после 
  const sectionListItem = sectionList[0]; ?

2022-12-07 13:08 UTC, sdelfi commented on packages/client/src/pages/Forum/ForumSectionList/ForumSectionList.tsx
> +        return (
Можно избавиться от return. +1 к красивости :)

2022-12-07 13:08 UTC, sdelfi commented on packages/client/src/pages/Forum/ForumTopic/ForumMessage/typings.ts
> +type LeaderboardRecord = {
Этот тип не экспортируется. Он нужен? По идее, его невозможно использовать нигде за пределами этого файла.

2022-12-07 14:13 UTC, Gramoteev commented on packages/client/src/pages/Forum/ForumTopic/ForumMessage/typings.ts
> +type LeaderboardRecord = {
лишнее. Убрал

2022-12-07 14:13 UTC, Gramoteev commented on packages/client/src/pages/Forum/ForumSectionList/ForumSectionList.tsx
> +        return (
done

2022-12-07 14:48 UTC, Gramoteev commented on packages/client/src/pages/Forum/ForumSectionList/ForumSectionList.test.tsx
> +    render(
done

2022-12-07 14:49 UTC, Gramoteev commented on packages/client/src/pages/Forum/ForumSection/ForumSection.test.tsx
> +    render(<ForumSection />, { wrapper: MemoryRouter });
done

2022-12-07 14:49 UTC, Gramoteev commented on packages/client/src/pages/Forum/Forum.test.tsx
> +    render(<Forum />, { wrapper: MemoryRouter });
done

2022-12-07 15:16 UTC, andreyatx approved these changes
У меня один маленький вопрос, написал в слаке в лс. А так всё классно.

2022-12-07 15:54 UTC, sdelfi commented on packages/client/src/components/Dropdown/Dropdown.test.tsx
> +    const handleClick = jest.fn();
Обсудили, все ок

2022-12-07 15:55 UTC, sdelfi approved these changes

2022-12-09 18:14 UTC, DmitriiNazimov approved these changes
Проделал крутую и большую работу, молодец! У меня всего несколько незначительных замечаний.

Также возможно компоненты breadcrumbs и dropdown есть смысл перенести в page/forum, поскольку они только на форуме используются. Но это не обязательно.

2022-12-09 18:14 UTC, DmitriiNazimov commented on packages/client/src/components/Dropdown/Dropdown.tsx
> +  const [open, setOpen] = useState(false);
Обычно такие переменные называют начиная с is - isOpen. Так понятнее, что эта переменная используется для проверки.

2022-12-09 18:14 UTC, DmitriiNazimov commented on packages/client/src/components/Dropdown/Dropdown.tsx
> +    const handler = (e: MouseEvent) => {
Наверное стоит дать менее абстрактное имя обработчику, более точно отражающее что он делает.

2022-12-09 18:14 UTC, DmitriiNazimov commented on packages/client/src/components/Dropdown/Dropdown.tsx
> +        'data-testid': 'dropdown-trigger',
Кажется, этот testid нигде не используется.

2022-12-12 05:41 UTC, Olegas commented on packages/client/src/components/Dropdown/Dropdown.tsx
> +      {cloneElement(trigger, {
Да, классная штука, я тоже не встречал 👍

2022-12-12 05:58 UTC, Olegas reviewed
Отличная работа, заиспользовали классные штуки - молодцы. 
Написал несколько комментариев.

2022-12-12 05:58 UTC, Olegas commented on packages/client/src/pages/Forum/ForumSection/ForumSection.tsx
> +      <table border={1} className="forum" data-testid="forum-section">
Немного странная компоновка. Заголовок таблицы отдельно от ее содержимого, хотя это явно части одного целого. Представьте что вам понадобится сменить набор колонок - придется менять два компонента вместо одного. Не лучше ли внести определение таблицы и колонок в ForumTopicList?

2022-12-12 05:58 UTC, Olegas commented on packages/client/src/pages/Forum/ForumTopic/ForumMessage/ForumMessage.tsx
> +    <div id={`${id}`} className="forum-message" data-testid="forum-message">
А почему не просто `id={id}`?

2022-12-12 05:58 UTC, Olegas commented on packages/client/src/pages/Forum/ForumTopic/ForumMessage/typings.ts
> +export type ForumMessageProps = {
Как и в других PR (если я не путаю проекты, то в здесь были такие комментарии ранее) предлагаю выделить сущность - Message с основными свойствами. А в компонент ForumMessage передавать (на текущий момент) один параметр - message

Т.е. тип пропсов должен быть вот таким
```
export type ForumMessageProps = {
   message: ForumMessage
}
```

В будущем в компоненты могут добавляться другие свойства (стиль отображения, className, обработчики событий и т.п.) и они не должны мешаться со свойствами бизнес-объекта. + рефакторить проще - при изменении набора свойств не надо через весь проект его тащить + поиск использований проще

2022-12-12 05:58 UTC, Olegas commented on packages/client/src/pages/Forum/ForumTopic/ForumTopic.tsx
> +        <form onSubmit={e => submitHandler(e)} className="forum-topic__new-message">
Можно короче - onSubmit={submitHandler}

2022-12-12 05:58 UTC, Olegas commented on packages/client/src/pages/Forum/ForumTopic/ForumTopic.tsx
> +            onChange={e => textareaChangeHandler(e)}
И тут можно сократить

2022-12-12 05:58 UTC, Olegas commented on packages/client/src/pages/Forum/ForumTopic/ForumTopic.tsx
> +export const ForumTopic: FC<ForumTopicRowProps> = () => {
Тип пропсов объявлен, и он не пустой, а сами пропсы не используются.

2022-12-12 05:58 UTC, Olegas commented on packages/client/src/utils/date-utils.ts
> +export default function simplifyDate(dateString: string): string {
Неконсистентное именование файлов. Судя по всему остальному проекту, файлы именуются camelCase'ом, а тут почему-то kebab-case

2022-12-12 05:58 UTC, Olegas commented on packages/client/src/utils/date-utils.ts
> +  const minutes = (date.getMinutes() < 10 ? '0' : '') + date.getMinutes();
На заметку - у строки есть метод padStart, его удобно использовать для таких задач (где надо каким-то символом добить до нужной длины)

2022-12-12 06:33 UTC, Gramoteev commented on packages/client/src/pages/Forum/ForumTopic/ForumMessage/ForumMessage.tsx
> +    <div id={`${id}`} className="forum-message" data-testid="forum-message">
По причине данной ошибки
![image](https://user-images.githubusercontent.com/51950012/206976999-f68a1e62-1915-487d-95ae-cdfc51828cc4.png)

2022-12-12 06:35 UTC, Gramoteev commented on packages/client/src/pages/Forum/ForumTopic/ForumMessage/ForumMessage.tsx
> +    <div id={`${id}`} className="forum-message" data-testid="forum-message">
тут вижу два варианта, либо хранить id как строку, либо делать трансформацию до рендера. не знаю что правильней

2022-12-12 07:06 UTC, Olegas commented on packages/client/src/pages/Forum/ForumTopic/ForumMessage/ForumMessage.tsx
> +    <div id={`${id}`} className="forum-message" data-testid="forum-message">
Стоп, а зачем нужно id этому div выдавать в принципе?

2022-12-12 07:13 UTC, Gramoteev commented on packages/client/src/pages/Forum/ForumTopic/ForumMessage/ForumMessage.tsx
> +    <div id={`${id}`} className="forum-message" data-testid="forum-message">
Чтобы в будущем можно было копировать анкорные ссылки на сообщения. Убрал пока

2022-12-12 07:16 UTC, Olegas commented on packages/client/src/pages/Forum/ForumTopic/ForumMessage/ForumMessage.tsx
> +    <div id={`${id}`} className="forum-message" data-testid="forum-message">
Это отличная идея! 👍 Тогда да, тут и id обоснован и преобразование к строке вполне законное

2022-12-12 07:41 UTC, merged

2022-12-12 07:47 UTC, Gramoteev commented
@Olegas  Возможно я ошибся, что слил ветку в develop? Или вы не ставили блок на merge?  
Изменения по вашим замечаниям реализовал в последнем коммите.

2022-12-12 08:13 UTC, Olegas commented on packages/client/src/pages/Forum/Forum.tsx
> +      <table border={1} className="forum" data-testid="forum">
По идее и таблицу бы тоже внутрь ForumSectionList утащить бы

2022-12-12 08:15 UTC, Olegas commented
@Gramoteev да, все ок, я не блочил. Все супер, молодцы! Один камент выше - когда составные части таблицы в компонент утаскивали, саму таблицу забыли