Add resources loader
FrontHeads/tanchiki pull request #31
Opened 2022-12-11 15:16 UTC by DmitriiNazimov

2022-12-11 16:41 UTC, sdelfi approved these changes

2022-12-11 16:41 UTC, sdelfi commented on packages/client/src/game/services/Resources/typings.ts
> +export type ImagesList = Record<string, HTMLImageElement>;
Мелочь, можно при желании поправить:

ImageList вместо ImagesList
SoundList  вместо SoundsList

2022-12-11 18:56 UTC, sapomaro requested changes
Круто, что удалось найти спрайт с прозрачным фоном! 

Что касается кода, можно сделать одно архитектурное улучшение: абстрагировать класс Resources по примеру Controller, чтобы можно было прокидывать в него при инициализации список необходимых файлов для загрузки. С другой стороны раздвоение инстансов чуть усложнит код проверки загрузки.

Ну и как я понял, некоторые вещи сделаны временно (метод playSound по идее должен быть в классе Audio, который делает Андрей).

Указал ещё по коду на пару моментов.

2022-12-11 18:56 UTC, sapomaro commented on packages/client/src/game/services/Resources/data.ts
> +  fire: {
Я бы переименовал в shoot, поскольку у нас так называется соответствующий метод в классе Tank.

2022-12-11 18:56 UTC, sapomaro commented on packages/client/src/game/services/Game.ts
> +    this.view.on('assetsLoaded', async () => {
Имеет смысл вынести загрузку картинки с кирпичом из класса View в класс Resources, а то получается странная конструкция с двойным загрузчиком.

2022-12-11 18:56 UTC, sapomaro commented on packages/client/src/game/services/Resources/Resources.ts
> +export const resources = new Resources();
Наверно, лучше не делать этот класс синглтоном, а инициализировать отдельно в сервисах, которые отвечают за графику (View) и звуки (последний ещё пока не создан) и кидать в качестве аргумента при его инициализации конкретный список необходимых вещей для загрузки (imagesData или soundsData). Так лоадер будет более абстрактным и гибким. У нас сейчас так вызывается Controller с разными раскладками клавиатуры. Ну и для обращения к загруженному ресурсу тогда сделать один метод - getResource вместо getImage / playSound (последнее по идее должно быть реализовано в звуковом классе, а не лоадере).

2022-12-11 18:56 UTC, sapomaro commented on packages/client/src/game/services/Resources/Resources.ts
> +  playSound(sound: keyof typeof soundsData): void {
Такой метод должен быть не в лоадере, а в звуковом классе-сервисе. Или это пока на время, чтобы потестить?

2022-12-11 18:56 UTC, sapomaro commented on packages/client/src/game/entities/Tank.ts
> +    resources.playSound('fire');
Как я понял, это сделано временно для тестов, пока у нас нет звукового класса?

2022-12-11 18:56 UTC, sapomaro commented on packages/client/src/game/services/Resources/Resources.ts
> +      if (asset.type === 'image') {
Может, стоит определять тип файла по его расширению? Для этого можно создать отдельный метод. Это сделает список с файлами более простым, и не нужно будет везде повторять тип.

2022-12-11 18:56 UTC, sapomaro commented on packages/client/src/game/services/Resources/Resources.ts
> +      if (resource) {
Если resource не будет инициализирован (сейчас это может произойти, если случайно указать тип, отличающийся от image/sound), то reject сразу не вызовется, и загрузчик повиснет.

2022-12-11 18:56 UTC, sapomaro commented on packages/client/src/game/services/Resources/typings.ts
> +export type AssetData = { type: string; path: string };
Если оставлять императивное указание типов ресурсов, то тогда их лучше чётко прописать, чтобы избежать потенциальных ошибок: type: 'image' | 'sound'.

2022-12-11 20:51 UTC, DmitriiNazimov commented on packages/client/src/game/services/Resources/Resources.ts
> +export const resources = new Resources();
Тут есть что обсудить. 

Я сам за SOLID и красивую архитектуру. Но возможно здесь нет смысла усложнять?
Усложнять есть смысл либо когда текущая архитектура создает проблемы, либо когда могут быть потенциальные проблемы в будущем. В данном случае я не вижу ни того, ни другого (но буду рад если мне подскажут).

1. Чем лучше инициализация загрузчика в разных классах чем синглтон? Синглтон сделан специально, чтобы все ресурсы грузились один раз в одном месте при запуске игры и больше ничего загрузить нельзя было. А то кто-то может вызывать new Resources() в разных частях кода и грузить одно и тоже.
2. Для чего нам больше абстрактности и гибкости у загрузчика ресурсов, который отрабатывает 1 раз при запуске приложения? У контроллера понятно - разные раскладки разным пользователям, виртуальный джойстик. У загрузчика ресурсов будут разные ресурсы для разных пользователей?
3. По поводу звукового класса - а он точно нужен? Что он будет делать кроме проигрывания звука? Пока кажется, что ради одного метода playSound() создавать целый класс смысла нет. По крайней мере на данном этапе. Если мы когда-нибудь реализуем настройки игры, и там будет, например, беззвучный режим, или регулировка громкости - тогда класс Audio может пригодится. Также он бы мог пригодится, если бы мы останавливали звуки на время паузы, но мы решили, что в этом нет необходимости.

Если звуковой класс действительно нужен, то после его написания можно будет переписать Resources и убрать playSound. В принципе Андрей может это реализовать, если ему объяснить что должен делать класс Audio. 

Из того что Андрей записал во время синка в четверг в принципе всё уже реализовано, и кажется более простым способом. Необходимости в классе Audio не возникло, пока.

Вот что было записано у Андрея:
```
1 Создать класс Audio в services
 1.1 В классе Audio реализовать функции обработчики, которые будут запускать проигрывание звуков обр. cattle-bity(levelaudioscripts)
 1.2 В классе Audio реализовать метод registerEntity из Zone и назвать его add
2 В нём загрузить все звуки, связать с загрузкой игры
3 В классе Game реализовать подписку на событие с загрузкой ресурсов
 3.1 В классе Game сделать свойство состояние загрузки ресурсов true/false
 Подписку делать через EventBus см. View extends EventEmitter
4 В Tank вызвать событие через this.emit('shoot')
```

2022-12-11 20:56 UTC, DmitriiNazimov commented
Замечания отмеченные как resolved исправил. Определять тип ресурса по расширению и то что reject не вызовется при неправильном asset.type - это прям топ-комменты 🥇  
Спасибо 👍  
По остальным замечаниям отписался выше - есть что обсудить.

2022-12-11 21:10 UTC, DmitriiNazimov commented on packages/client/src/game/services/Resources/Resources.ts
> +export const resources = new Resources();
Возможно стоит класс Resources воспринимать все-таки не как загрузчик, а именно как класс с ресурсами. Класс загружает ресурсы, хранит и раздает по требованию. Это три разных действия и по-хорошему это должно быть три разных класса. А вообще-то шесть (по 3 класса для картинок и 3 для звуков). Но точно ли нам это нужно сейчас? Да и вообще в принципе.

2022-12-12 05:13 UTC, sapomaro commented on packages/client/src/game/services/Resources/Resources.ts
> +export const resources = new Resources();
Сложности тут особо не будет, но согласен, что нынешний подход тоже рабочий. По поводу отдельного звукового класса: у нас все другие сервисы работают через подписки на события сущностей. Имеет смысл сделать класс Audio по тому же принципу. При такой архитектуре сущности не знают о сервисах, и получается более чистый код. Если же вставлять инстанс класса загрузчика в каждую сущность - это приведет к смешению логики и усложнит расширение/рефакторинг в дальнейшем.

2022-12-12 07:03 UTC, sapomaro approved these changes
Ставлю аппрув с небольшим комментарием. По архитектуре действительно имеет смысл отдельно поговорить и спросить мнение более опытных коллег (@Olegas).

2022-12-12 07:03 UTC, sapomaro commented on packages/client/src/game/services/Resources/helpers.ts
> +export function getAssetType(filePath: string): 'image' | 'sound' | 'unknown' {
Можно подумать над тем, чтобы загнать эту функцию в качестве метода в класс ресурсов, т.к. больше нигде она не нужна.

2022-12-12 07:31 UTC, DmitriiNazimov commented on packages/client/src/game/services/Resources/helpers.ts
> +export function getAssetType(filePath: string): 'image' | 'sound' | 'unknown' {
Я сомневался где лучше разместить - внутри Resources или отдельно. Но если есть товарищеская подсказка, то сомнения развеиваются :) Перенес в Resources.

2022-12-12 09:05 UTC, DmitriiNazimov commented
@Olegas данный PR готов к ревью. И есть архитектурный вопрос, который хотелось бы обсудить, так как мнения в команде разделились. Хотелось бы узнать позицию более опытного коллеги.

Сейчас реализован синглтон-класс Resources, который загружает картинки и звуки и хранит их внутри себя приватно. 

У Resources есть публичные методы getImages() и playSound(). Т.е. если где-то нужна картинка или нужно проиграть звук, то из любого места приложения можно сделать вызов resources.playSound('someSoundName'). 

@sapomaro Алексей считает, что такая архитектура усложнит расширение/рефакторинг в дальнейшем и нужно создать отдельный класс Audio, реализовать там подписочную модель на события через EventBus и проигрывать звуки триггеря события. 

Более развернутые наши рассуждения по этой теме, если они интересны, можно найти выше в комментариях в этом PR. 

**В итоге вопрос**: стоит ли сейчас усложнять архитектуру и выносить playSound в отдельный класс с реализацией подписочной модели?

2022-12-12 15:11 UTC, Olegas commented on packages/client/src/game/services/Resources/Resources.ts
> +export const resources = new Resources();
Я соглашусь с @DmitriiNazimov 
Возможно действительно на текущий момент усложнять не стоит, но потенциал рефакторинга тут есть. Загрузчик - это одно, а проигрыватель - другое.

Схема могла бы быть такая:
1. Загрузчик грузит ресурсы
2. Есть проигрыватель который слушает события от игры (они уже есть - fire, damage и т.п.) и в зависимости от настроек (какое событие какому ресурсу соответствует) получает ресурс из загрузчика и проигрывает его.

Для картинок я бы отдельный не делал. Вот есть загрузчик - он все умеет грузить.

2022-12-12 15:13 UTC, Olegas commented on packages/client/src/game/services/Resources/data.ts
> +  sprite = '../src/game/assets/img/sprite.png',
А тут не должны быть публичные пути которые доступны в собранном приложении. Как это сейчас работает?

2022-12-12 22:32 UTC, DmitriiNazimov commented on packages/client/src/game/services/Resources/data.ts
> +  sprite = '../src/game/assets/img/sprite.png',
Спасибо что обратили внимание! Исправил по всему проекту - перенес все картинки и звуки в папку public. Теперь и на dev сервере и на product ресурсы подгружаются корректно.

2022-12-13 16:04 UTC, Olegas approved these changes

2022-12-13 16:06 UTC, merged