Add project description
FrontHeads/tanchiki pull request #32
Opened 2022-12-12 09:01 UTC by andreyatx

Добавил минимальное описание.

2022-12-12 11:22 UTC, DmitriiNazimov commented
`В игре 70 уровней. После прохождения 35 уровней они повторяются, с повышением сложности. После 70 уровня игра считается пройденной, но какой либо концовки нет. Игра опять начинает отcчёт уровней с первого.`

Вот это я думаю можно сократить до "В игре 35 уровней". 

И блок с механикой игры переместить в самый низ, потому что в первую очередь на гитхабе интересны технические подробности.

2022-12-12 11:22 UTC, DmitriiNazimov approved these changes

2022-12-12 11:26 UTC, DmitriiNazimov commented
Опечатка в "Web Workets"

2022-12-12 13:56 UTC, sdelfi approved these changes

2022-12-12 18:28 UTC, sapomaro requested changes

2022-12-12 18:28 UTC, sapomaro commented on README.md
> +Проект создан в учебных целях в рамках курса [Мидл фронтенд разработчик](https://practicum.yandex.ru/middle-frontend/)
Может добавить к курсу ещё фразу "от Яндекс Практикума"?

2022-12-12 18:28 UTC, sapomaro commented on README.md
> +- Server Side Rendering
Этого и нескольких вещей ниже у нас пока нет. Стоит ли писать сейчас?
Нужно ли к Redux добавить Redux Thunk?
Axios, Vite, Lerna, Jest будем записывать? Некоторые вещи уже есть в бейджиках сверху.

2022-12-12 18:28 UTC, sapomaro commented on README.md
> +## Реализованный функционал
Как минимум половины у нас пока нет из нижеописанного. Предлагаю написать следующее:
- свёрстаны основные страницы (перечислить);
- подключены авторизация и регистрация;
- реализована базовая версия игрового движка (можно выбирать уровни, ездить, стрелять).

2022-12-12 18:28 UTC, sapomaro commented on README.md
> +## Механика игры
Я бы добавил приписку, что часть вещей нам ещё предстоит реализовать.

2022-12-12 18:28 UTC, sapomaro commented on README.md
> +Реализация игры [_Battle City_](https://en.wikipedia.org/wiki/Battle_City) с использованием `Canvas`, `Typescript` и `React`
Можно перед Battle City добавить "веб-версии культовой игры 80-х и 90-х гг.".

2022-12-12 18:28 UTC, sapomaro commented on docs/lerna/README.md
> +Для клиента используется [`react-testing-library`](https://testing-library.com/docs/react-testing-library/intro/)
А Jest? Сюда ещё можно добавить как запускать отдельные тесты (через cd packages/client && yarn jest /path/).

2022-12-12 18:28 UTC, sapomaro commented on docs/lerna/README.md
> +Откройте issue, я приду :)
Это нам нужно? Кто придёт?)

2022-12-12 18:34 UTC, DmitriiNazimov commented on README.md
> +- Server Side Rendering
Axios, Vite, Jest, Thunk можно добавить. 

То что этих вещей нет - ничего страшного. Потом же будет. Один раз напишем readme и забудем. Не вижу смысла растягивать удовольствие :)

2022-12-12 18:37 UTC, DmitriiNazimov commented on docs/lerna/README.md
> +Откройте issue, я приду :)
Это стандартный readme проекта изначального :) Придет hellSquirrel :)) Наверное можно это уже удалить.

2022-12-12 18:38 UTC, DmitriiNazimov commented on README.md
> +## Механика игры
ДУмаю можно сразу написать финальную версию и забыть. Все равно никто читать не будет :)

2022-12-13 05:45 UTC, Olegas approved these changes

2022-12-13 17:28 UTC, sapomaro approved these changes
Можешь внести небольшое исправление по тестам? Предварительно ставлю аппрув.

2022-12-13 17:28 UTC, sapomaro commented on docs/lerna/README.md
> +`yarn jest `<relativePath> - запустить тесты конкретного файла. Например: `yarn jest packages/client/src/components/Form/Form.test.tsx`
Если перейти в директорию клиентского пакета, то в команде yarn jest не нужно указывать packages/client.

Ну и перед RTL имеет смысл добавить ссылку на сам Jest, ведь мы его тоже используем в проекте.

2022-12-14 07:49 UTC, merged