Add Error Boundary
FrontHeads/tanchiki pull request #41
Opened 2022-12-16 10:25 UTC by andreyatx

2022-12-16 10:38 UTC, sdelfi approved these changes

2022-12-16 19:34 UTC, Olegas commented on packages/client/src/layouts/Root/Root.tsx
> +          <ErrorBoundary>{printHeaderAndFooter && <Footer />}</ErrorBoundary>
А почему нельзя сделать один ErrorBoundary на всех?

2022-12-17 08:24 UTC, andreyatx commented on packages/client/src/layouts/Root/Root.tsx
> +          <ErrorBoundary>{printHeaderAndFooter && <Footer />}</ErrorBoundary>
@Olegas чтобы если упал один кусок приложения, то другая его часть не сломалась.

2022-12-17 20:33 UTC, Olegas approved these changes

2022-12-18 07:41 UTC, sapomaro requested changes

2022-12-18 07:41 UTC, sapomaro commented on packages/client/src/layouts/Root/Root.tsx
> +            <Outlet />
Если на одной из страниц добавить в код ошибки, то при переходе на неё будет просить её обновить (что ничего не поменяет) вместо кнопки возвращения на главную.

2022-12-18 07:41 UTC, sapomaro commented on packages/client/src/layouts/Root/Root.tsx
>            {isAppLoading && <Loader data-testid="app-loader" />}
А лоадер и `ScrollRestoration` не нужно обернуть в `ErrorBoundary`?

2022-12-18 07:41 UTC, sapomaro commented on packages/client/src/layouts/Root/Root.tsx
> +          </ErrorBoundary>
Если вставить в хэдер ошибку, то вместо `Outlet` с контентом покажет сообщение об ошибке. В таком случае смысл нескольких ErrorBoundary на разные элементы теряется, можно всё обернуть в один.

2022-12-18 12:49 UTC, sapomaro approved these changes

2022-12-18 12:51 UTC, merged