Add AudioManager class
FrontHeads/tanchiki pull request #42
Opened 2022-12-16 11:11 UTC by andreyatx

2022-12-16 16:36 UTC, sdelfi approved these changes
Супер.
Одно небольшое замечание, больше для красоты

2022-12-16 16:36 UTC, sdelfi commented on packages/client/src/game/services/Game.ts
> +  audioManager!: AudioManager;
Тут "!" точно нужен? Инициализация идет в конструкторе, не должно быть проблем

Т.к. параметры не надо передавать можно просто сделать
 audioManager = new AudioManager();

а из конструктора убрать. Меньше кода и не нужно применять !

2022-12-16 19:18 UTC, sapomaro requested changes
Игра прямо преобразилась со звуками! Всё работает, в том числе в двупользовательском режиме. Оставил в комментах несколько соображений. Надо бы добавить механику глушения всех звуков во время паузы.

2022-12-16 19:18 UTC, sapomaro commented on packages/client/src/game/services/AudioManager.ts
> +      this.playSound('pause');
Пауза уже есть выше. Это, видимо, лишний код.

2022-12-16 19:18 UTC, sapomaro commented on packages/client/src/game/services/Resources/Resources.ts
> +  public soundList: SoundList = {};
Может, оставить это свойство приватным и сделать метод getSound по аналогии с getImage? А то, получается, что изображения берутся через функцию, а звуки - нет.

2022-12-16 19:18 UTC, sapomaro commented on packages/client/src/game/services/AudioManager.ts
> +      this.playSound('pause');
При паузе все другие звуки должны глушиться, в частности idle/move.

2022-12-16 19:18 UTC, sapomaro commented on packages/client/src/game/services/AudioManager.ts
> +    const isEnemy = entity.role === 'enemy';
Хорошие проверки!

2022-12-16 19:18 UTC, sapomaro commented on packages/client/src/game/entities/Entity.ts
> +    this.emit('spawn');
Этот эмиттер нужно поднять на три строчки выше, включив в условие, т.к. при коллизиях танк спавниться не будет.

2022-12-16 19:18 UTC, sapomaro commented on packages/client/src/game/services/AudioManager.ts
> +export class AudioManager extends EventEmitter {
Я бы добавил несколько юнит-тестов на основной функционал, особенно в части навешивания событий (вместо playSound и stopSound можно поставить заглушки jest.fn() и проверять их только на предмет вызова при нужном событии).

2022-12-18 06:07 UTC, sapomaro requested changes

2022-12-18 06:07 UTC, sapomaro commented on packages/client/src/game/services/AudioManager.ts
>          this.mute();
Наверно, вряд ли нужно создавать mute и unmute, т.к. они состоят из одной строчки и вызываются только по одному разу.

2022-12-18 06:07 UTC, sapomaro commented on packages/client/src/game/services/AudioManager.ts
> +          this.stopSound(sound);
После паузы звук стоящего танка `idle` не возвращается. Я бы добавил в класс ещё методы `pauseSound` и `resumeSound` (аналоги `playSound` и `stopSound` без `soundResource.currentTime = 0;`), которые можно вызывать до и после паузы через цикл `activeSounds`.

2022-12-18 06:07 UTC, sapomaro commented on packages/client/src/game/services/AudioManager.test.ts
> +    //** Не смог сделать проверку, что функция playSound не вызывается при паузе */
На самом деле тут нужно сделать код практически такой же, как в первом тесте `should play sounds`: сначала вызвать паузу, затем сделать выстрел из танка, после этого проверить не вызывался ли мок `audioManager.playSound` с аргументом `shoot`.

2022-12-18 13:49 UTC, sapomaro approved these changes

2022-12-18 18:32 UTC, Olegas commented on packages/client/src/game/services/AudioManager.ts
> +}
Классная штука получилась 👍

2022-12-18 18:35 UTC, Olegas approved these changes

2022-12-18 18:59 UTC, merged