Update game scenario
FrontHeads/tanchiki pull request #43
Opened 2022-12-16 16:33 UTC by sdelfi

2022-12-16 19:37 UTC, Olegas commented on packages/client/src/game/services/Scenario.ts
> +    while (entity.spawned === false) {
А для чего здесь такая задержка и цикл, расскажите пожалуйста?

2022-12-16 19:52 UTC, sapomaro reviewed
При переходе на следующий уровень почему-то не затирает квадрат с танком игрока. Он висит в том месте, на котором закончил до этого. Надо бы отловить этот баг. Я посмотрю ещё.

2022-12-16 19:52 UTC, sapomaro commented on packages/client/src/game/services/Game.ts
> +          }
Здесь не нужен else, чтоб перекинуло на первый уровень?

2022-12-16 19:52 UTC, sapomaro commented on packages/client/src/game/services/Game.ts
>      this.overlay.show(ScreenType.LEVEL_SELECTOR, this.level);
Выбор уровня сделан не совсем очевидно, надо бы добавить на этот экран стрелочки и подсказки.

2022-12-16 19:52 UTC, sapomaro commented on packages/client/src/game/services/Scenario.ts
> +      if (++integer !== 1) {
Можно назвать это isFirstTry и сделать через true/false для лучшей читаемости.

2022-12-16 19:56 UTC, sdelfi commented on packages/client/src/game/services/Scenario.ts
> +    while (entity.spawned === false) {
@Olegas Эта часть кода требует доработки, но чуть позже.
Суть в том, чтобы сделать неравномерное появление танков противника. Так же если три позиции спауна заняты, то цикл будет работать непрерывно до момента появления свободного слота. Хотелось сделать задержку, чтобы также чуть уменьшить количество попыток сделать спаун.

В планах перейти на игровой таймаут, вместо штатного, т.к. на время паузы нужно останавливать выполнение всех процессов сценария + более тщательно изучить как происходит логика работы спауна противников.

2022-12-17 07:00 UTC, sapomaro commented on packages/client/src/game/services/Scenario.ts
> +    while (entity.spawned === false) {
Если что, задержка через игровой цикл находится на ревью в соседнем пулл-реквесте (38-м).

2022-12-17 08:44 UTC, sdelfi commented on packages/client/src/game/services/Game.ts
> +          }
Логично. Поправил

2022-12-17 08:49 UTC, sdelfi commented on packages/client/src/game/services/Game.ts
>      this.overlay.show(ScreenType.LEVEL_SELECTOR, this.level);
Готово
![image](https://user-images.githubusercontent.com/1927032/208234020-76adf5a3-69ef-4d6c-8e12-8d347e201c30.png)

2022-12-17 08:50 UTC, sdelfi commented on packages/client/src/game/services/Scenario.ts
> +      if (++integer !== 1) {
Поправил

2022-12-17 08:54 UTC, sdelfi commented
> При переходе на следующий уровень почему-то не затирает квадрат с танком игрока. Он висит в том месте, на котором закончил до этого. Надо бы отловить этот баг. Я посмотрю ещё.

Да, тут хотелось бы совместно посмотреть. Есть еще пару багов на карте, иногда возникают и их источник мне не понятен.
В частности, бывает так, что убиваешь противника в центральной клетке. Он исчезает, но эта клетка остается как-бы занятой, хоть визуально и пустая. Сквозь неё не пройти, вражеские пули не пролетают мимо, пули игрока тоже упираются и ничего не меняют, клетка блокирована

2022-12-17 09:19 UTC, sapomaro commented
Баг с незатиранием танка игрока, по всей видимости, исправлен в моём PR #38 (там в класс Game добавлен метод clearLoopEntities, который деспавнит все сущности при reset).

2022-12-17 19:19 UTC, Olegas approved these changes

2022-12-17 19:44 UTC, sapomaro requested changes
Я что-то не могу отловить баг с пустой клеткой, через которую нельзя проехать/стрельнуть. В начале было, а сейчас почему-то нет. Он может быть связан с тем, что сейчас текущий код инициализирует сразу все 20 вражеских танков и пытается их одновременно поставить на карту. Здесь нужно по-другому сделать, чтобы потом можно было легко setLoopDelay интегрировать из 38-го ПР. Оставил пару комментов ниже. Кстати, в оригинале танки появляются постепенно - по одному. И чем выше уровень, тем меньше задержка с появлением следующего.

2022-12-17 19:44 UTC, sapomaro commented on packages/client/src/game/services/Scenario.ts
>        this.createProjectile(projectile);
Здесь нужно сделать проверку на паузу, иначе снаряд вылетает во время неё.

2022-12-17 19:44 UTC, sapomaro commented on packages/client/src/game/services/Scenario.ts
>        this.createTankEnemy();
Мне кажется, что этот код не совсем оптимален. Он создаёт 20 танков, из которых три-четыре спавняться сразу, а остальные 16 зависают в ожидании и гоняют циклы while с задержкой в 200 мс для проверки возможности отспавниться. 

Лучше сделать отдельный метод для создания вражеских танков без while и вызывать его через интервал (хотя бы пока что обычный setInterval, потом приделаем тот, который работает через игровой цикл). Тогда танки будут создаваться по одному (как в оригинале).

2022-12-17 19:51 UTC, sapomaro commented on packages/client/src/game/services/Scenario.ts
>        this.createTankEnemy();
setLoopDelay уже в ветке develop, так что можно использовать его! Интервал создаётся через рекурсию (можно посмотреть, как сделано в TankEnemy.ts).

2022-12-17 19:55 UTC, DmitriiNazimov commented on packages/client/src/game/services/Scenario.ts
>        this.createTankEnemy();
Самодельный интервал setLoopInterval будет в моем PR, который состоится, надеюсь, завтра. Чтобы не изобретать велосипед как я. setLoopDelay перепрофилировать в интервал мне показалось не очень удачной идеей.

2022-12-18 07:48 UTC, sdelfi commented on packages/client/src/game/services/Scenario.ts
> +    while (entity.spawned === false) {
Интегрировал

2022-12-18 07:53 UTC, sdelfi commented on packages/client/src/game/services/Scenario.ts
>        this.createProjectile(projectile);
Добавил

2022-12-18 08:13 UTC, sdelfi commented on packages/client/src/game/services/Scenario.ts
>        this.createTankEnemy();
Не совсем так, этот while срабатывает 4 раза (максимум игроков на карте, дальше уже запускается createTankEnemy, внутри которого уже while (будет заменен на setLoopDelay), который работает до момента, пока не будет свободной клетки. 
Этот while нужен и он не циклится в бесконечность, сейчас перепроверил (но уже чуть поправив код, возможно раньше и уходил в бесконечный цикл. Сейчас увел в цикл в бесконечность и браузер завис. Т.е. 99%, что такого не было)

2022-12-18 08:41 UTC, sdelfi commented on packages/client/src/game/services/Scenario.ts
>        this.createTankEnemy();
Залил обновленную логику.

2022-12-18 08:45 UTC, sdelfi commented
@DmitriiNazimov @sapomaro правки залиты, можно проверять.
Более продвинутую логику появления, в зависимости от уровня и прочих факторов будем добавлять позже, как будут реализованы все сопутствующие фичи.

2022-12-18 13:35 UTC, sapomaro approved these changes

2022-12-18 18:23 UTC, Olegas approved these changes

2022-12-18 18:54 UTC, DmitriiNazimov approved these changes

2022-12-18 19:11 UTC, merged