Add graphics
FrontHeads/tanchiki pull request #44
Opened 2022-12-19 19:46 UTC by DmitriiNazimov

Из класса Entity просятся на выход методы анимации и методы для работы с таймерами. Но пока коллективно решили оставить их здесь с перспективой рефакторинга в будущем, когда определимся с архитектурными решениями. 

В тестах класса View последний тест похож на интеграционный и его можно бы вынести отдельно, но пока такой тест один на весь проект. В будущем когда(если) интеграционных тестов станет больше - можно будет их вынести в отдельное подходящее место.

2022-12-20 04:52 UTC, sapomaro commented on packages/client/src/game/entities/Entity.ts
> +      this.despawn();
Не совсем логично, что за деспавн сущности отвечает блок с анимацией. По идее должно быть наоборот.

2022-12-20 04:52 UTC, sapomaro commented on packages/client/src/game/entities/EntityDynamic.ts
> +  blocked = false;
В Entity было свойство movable для этого.

2022-12-20 04:52 UTC, sapomaro commented on packages/client/src/game/entities/Entity.ts
> +        this.emit('entityDidUpdate');
Может вынести эти два эмиттера в отдельный метод (например, refresh)? Т.к. они используются несколько раз по коду и могут быть не до конца понятны другим.

2022-12-20 07:35 UTC, sapomaro requested changes
Работа проделана действительно огромная! Всё выглядит суперски! Хочется уже взять и играть. Круто, что удалось дополнительно реализовать функционал защитного поля танка с соответствующей анимацией. 

Оставил несколько соображений по коду. По архитектуре мы уже обсудили на синке насчёт выноса всех спрайтов в класс View.  Мне этот подход нравится больше, но твой тоже рабочий.

2022-12-20 07:35 UTC, sapomaro commented on packages/client/src/game/entities/Entity.ts
> +    settings.name ??= Math.random().toString();
Каков шанс, что рандом выкинет одно и то же значение? Тогда может возникнуть баг с отображением.

2022-12-20 07:35 UTC, sapomaro commented on packages/client/src/game/services/Controller.test.ts
> +import { sleep } from '../utils/sleepTimer';
Отлично! Давно хотел вынести это в отдельный файл.

2022-12-20 07:35 UTC, sapomaro commented on packages/client/src/game/services/Game.ts
> +    entity.on('loopInterval', this.setLoopInterval.bind(this));
Раз ниже clearLoopInterval, может, здесь нужно сделать setLoopInterval, чтоб нейминг был более последовательным?

2022-12-20 07:35 UTC, sapomaro commented on packages/client/src/game/services/Scenario.ts
> +  createExplosion(entity: Tank | Projectile) {
У этого метода здесь слишком сложная логика по сравнению с другими сущностями. Её лучше вынести непосредственно в класс Explosion. Сценарий должен заниматься более общими вещами, и он и так слишком большой и сложный.

2022-12-20 07:35 UTC, sapomaro commented on packages/client/src/game/services/View.ts
> +  drawMainEntitySprite(entity: Entity, context: CanvasRenderingContext2D) {
Сюда мы вторым аргументом передаём контекст канваса, а в другие похожие методы - айди слоя, где лежит этот контекст. Лучше привести к однообразию.

2022-12-20 07:35 UTC, sapomaro commented on packages/client/src/game/services/View.ts
> +    if ('type' in rect && rect.type === 'tank') {
Такая конструкция получилась не очень логически изящной, т.к. у rect в принципе нет типа. Может, вынести эту логику в отдельный метод и вызывать его в соответствующих подписках после метода getActualRect?

2022-12-20 07:35 UTC, sapomaro commented on packages/client/src/game/ui/Overlay.ts
> +  constructor(public view: View, private game?: Game) {
А может, сюда только передавать game? Т.к. view можно получить через game.view.

2022-12-20 13:06 UTC, DmitriiNazimov commented on packages/client/src/game/entities/EntityDynamic.ts
> +  blocked = false;
movable !== blocked

Movable - способен ли обьект в принципе двигаться. Этим отличается динамическая сущность от статичной. Blocked - это временная блокировка динамичной сущности. Подходит для спауна или для перка обездвиживания противников.

Сейчас в коде эти свойства используются для разных проверок и переделывать это не хотелось бы.

2022-12-20 13:17 UTC, DmitriiNazimov commented on packages/client/src/game/entities/Entity.ts
> +    settings.name ??= Math.random().toString();
Я провел много времени за тестами - такого рода багов не замечал ни разу. Изначально была идея сделать `settings.name ??= (performance.now() + Math.random()).toString();`, но показалось это избыточным. Math.random формирует достаточно длинную строку, а анимаций не так чтобы очень много в игре одновременно. Мне кажется вероятность крайне низкая что выпадет одно и тоже значение. 

Примеры что выдает Math.random():
- 0.15593199160805482
- 0.2963212798608714
- 0.9239463698832922

2022-12-20 13:26 UTC, DmitriiNazimov commented on packages/client/src/game/services/Game.ts
> +    entity.on('loopInterval', this.setLoopInterval.bind(this));
Тогда, чтобы нейминг был последовательным, надо и loopDelay переименовать в setLoopDelay? :)

2022-12-20 14:26 UTC, DmitriiNazimov commented on packages/client/src/game/services/View.ts
> +  drawMainEntitySprite(entity: Entity, context: CanvasRenderingContext2D) {
Мне кажется странным опять искать контекст внутри drawMainEntitySprite(), учитывая что мы его уже нашли ранее, но ок. Передаем layerId.

2022-12-20 15:10 UTC, DmitriiNazimov commented on packages/client/src/game/services/View.ts
> +    if ('type' in rect && rect.type === 'tank') {
Не совсем понимаю предложение. Можно пример кода? 
Как вызывать отдельный метод если getActualRect у нас вызывается вот так: 
` context.drawImage(this.spriteImg, ...spriteCoordinates, ...this.getActualRect(entity));
`

2022-12-20 16:59 UTC, sapomaro commented on packages/client/src/game/services/View.ts
> +  drawMainEntitySprite(entity: Entity, context: CanvasRenderingContext2D) {
Можно передавать и контекст, но тогда и в других местах по аналогии неплохо было бы сделать.

2022-12-20 17:45 UTC, DmitriiNazimov commented on packages/client/src/game/services/View.ts
> +  drawMainEntitySprite(entity: Entity, context: CanvasRenderingContext2D) {
Я уже исправил на layerId. В других местах контекст заранее не всегда известен.

2022-12-20 19:25 UTC, DmitriiNazimov commented on packages/client/src/game/entities/EntityDynamic.ts
> +  blocked = false;
Сделаю frozen.

2022-12-20 19:44 UTC, DmitriiNazimov commented on packages/client/src/game/services/View.ts
> +    if ('type' in rect && rect.type === 'tank') {
Ок, назовем аргумент `item`

2022-12-20 21:21 UTC, DmitriiNazimov commented
@sapomaro все указанные замечания доработал в соответствии с тем как мы договорились при созвоне.

2022-12-21 07:40 UTC, sapomaro requested changes

2022-12-21 07:40 UTC, sapomaro commented on packages/client/src/game/entities/Explosion.ts
> +  setProps(entity: Tank | Projectile) {
Этот метод ничего не задаёт, а возвращает, поэтому лучше избежать слова set в названии. Тем более такой же метод есть в классе Entity, и принцип его работы иной.

2022-12-21 07:40 UTC, sapomaro commented on packages/client/src/game/entities/Explosion.ts
> +    super(props);
Тут нужно подумать, т.к. сейчас в качестве пропса передаётся другая сущность, и в Explosion добавляются все её свойства/методы, включая те, которых нет в Entity, от которого взрыв наследуется. Потенциально может привести к багам.

2022-12-21 07:54 UTC, DmitriiNazimov commented on packages/client/src/game/entities/Explosion.ts
> +  setProps(entity: Tank | Projectile) {
Всмысле он ничего не задает? :) Он задает несколько параметров и возвращает их. Именно этот метод определяет тип, размеры и координаты. Он не просто вытаскивает их из Entity и возвращает, а именно сам определяет. 

Get здесь тоже неуместно, потому что он не только возвращает, но и задает.

Можно назвать setExplosionProps чтобы избежать дублирования с методом из Entity.

2022-12-21 08:06 UTC, DmitriiNazimov commented on packages/client/src/game/entities/Explosion.ts
> +    super(props);
>и в Explosion добавляются все её свойства/методы

В Explosion не добавляются свойства и методы передаваемой сущности, потому что сущность сама передается как свойство explosionParentEntity. 

<img width="460" alt="Снимок экрана 2022-12-21 в 11 04 10" src="https://user-images.githubusercontent.com/49460860/208852598-a1cd983d-b4f3-4a11-9e98-70df5b96e447.png">

2022-12-21 08:21 UTC, sdelfi approved these changes
Критических замечаний нет, новых багов не выловил, кроме тех, что уже известны и они не связаны с графикой.

2022-12-21 08:21 UTC, sdelfi commented on packages/client/src/game/entities/Entity.ts
> +  }
Отлично, пригодится

2022-12-21 08:21 UTC, sdelfi commented on packages/client/src/game/entities/Terrain.ts
>          this.color = 'brown';
Нужны ли цвета, когда применены спрайты?

2022-12-21 08:31 UTC, DmitriiNazimov commented on packages/client/src/game/entities/Terrain.ts
>          this.color = 'brown';
Я оставил на всякий случай. Вдруг спрайты не подгрузятся или что-то подобное случится. Места много не занимает, но можно и убрать. У кого-то еще есть мнения на этот счет? @sapomaro

2022-12-21 08:39 UTC, sapomaro commented on packages/client/src/game/entities/Terrain.ts
>          this.color = 'brown';
Мне кажется, лучше оставить. Это может помочь с дебагингом, когда мы добавим новые спрайты.

2022-12-21 08:44 UTC, sapomaro commented on packages/client/src/game/entities/Explosion.ts
> +  setProps(entity: Tank | Projectile) {
Он нигде не переопределяет свойства через this, я про это.

2022-12-21 08:55 UTC, sapomaro commented on packages/client/src/game/entities/Explosion.ts
> +    super(props);
Меня смущает это:

//@ts-expect-error не передаем posX и posY т.к. они есть в props.explosionParentEntity
super(props);

В качестве пропсов сюда поступает танк или снаряд (судя по createExplosion в Scenario). Мне кажется, это не есть хорошо.

Прости, сижу с мобильника, что-то мог упустить. К компу пока нет доступа.

2022-12-21 09:05 UTC, sapomaro commented on packages/client/src/game/entities/Explosion.ts
> +    super(props);
Так-то всё работает, но конструкция с ts-expext-error сама по себе указывает на возможные проблемы. Я думаю, что тут нужно как-то по-другому сделать. Можем это пометить к исправлению в будущем.

2022-12-21 09:07 UTC, DmitriiNazimov commented on packages/client/src/game/entities/Explosion.ts
> +    super(props);
> я не знаю, к какому эффекту это может привести)
Ни к какому. Просто у взрыва будет свойство explosionParentEntity, в котором лежит какая-то сущность. Багов от этого не будет. 

Чтобы вынести логику по взрыву из Scenario, о чем ты просил ранее, нужно как-то передавать в Explosion данные о сущности которая взрывается. Передавать саму сущность - это лучший путь чтобы сократить логику в Scenario. Ну или я могу вытаскивать из сущности только нужные данные и передавать в Explosion только их, но тогда Scenario так и останется с логикой от Explosion.

2022-12-21 09:13 UTC, DmitriiNazimov commented on packages/client/src/game/entities/Explosion.ts
> +    super(props);
>  ts-expext-error сама по себе указывает на возможные проблемы

Это вопрос чисто типизации. Entity ждет posX, т.к. это обязательный параметр, а я не передаю, т.к. Explosion не нужны координаты танка или снаряда, ему нужны собственные координаты которые станут известны только в setExplosionProps. 

Багов тут быть не должно. Предлагаю тебе вечером спокойно за компьютером посмотреть, можно созвониться будет и обсудить. Если что - я исправлю. Это не причина блокировать PR :)

2022-12-21 09:14 UTC, sapomaro commented on packages/client/src/game/entities/Explosion.ts
> +    super(props);
Предлагаю это занести в todo и потом разобраться, чтобы не задерживать производственный процесс.

2022-12-21 09:18 UTC, sapomaro approved these changes

2022-12-21 10:46 UTC, DmitriiNazimov commented
@Olegas PR готов к ревью.

2022-12-21 19:19 UTC, Olegas commented on packages/client/src/game/services/Scenario.ts
> +        this.createExplosion(_entity);
_ перед именем - это что-то означает?

2022-12-21 19:25 UTC, Olegas approved these changes

2022-12-21 19:29 UTC, sdelfi commented on packages/client/src/game/services/Scenario.ts
> +        this.createExplosion(_entity);
Это я добавлял когда _entity не использовалась, иначе ругался TS.

Сейчас да, подчеркивание надо убрать, т.к. не несет смысловой нагрузки.

![image](https://user-images.githubusercontent.com/1927032/208987535-c58f47be-502f-4dfe-87af-18387646efad.png)

2022-12-21 19:49 UTC, merged