Pause the game when a tab becomes inactive
FrontHeads/tanchiki pull request #52
Opened 2022-12-23 19:32 UTC by sdelfi

2022-12-23 20:30 UTC, DmitriiNazimov commented
Прикольно.

2022-12-23 20:30 UTC, DmitriiNazimov approved these changes

2022-12-24 07:28 UTC, Olegas requested changes

2022-12-24 07:28 UTC, Olegas commented on packages/client/src/hooks/usePageVisibility.ts
> +  const [isVisible, setIsVisible] = useState(getIsDocumentHidden(document));
Тут очень странно по неймингу. Переменная isVisible, в нее присвоили значение, которое вернула функция isHidden. То ли где-то забыли отрицание, то ли название не то что нужно

2022-12-24 07:28 UTC, Olegas commented on packages/client/src/utils/webApiUtils.ts
> +export const getBrowserVisibilityProp = (document: Document & { msHidden?: boolean; webkitHidden?: boolean }) => {
Кажется это не prop а eventName или что-то в этом духе.

2022-12-24 07:28 UTC, Olegas commented on packages/client/src/hooks/usePageVisibility.ts
> +    if (visibilityChange) {
А зачем проверка? Разве `getBrowserVisibilityProp` может вернуть пустоту?

2022-12-24 07:28 UTC, Olegas commented on packages/client/src/pages/Game/Game.tsx
> +  const isTabActive = usePageVisibility();
Вообще очень крутая идея - сделать автопаузу. Респект! 👍

2022-12-24 08:55 UTC, andreyatx approved these changes

2022-12-24 10:35 UTC, sdelfi commented on packages/client/src/hooks/usePageVisibility.ts
> +  const [isVisible, setIsVisible] = useState(getIsDocumentHidden(document));
Согласен. 
Поменял getIsDocumentHidden на getIsDocumentVisible, что более логично, т.к. внутри идет 
`return !document.hidden`

2022-12-24 10:37 UTC, sdelfi commented on packages/client/src/hooks/usePageVisibility.ts
> +    if (visibilityChange) {
Раньше мог возвращаться undefined, переделал это, а проверки остались. 
Сейчас действительно лишние, убрал.

2022-12-24 10:42 UTC, sdelfi commented
@Olegas спасибо за ревью. Поправил замечания.

2022-12-24 14:04 UTC, Olegas approved these changes

2022-12-24 14:05 UTC, merged