Add form validation
FrontHeads/tanchiki pull request #53
Opened 2022-12-23 19:40 UTC by Gramoteev

Добавил валидацию для всех форм

2022-12-23 22:13 UTC, sdelfi approved these changes
По функционалу замечаний нет, все отлично, молодец.

Несколько мыслей по нэймингу написал.

2022-12-23 22:13 UTC, sdelfi commented on packages/client/src/components/Form/FieldList/Field/Field.tsx
> +      {validationErrors ? <ValidationErrors validationErrors={validationErrors} /> : null}
Немного странно, что и название компонента и название параметра одинаковое. Тут вообще получается, что 4 раза повторяется одно слово, что выглядит немного запутанно.
Не критично, но может есть смысл чуть исправить, хотя бы название параметра у компонента ValidationErrors

2022-12-23 22:13 UTC, sdelfi commented on packages/client/src/components/Form/Form.css
> +    color: $font_color_red;
Переменная создана ранее, как я понял, но зачем в её названии font_color? Мне кажется, что логично указать только $red, а лучше $danger или $color_danger, т.к. если мы поменяем цвет ошибки с красного на бордовый, то в названии слово "red" будет уже вводить в заблуждение.

2022-12-23 22:13 UTC, sdelfi commented on packages/client/src/components/Form/Form.tsx
> +  const formClassNames = cn('form', {
Молодец, на уровне формы знать, что есть ошибка - это удобно для написания css стилей

2022-12-23 22:13 UTC, sdelfi commented on packages/client/src/utils/validation/config.ts
> +  password_check = 'passwordRules',
Почему-то в одном случае у тебя camelCase,  в другом snake_case. В этом есть какой-то смысл или опечатка?

2022-12-23 22:13 UTC, sdelfi commented on packages/client/src/utils/validation/config.ts
> +export enum ErrorMessage {
Может быть лучше ValidationErrorMessage?

2022-12-23 22:13 UTC, sdelfi commented on packages/client/src/utils/validation/config.ts
> +  notEmptyRules = 'Поле не может быть пустым.',
Для чего в ключах используется слово Rules? Мне кажется, что это лишнее. Или есть какой-то смысл?

2022-12-23 22:13 UTC, sdelfi commented on packages/client/src/utils/validation/validationRules.ts
> +  loginRules(value: string): string[] {
Тоже немного странное наименование. Может лучше написать что-то вроде checkLogin?

2022-12-24 05:43 UTC, Gramoteev commented on packages/client/src/components/Form/FieldList/Field/Field.tsx
> +      {validationErrors ? <ValidationErrors validationErrors={validationErrors} /> : null}
поменял пока на $font_color_danger, т.к. это соответствует именованию переменных для цвета шрифтов в проекте, но думаю, что в целом именование css переменных нуждается в рефакторинге

2022-12-24 05:44 UTC, Gramoteev commented on packages/client/src/components/Form/Form.css
> +    color: $font_color_red;
Поменял пока на $font_color_danger, т.к. это соответствует именованию переменных для цвета шрифтов в проекте, но думаю, что в целом именование css переменных нуждается в рефакторинге

2022-12-24 08:17 UTC, Gramoteev commented on packages/client/src/utils/validation/config.ts
> +  password_check = 'passwordRules',
свойства форм проименованы как на сервере. В будущем можно сделать клиентский transform и привести  написание к единому стилю

2022-12-24 08:53 UTC, andreyatx approved these changes
К замечаниям Станислава мне нечего добавить 👍

2022-12-24 15:56 UTC, Olegas commented on packages/client/src/utils/validation/validationRules.ts
> +    if (!/^(?=.{10,15}$)/.test(value)) {
Если мы проверяем длину, тут достаточно просто length.

2022-12-24 15:56 UTC, Olegas commented on packages/client/src/utils/validation/validationRules.ts
> +    if (!/^[a-zA-Z0-9\-_]+$/i.test(value)) {
Регулярки имеет смысл выносить и переиспользовать, не компилировать их каждый раз при заходе в функцию.

2022-12-24 15:56 UTC, Olegas commented on packages/client/src/utils/validation/config.ts
> +}
Правильнее не делать внутренний словарь соответствия а просто в конфигурацию формы передавать не только имя и тип поля, но еще и валидатор(ы) для него. Тогда библиотека валидаторов и форма не будут "знать" друг о друге и тем более не будут знать о том, какие вообще есть поля

2022-12-24 15:56 UTC, Olegas commented on packages/client/src/utils/validation/validation.ts
> +export function validation(inputs: Record<string, string>, nonRequiredFields?: string[]) {
Обычно "обязательность" поля это просто еще один валидатор. И не надо хранить список "необязательных полей".

2022-12-24 15:56 UTC, Olegas commented on packages/client/src/components/Form/FieldList/FieldList.tsx
> +    [formData, validationErrors]
Мысль на "обсудить и подумать" - валидация в процессе ввода - не всегда хорошо. Представьте у вас ограничение на минимальную длину например. Пользователь только начал вводить а ему уже говорят что он не прав

2022-12-27 07:04 UTC, Olegas requested changes

2022-12-27 07:04 UTC, Olegas commented on packages/client/src/components/Form/FieldList/FieldList.tsx
> +    setValidationErrors(validationErrors);
Здесь в стейт заносится его же текущее значение?

2022-12-27 07:04 UTC, Olegas commented on packages/client/src/components/Form/FieldList/FieldList.tsx
> +    [formData, validationErrors]
Зачем тут зависимость от validationErrors?

2022-12-27 07:04 UTC, Olegas commented on packages/client/src/components/Form/FieldList/FieldList.tsx
> +      const validationResult = validation(formData);
А зачем валидировать всю форму если поменялись данные в одном только поле?

2022-12-27 07:04 UTC, Olegas commented on packages/client/src/components/Form/FieldList/typings.ts
> +  // setValidationErrors: Dispatch<ValidationResponse>;
Зачем тут оставлено так много закомментированных свойств? Давайте не будем замусоривать кодовую базу закомментированным кодом

2022-12-27 07:04 UTC, Olegas commented on packages/client/src/components/ValidationErrors/ValidationErrors.tsx
> +    return <></>;
Лучше return null.

2022-12-27 07:04 UTC, Olegas commented on packages/client/src/utils/validation/validation.ts
> +        if (isSubmitValidation && !field.required && value === '') {
Комментарий сбивает с толку. Получается если я сказал что поле не обязательное, но если заполнено, то должно быть, допустим, не больше 10 символов, то в момент отправки формы эта проверка не будет выполнена? По факту не так - из проверки исключаются только поля с пустым значением. 

Но все равно не понятно зачем. По идее валидаторы должны игнорировать пустое значение если им это не важно.

2022-12-27 07:04 UTC, Olegas commented on packages/client/src/utils/validation/validators.ts
> +    if (!/^(?=.{10,15}$)/.test(value)) {
Проверка длины через регулярку - бесполезная трата ресурсов. Есть же length

2022-12-27 07:04 UTC, Olegas commented on packages/client/src/utils/validation/validators.ts
> +    if (!/^(\+|\d)[0-9]+$/i.test(value)) {
Регулярки лучше объявить на уровне файла тем самым "закэшировав" их. Так интерпретатору не придется постоянно создавать новые

2022-12-28 15:53 UTC, Gramoteev commented
@Olegas Спасибо за внеплановое ревью, коммиты что мы успели запушить делались чисто для командной работы, но тем неменее замечания оказались очень ценными.

Сейчас же я сделал полную проработку всех замечаний, прошу проверить.

2022-12-28 17:21 UTC, Gramoteev commented on packages/client/src/utils/validation/validators.ts
> +    if (!/^(\+|\d)[0-9]+$/i.test(value)) {
Сделал через Объект в файле config

2022-12-28 17:23 UTC, Gramoteev commented on packages/client/src/components/Form/FieldList/FieldList.tsx
> +    [formData, validationErrors]
Решили оставить, т.к. например, если пользователь вводит Имя с маленькой буквы, то об ошибке он узнает, только после переключение на новое поле. ну и у нас сделано, так что сперва пользователь видит не ошибки а подсказки (белым цветом), а вот если он все-таки попробует засабмитить. то уже красим подсказки в красный цвет

2022-12-28 19:04 UTC, Olegas commented on packages/client/src/utils/validation/config.ts
> +};
👍

2022-12-28 19:04 UTC, Olegas commented on packages/client/src/utils/validation/validators.ts
> +    if (value.length < 3 || value.length > 20) {
👍

2022-12-28 19:09 UTC, Olegas commented on packages/client/src/components/Form/typings.tsx
> +  // hasErrors: boolean;
♻️ ?

2022-12-28 19:10 UTC, Olegas commented on packages/client/src/components/Form/typings.tsx
> +  // hasErrors: boolean;
Забыли удалить?

2022-12-28 19:17 UTC, Gramoteev commented on packages/client/src/components/Form/typings.tsx
> +  // hasErrors: boolean;
Да, убрал

2022-12-28 19:21 UTC, Olegas reviewed
Получилось классно, молодцы! Своя библиотечка для работы с формами 👍
Что можно улучшить (не блокирует апрув!): если как-то убрать внутрь "кишочки" с isFormSubmitted (так что бы внешний потребитель не знал об этом флаге а просто получал колбэк что форму засабмитили если ошибок нет) - было бы совсем круто. Это можно сделать с помощью контекста например. Form сделает контекст а FieldList его прочитает. В момент сабмита форма что-то поменяет в контексте, FieldList отреагирует и т.д. 
В общем все как сейчас у вас но "boilerplate" с флагами уйдет внутрь и не будет виден потребителю.

2022-12-28 19:21 UTC, Olegas commented on packages/client/src/components/Form/FieldList/FieldList.tsx
> +    if (validationResponse.errors[name] && !isFormSubmitted) {
А вот тут нет ли ошибки? validation кажется заполняет всегда пустым массивом а пустой массив превращается в булевский true

2022-12-28 19:21 UTC, Olegas commented on packages/client/src/components/Form/FieldList/FieldList.tsx
> +        onFormSubmitCallback();
А не стоит ли всегда делать setIsFormSubmitted(false), независимо от того, были ошибки или нет?

2022-12-28 19:26 UTC, Gramoteev commented on packages/client/src/components/Form/FieldList/FieldList.tsx
> +    if (validationResponse.errors[name] && !isFormSubmitted) {
да, чистая ошибка. поправлю

2022-12-28 19:27 UTC, Gramoteev commented on packages/client/src/components/Form/FieldList/FieldList.tsx
> +        onFormSubmitCallback();
да, по факту оно так и сделано, внутри onFormSubmitCallback(); тоже есть вызов setIsFormSubmitted(false);

2022-12-28 19:32 UTC, Gramoteev commented on packages/client/src/components/Form/FieldList/FieldList.tsx
> +    if (validationResponse.errors[name] && !isFormSubmitted) {
на самом деле тут проверка не нужна, т.к. нам наоборот важно чтобы если у поля name validation вернул пустой массив, то мы перезаписали массив с ошибками на пустой массив.

2022-12-28 19:34 UTC, sdelfi commented on packages/client/src/components/Form/FieldList/FieldList.tsx
> +        onFormSubmitCallback();
Мне кажется, что лучше убрать из onFormSubmitCallback вызов setIsFormSubmitted и сделать общий тут, т.к. в других callback можно и забыть это сделать. Плюс код почище.

2022-12-28 19:37 UTC, Gramoteev commented on packages/client/src/components/Form/FieldList/FieldList.tsx
> +        onFormSubmitCallback();
да. сделал

2022-12-28 20:07 UTC, Olegas approved these changes

2022-12-28 22:26 UTC, DmitriiNazimov requested changes
Есть некоторые замечания по юзабилити. Описал в слаке. 
В остальном очень классная работа! 👍👍👍

2022-12-29 09:51 UTC, DmitriiNazimov approved these changes

2022-12-29 09:53 UTC, merged