Add leaderboard API
FrontHeads/tanchiki pull request #58
Opened 2022-12-28 12:37 UTC by andreyatx

Добавил slice и thunks. 
Пока без сортировки и типов.

2022-12-28 12:47 UTC, sdelfi requested changes
Посмотрел пока часть, позже еще посмотрю

2022-12-28 12:47 UTC, sdelfi commented on packages/client/src/config/constants.tsx
> +    GET: '/leaderboard/FrontHeadsTest',
тут лучше сделать 

GET: (teamName: string) => {return `/leaderboard/${teamName}`}  
И в момент обращения к этому роуту передавать название команды.


teamName - вывести в константы, т.к. используется в разных запросах

2022-12-28 12:47 UTC, sdelfi commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +      ) : (
Можно разделить это на 

if(isLoading) {
return <Loader/>
}

return <основной код>

Более красиво выглядит

2022-12-28 12:47 UTC, sdelfi commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +        ratingFieldName: 'score',
'score' хорошо бы выделить в отдельную константу, т.к. поле с таким же именем надо передавать в data.

2022-12-28 12:47 UTC, sdelfi commented on packages/client/src/store/features/leaderboard/leaderboardSlice.ts
> +      .addCase(leaderboardThunks.getLeaderboard.fulfilled, (state, action: any) => {
Вместо any - PayloadAction<тип payload> 
Посмотри в appSlice.ts

2022-12-28 15:31 UTC, sdelfi commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +  } else {
else не нужен в данном случае.
Ну это я так, для красоты придираюсь :)

2023-01-04 08:52 UTC, DmitriiNazimov commented
По работе сортировки есть пара замечаний:
1. Нет указателя какая колонка отсортирована и в каком порядке. Я верстал такой указатель[ здесь](https://github.com/FrontHeads/tankettes-design). 
2. У user unavalaible пустые колонки "Время" и "#", из-за этого сортировка работает не корректно. Время, Рекорд и Матчи можно ставить 0 по умолчанию, а # не может быть пустым. Какой-то должен быть в любом случае. Наверное номер должен всегда быть вида "1,2,3,4" и т.д. и сортировки по этому столбцу не должно быть. Т.е. номер указывает какое место занимает игрок по текущему виду сортировки.

Код пока не смотрел. Жду сигнала, что все готово для ревью.

2023-01-08 11:37 UTC, sapomaro commented on packages/client/src/pages/Leaderboard/data.ts
> +  },
Названия этих полей нужно сделать поинформативнее. Предлагаю такие варианты: "Рекорд по очкам", "Время в игре (минуты)", "Пройденные уровни" (вместо "Матчи").

2023-01-08 15:35 UTC, andreyatx commented
Время у большинства по нулям, потому что оно стоит меньше одной секунды.

2023-01-08 21:06 UTC, sdelfi commented on packages/client/src/pages/Leaderboard/Leaderboard.test.tsx
> +      // const middlewares: any = [thunk];
Полагаю, что этот закомментированный блок лишний

2023-01-08 21:06 UTC, sdelfi commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +  // }
Лоадер теперь не используется или временно закомментировал? Если не используется, то давай удалим этот блок

2023-01-08 21:08 UTC, sdelfi approved these changes
Пару комментариев, в остальном все ок.

2023-01-09 08:22 UTC, andreyatx commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +  // }
Видимо пока ты писал коммент я уже залил commit :)  [chore(leaderboard): removed comments](https://github.com/FrontHeads/tanchiki/pull/58/commits/07d67b88f24b20a5af5133c29e599a528d65b18a)

2023-01-09 09:56 UTC, DmitriiNazimov commented
<img width="496" alt="Снимок экрана 2023-01-09 в 12 39 56" src="https://user-images.githubusercontent.com/49460860/211278974-ce3f15ae-065b-41ce-b80a-4ba251a1cfa3.png">
Я думаю это не очень хорошо выглядит. 
1. Слово "пользователь" лучше заменить на более короткое "игрок", чтобы маркер не убегал на строку ниже. 
2. Содержание столбца "#" и подсветка первых трех позиций разными цветами должны быть всегда фиксированы. Т.е. у нас меняется сортировка по столбцам "время" или "рекорд", соответственно меняется порядок игроков, но в столбце "#" так и остается "1,2,3,4...". При сортировке в колонке, например, "время" в обратную сторону, соответственно столбец "#" тоже должен сортироваться в обратную сторону - "4,3,2,1". 
3. Идея расписать более подробно "Время", "Рекорды" и т.п. была не очень удачная - на мобилках это все не влезает и смотрится не хорошо. Здесь было бы уместнее оставить короткие заголовки столбцов и сделать для них всплывающие подсказки при наведении курса. В самом базовом варианте это атрибут `alt`, но можно сделать что-то более интересное. Наверняка есть какие-то небольшие библиотеки для всплывающих подсказок. 
4. Размер маркера надо сделать поменьше, чтобы он не убегал на другую строку.

2023-01-09 15:46 UTC, sapomaro requested changes
Проверил - данные с сервера приходят, сортировка работает. Оставил несколько замечаний по коду.

2023-01-09 15:46 UTC, sapomaro commented on packages/client/src/pages/Leaderboard/LeaderboardRow/typings.ts
>  };
Не должен ли этот тип лежать в /src/api/typings.ts? А то сюда за ним тянется leaderboardAPI.ts, что не совсем правильно, т.к. типы API первичны, а для отображения - производные от них.

2023-01-09 15:46 UTC, sapomaro commented on packages/client/src/utils/dateUtils.ts
> +  hours = hours % 24;
А должен ли здесь быть остаток от деления на 24? Вдруг кто-то решит устроить марафон, который продлится больше 24 часов?)

2023-01-09 15:46 UTC, sapomaro commented on packages/client/src/store/features/leaderboard/leaderboardSlice.ts
> +        state.leaderboardTable = payload;
Нужна ли здесь фильтрация данных с сервера на предмет их правильности, чтоб в приложении ничего не ломалось? А то сейчас на собранной странице выводится запись, где `user unavalaible` в имени и `NaN:NaN:NaN` во времени. 

Плюс потом нам нужно будет реализовать фильтрацию от XSS.

2023-01-09 15:49 UTC, sdelfi commented on packages/client/src/store/features/leaderboard/leaderboardSlice.ts
> +        state.leaderboardTable = payload;
Ты точно в правильном месте оставил комментарий? 
В данном куске кода заносятся данные в том виде, в котором пришли.
Сортировка делается в селекторе, не меняя исходных данных.

2023-01-09 15:56 UTC, sapomaro commented on packages/client/src/store/features/leaderboard/leaderboardSlice.ts
> +        state.leaderboardTable = payload;
Я не про сортировку, а проверку серверных данных на предмет их правильности в целом. Вопрос в том, нужно ли заносить в стейт приложения невалидные вещи? Или такие записи лучше на этапе сортировки убирать?

2023-01-09 16:02 UTC, sdelfi commented on packages/client/src/store/features/leaderboard/leaderboardSlice.ts
> +        state.leaderboardTable = payload;
В нашем приложении я бы делал валидацию и фильтр при выводе или в селекторе.
На сколько помню, reducer в данном случае должен быть примитивным.
Данных у нас не много, чтобы беспокоиться, что будет храниться мусор. 
С другой стороны, каждый раз делать фильтр при селекторе - тоже трата ресурсов, хоть и минимальная.

Тот же NaN - это не невалидные данные, это их отсутствие, т.е. вывести эту запись можно, но не выводить данные с NaN, а оставить ячейку пустой.

В общем, в нашем случае - тут дело вкуса, как по мне...

2023-01-09 16:09 UTC, DmitriiNazimov commented on packages/client/src/store/features/leaderboard/leaderboardSlice.ts
> +        state.leaderboardTable = payload;
Мне кажется валидация нужна там где это обычно делается - при отправке данных на сервер. И на самом сервере. Но поскольку доступа к серверу у нас нет, то было бы логично сделать валидацию при отправке. Тогда не будет болеть голова с валидацией при получении данных с сервера и при выводе на странице.

2023-01-09 16:11 UTC, DmitriiNazimov commented on packages/client/src/store/features/leaderboard/leaderboardSlice.ts
> +        state.leaderboardTable = payload;
Согласен что NaN - это некрасиво. Записи из БД можно удалять? Если можно - надо удалить. Если нет - надо сделать костыльную заглушку чтобы не показывать такой кошмар. Можно ее сделать при получении данных с сервера или при выводе на страницу, мне не принципиально.

2023-01-09 16:25 UTC, sapomaro commented on packages/client/src/store/features/leaderboard/leaderboardSlice.ts
> +        state.leaderboardTable = payload;
Валидация на клиенте тоже не помешает, особенно с учетом того, что данные на сервер могут поступать от кого угодно и какие угодно. Чтобы не усложнять, можно сделать фильтрацию при выводе или в селекторе, как советует Станислав.

2023-01-09 16:27 UTC, sdelfi commented on packages/client/src/store/features/leaderboard/leaderboardSlice.ts
> +        state.leaderboardTable = payload;
Да, с Алексеем согласен, что в идеале валидация должна быть и на сервере и на клиенте. 
И при отправке и при получении данных. Никому нельзя доверять :)

2023-01-09 16:42 UTC, DmitriiNazimov commented on packages/client/src/store/features/leaderboard/leaderboardSlice.ts
> +        state.leaderboardTable = payload;
> Никому нельзя доверять

Нельзя доверять клиенту. 

Собственному бекенду обычно доверять можно. Хотя в нашем случае бекенд сторонний, на нем нет валидации, поэтому если хочется, то можно сделать валидацию и при получении данных с бэка. Но это не является стандартной практикой.

2023-01-09 16:44 UTC, sdelfi commented on packages/client/src/store/features/leaderboard/leaderboardSlice.ts
> +        state.leaderboardTable = payload;
И бэкенду тоже нельзя, даже если есть к нему доступ. 
По крайней мере на вебинаре такая точка зрения была озвучена.
По опыту - валидация и на клиенте и на сервере - гарантированно меньше проблем.

2023-01-09 16:45 UTC, DmitriiNazimov commented on packages/client/src/store/features/leaderboard/leaderboardSlice.ts
> +        state.leaderboardTable = payload;
На каком вебинаре?

2023-01-09 16:47 UTC, sdelfi commented on packages/client/src/store/features/leaderboard/leaderboardSlice.ts
> +        state.leaderboardTable = payload;
В я.практикуме, в каком именно уже не вспомню

2023-01-11 14:25 UTC, sapomaro reviewed
Вроде бы, всё работает, как мы договорились на синке. Я бы в столбце с порядковыми номерами развернул треугольник сортировки в противоположную сторону. Оставил ещё пару комментов по коду.

2023-01-11 14:25 UTC, sapomaro commented on packages/client/src/pages/Leaderboard/data.ts
>    },
Я бы предложил сюда в качестве `fieldName` слово "Очки", т.к. "Рекорд" не совсем отражает суть. У пользователя может сложиться впечатление, что это рекорд по времени или пройденным уровням. Тем более подсказка на мобильниках всплывать не будет.

2023-01-11 14:25 UTC, sapomaro commented on packages/client/src/api/leaderboardAPI.ts
> +      });
Если вдруг в поле придёт `null`, то всё упадёт, т.к. он не умеет делать `toString()`. Поэтому надо ещё проверить, чтоб типы были `string` (для 'username') или `number` (для 'score', 'time' и 'matches'). Можно ещё удостовериться, чтоб они были целыми и положительными числами. Заморачиваться с дополнительными проверками на Infinity и размеры чисел, наверно, не стоит, сортировка должна с ними работать.

2023-01-11 14:25 UTC, sapomaro commented on packages/client/src/api/leaderboardAPI.ts
>  };
Мне всё-таки кажется не совсем правильным тянуть в `/api` типы из `/pages`. Поправьте меня, если я не прав. К тому же здесь есть `ReceivedRecordData`, правда, судя по всему, он нигде не используется.

2023-01-11 14:32 UTC, sapomaro commented on packages/client/src/api/leaderboardAPI.ts
> +      });
Т.к. мы сервак не контролируем, и туда любой может записывать какие угодно данные, надо всё обезопасить, чтоб, к примеру, разгневанные своими поражениями игроки из соседних команд не смогли ничего нам сломать. Вдруг кто решит поупражняться в хакерстве)

2023-01-11 16:52 UTC, andreyatx commented on packages/client/src/api/leaderboardAPI.ts
>  };
Переложил

2023-01-11 19:14 UTC, sapomaro approved these changes
Валидация теперь хорошо отсеивает недопустимые значения, табличку уже так просто не сломать. Ставлю аппрув. Пока листал код - откомментил по нескольким незначительным моментам.

2023-01-11 19:14 UTC, sapomaro commented on packages/client/src/api/leaderboardAPI.ts
> +      const timeLimitation = !isValidNumber(data.time) || data.time > 3.564e8;
Я бы написал в комментарии, что это 99 часов.

2023-01-11 19:14 UTC, sapomaro commented on packages/client/src/api/leaderboardAPI.ts
> +        return typeof num === 'number' && num >= 0 && num % 1 === 0 && num.toString().length <= 20;
`num.toString().length <= 20` - эта проверка что-то даёт с учётом, того, что у нас дальше числа сравниваются?

2023-01-11 19:14 UTC, sapomaro commented on packages/client/src/config/constants.tsx
> +export const DEFAULT_LIMIT = 999;
Может, для большей ясности переименовать эти поля в LEADERBOARD_TEAM_NAME, LEADERBOARD_SORT_FIELD, LEADERBOARD_RECORDS_DISPLAY_LIMIT?

2023-01-11 19:14 UTC, sapomaro commented on packages/client/src/utils/dateUtils.ts
> +  return `${padTo2Digits(hours)}:${padTo2Digits(minutes)}`;
Раз секунды ушли, их можно убрать.

2023-01-11 19:38 UTC, andreyatx commented on packages/client/src/api/leaderboardAPI.ts
> +        return typeof num === 'number' && num >= 0 && num % 1 === 0 && num.toString().length <= 20;
По-идее, нет. Забыл её убрать, когда добавил сравнения для каждого случая

2023-01-11 22:27 UTC, DmitriiNazimov requested changes
1. Номера сбиваются (видно на скрине). Должно быть всегда 1,2,3 или 3,2,1, но не 2,3,1.
2. nit: При клике на новый столбец было бы логично чтобы сортировка была по убыванию, а при повторном клике по возрастанию. Сейчас она чередуется от столбца к столбцу (видимо потому что единый тоглер на все виды сортировки).
3. nit: маркер вверх и маркер вниз - это разные символы. В одном случае треугольник с высокой вершиной, в другом с низкой вершиной. Желательно привести к единообразию.
4. nit: В мобильной версии почему-то отступ справа от таблицы больше чем отступ слева (видно на скрине).
<img width="444" alt="Снимок экрана 2023-01-12 в 01 27 06" src="https://user-images.githubusercontent.com/49460860/211931332-9a5169f5-d4a6-4846-954e-5a2df41ab6d6.png">

2023-01-12 06:11 UTC, Olegas commented
> * Содержание столбца "#" и подсветка первых трех позиций разными цветами должны быть всегда фиксированы. Т.е. у нас меняется сортировка по столбцам "время" или "рекорд", соответственно меняется порядок игроков, но в столбце "#" так и остается "1,2,3,4...". При сортировке в колонке, например, "время" в обратную сторону, соответственно столбец "#" тоже должен сортироваться в обратную сторону - "4,3,2,1".
> *

А точно так? Разве от способа сортировки меняется смысл? Выделяются же те, кто "получил медали", а сортировка это просто разный способ построить таблицу.

2023-01-12 06:13 UTC, Olegas commented
> 3\. nit: маркер вверх и маркер вниз - это разные символы. В одном случае треугольник с высокой вершиной, в другом с низкой вершиной. Желательно привести к единообразию.

Как вариант - треугольник всегда один и вертеть его через CSS transform

2023-01-12 06:13 UTC, Olegas requested changes
Не нашел где добавляются новые данные в таблицу (API есть а вызова - нет) по результату игры. Возможно пока просто не сделали. Хотел увидеть как обновление данных реализовано...

2023-01-12 06:13 UTC, Olegas commented on packages/client/src/components/BurgerMenu/BurgerMenu.tsx
>    });
Вот здесь в useEffect явно зависимостей не хватает. Он точно зависит от внешней переменной isBurgerMenuVisible. Поставьте ESLint правило react-hooks/rules-of-hooks и настройте что бы оно было error - позволяет много ошибок найти

2023-01-12 06:13 UTC, Olegas commented on packages/client/src/pages/Leaderboard/data.ts
> +    title: 'Сколько уровней пройдено ',
Лишний пробел в конце?

2023-01-12 06:13 UTC, Olegas commented on packages/client/src/pages/Leaderboard/LeaderboardRow/LeaderboardRow.tsx
> +    leaderboardRowClassName = `leaderboard__row${sortDirection == 'desc' ? '_asc' : '_desc'}`;
В такие места бы комментарий добавлять... Не сразу понятно почему для какого-то поля нужно сортировку как-бы перевернуть.

2023-01-12 06:13 UTC, Olegas commented on packages/client/src/store/features/leaderboard/leaderboardSlice.ts
> +      state.sortDirection === 'desc' ? (state.sortDirection = 'asc') : (state.sortDirection = 'desc');
Я правильно понимаю что у вас всегда направление сортировки тоглится на противоположное, даже если вы меняете поле, по которому идет сортировка?

2023-01-12 06:13 UTC, Olegas commented on packages/client/src/store/features/leaderboard/leaderboardSlice.ts
> +        state.isLoading = true;
А во время добавления новой записи действительно нужно ставить loading? У вас просто когда loading весь контент лидерборда пропадает. ИМХО будет мигать и будет не красиво

2023-01-12 06:13 UTC, Olegas commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +        limit: LEADERBOARD_RECORDS_DISPLAY_LIMIT,
А вот эти поля - limit и ratingFieldName - они ведь всегда для вашего приложения такие и никакие другие. Может их внутрь thunk'а убрать что бы они в прикладном коде не мешались? API попроще будет

2023-01-12 07:31 UTC, DmitriiNazimov commented
> А точно так? Разве от способа сортировки меняется смысл? Выделяются же те, кто "получил медали", а сортировка это просто разный способ построить таблицу.

В моем понимании подсветка привязывается не к конкретным игрокам, а ей выделяются первые три строчки таблицы.

В моем понимании от разной сортировки смысл меняется. Когда мы сортируем по очкам - хотим узнать кто больше набрал очков. Когда сортируем по времени - хотим узнать кто был самым быстрым и т.п. 

Соответственно номер в таблице и подсветка строк показывают кто был самым быстрым, кто больше всего набрал очков и т.п.

Уже не первый раз поднимается этот вопрос, долго на синке обсуждали. Раз так, то возможно моя позиция не совсем верная, раз нуждается в постоянных пояснениях.

> Как вариант - треугольник всегда один и вертеть его через CSS transform
В макете верстки, кстати, так и было сделано, а здесь получилось по-другому.

2023-01-12 08:35 UTC, andreyatx commented on packages/client/src/components/BurgerMenu/BurgerMenu.tsx
>    });
Добавил зависимость

2023-01-12 08:41 UTC, andreyatx commented on packages/client/src/store/features/leaderboard/leaderboardSlice.ts
> +        state.isLoading = true;
Логично, не стоит

2023-01-12 09:19 UTC, andreyatx commented on packages/client/src/store/features/leaderboard/leaderboardSlice.ts
> +      state.sortDirection === 'desc' ? (state.sortDirection = 'asc') : (state.sortDirection = 'desc');
Сделал, чтобы при выборе всегда сначала было по-убыванию

2023-01-12 10:32 UTC, DmitriiNazimov approved these changes

2023-01-12 11:56 UTC, Olegas approved these changes
Молодцы!

2023-01-12 13:12 UTC, merged