feat(ssr): add SSR to the app
FrontHeads/tanchiki pull request #59
Opened 2022-12-30 17:31 UTC by sdelfi

2022-12-30 17:31 UTC, sdelfi commented
@FrontHeads/frontheads развлекайтесь :)

2023-01-01 19:41 UTC, DmitriiNazimov reviewed
У меня ошибки в консоли при работе dev сервера. А продакшн сборку вообще не поулчилось запустить - тоже ошибки. Приложил скрины с ошибками. 
<img width="657" alt="Снимок экрана 2023-01-01 в 22 17 56" src="https://user-images.githubusercontent.com/49460860/210182849-441cf96d-d2a0-4366-a536-c612d3787458.png">
<img width="1295" alt="Снимок экрана 2023-01-01 в 22 17 21" src="https://user-images.githubusercontent.com/49460860/210182851-cc150bf7-d3ba-4667-9a5c-aebfab572a5d.png">

2023-01-01 19:41 UTC, DmitriiNazimov commented on packages/server/index.ts
> +  const port = Number(process.env.SERVER_PORT) || 3001;
Наверное стоит эту переменную назвать serverPort - так будет более понятно и более единообразно с clientPort.

2023-01-01 19:41 UTC, DmitriiNazimov commented on packages/server/index.ts
>  import cors from 'cors';
Основополагающий файл по SSR + он довольно объемный, поэтому хотелось бы побольше комментариев, чтобы было проще разобраться что здесь происходит и зачем.

2023-01-01 19:41 UTC, DmitriiNazimov commented on package.json
> +    "preview": "yarn build && lerna run preview --parallel"
Было бы хорошо в readme вкратце описать какие команды для чего.

2023-01-01 19:50 UTC, sdelfi commented
> У меня ошибки в консоли при работе dev сервера. А продакшн сборку вообще не поулчилось запустить - тоже ошибки. Приложил скрины с ошибками. <img alt="Снимок экрана 2023-01-01 в 22 17 56" width="657" src="https://user-images.githubusercontent.com/49460860/210182849-441cf96d-d2a0-4366-a536-c612d3787458.png"> <img alt="Снимок экрана 2023-01-01 в 22 17 21" width="1295" src="https://user-images.githubusercontent.com/49460860/210182851-cc150bf7-d3ba-4667-9a5c-aebfab572a5d.png">

Запусти команде yarn в корне, нужно обновить пару пакетов просто. 90%, что проблема в этом

2023-01-01 20:04 UTC, DmitriiNazimov commented
1. Я тупица, конечно надо было запустить yarn. Запустил, пакеты обновились. 
2. К сожалению это не решило всех проблем. На dev сервере ошибки в консоли так и есть.
3. При запуске yarn preview ошибок нет, но при попытке открыть, например http://127.0.0.1:3000/game возникают другие ошибки в консоли, а также появляются сообщения о работе Service Worker. Не уверен что это ожидаемое поведение. При этом страницы сайта и игра работают без нареканий. 
<img width="662" alt="Снимок экрана 2023-01-01 в 23 02 35" src="https://user-images.githubusercontent.com/49460860/210183292-a91eb69f-8e17-4176-920c-c70401534bee.png">

2023-01-01 20:08 UTC, sdelfi commented
> 1. Я тупица, конечно надо было запустить yarn. Запустил, пакеты обновились.
> 2. К сожалению это не решило всех проблем. На dev сервере ошибки в консоли так и есть.
> 3. При запуске yarn preview ошибок нет, но при попытке открыть, например http://127.0.0.1:3000/game возникают другие ошибки в консоли, а также появляются сообщения о работе Service Worker. Не уверен что это ожидаемое поведение. При этом страницы сайта и игра работают без нареканий.
> 
> <img alt="Снимок экрана 2023-01-01 в 23 02 35" width="662" src="https://user-images.githubusercontent.com/49460860/210183292-a91eb69f-8e17-4176-920c-c70401534bee.png">

Отлично.

Открывай на 3001 порту. 3000 надо будет убрать, но пока не стал убирать, вижу, что в в настройках докер он есть. 
Забыл предупредить.

В пачке уточнял у Олега. Вкратце - 3000 это без SSR,  поэтому ошибки, что spa версия не соответствует серверной версии кода.

2023-01-01 20:10 UTC, sdelfi commented
Добавил описание к PR, чтобы другие не запутались.

2023-01-01 20:44 UTC, DmitriiNazimov commented
На 3001 вот что. 

Пробовал и с yarn dev и с yarn preview и даже их вместе - результат на 3001 порту всегда такой. 

<img width="864" alt="Снимок экрана 2023-01-01 в 23 43 01" src="https://user-images.githubusercontent.com/49460860/210184113-64d0bbb7-a2fb-404c-9d76-4380a4ec4cc3.png">

2023-01-01 20:48 UTC, sdelfi commented
> На 3001 вот что.
> 
> Пробовал и с yarn dev и с yarn preview и даже их вместе - результат на 3001 порту всегда такой.
> 
> <img alt="Снимок экрана 2023-01-01 в 23 43 01" width="864" src="https://user-images.githubusercontent.com/49460860/210184113-64d0bbb7-a2fb-404c-9d76-4380a4ec4cc3.png">

Что-то новое. Попробую у себя воспроизвести. Спасибо

2023-01-01 20:51 UTC, DmitriiNazimov commented
Может я что-то не так делаю? Пригодилась бы инструкция как запускать проект правильно и какие команды для чего нужны. Было бы полезно и в описание PR добавить и в readme проекта.

2023-01-01 20:56 UTC, sdelfi commented
Это добавлю, хорошо. 
Ничего не поменялось, в принципе. Запуск такой же, как и ранее, только порт сервера использовать, т.к. у нас переход на SSR

2023-01-01 20:59 UTC, sapomaro commented
Залил небольшой фикс для сервис-воркера, чтобы в консоле не было ошибок из-за расширений Хрома. Сам SSR гляну попозже, когда досмотрю соответствующие вебинары. Дополнительные комменты/описания были бы очень кстати!

2023-01-01 21:01 UTC, sdelfi commented
Комментарии оставлял, но добавлю ещё. Часть кода из документации, поэтому туда ничего не добавлял, вставлено как есть.

2023-01-01 21:02 UTC, sdelfi commented
По ошибке Headers - возможно, что-то связанное с версией nodejs. Какая версия установлена?
Пока проверить не могу, не у компьютера

2023-01-01 21:35 UTC, DmitriiNazimov commented
Обновил ноду до 19.3.0 - запустилось на 3001 порту. Думаю стоит указать, что нужна свежая версия ноды. Была 16 версия. 

Но это опять не решило всех проблем :) 

1. При загрузке страницы с игрой вылезают сообщения об авторизации. 
2. В консоли 100500 сообщений от сервис воркера и ошибка. 

<img width="1658" alt="Снимок экрана 2023-01-02 в 00 31 36" src="https://user-images.githubusercontent.com/49460860/210185198-d3a40075-1151-4a41-99e0-55589dc7a450.png">

2023-01-01 21:40 UTC, sdelfi commented
Игра это зона приватная, поэтому SSR по факту рендерит форму авторизации, что логично. Но spa скрипт видит, что ты авторизован и редиректит обратно.
Тут нужно совместно решить этот момент.
Технически работает верно. Но не очень логично из-за лишних редиректов. 

По скрину не вижу ошибки, вижу просто логирование SW,  с SSR в данном случае не связано. Ошибку одну вижу, но она тоже не пересекается с SSR.  

Про версию ноды - напишу в readme. Я тестировал на той, что у меня установлена,  поэтому подвоха с версией не ждал :(

2023-01-01 21:49 UTC, DmitriiNazimov commented
> Игра это зона приватная, поэтому SSR по факту рендерит форму авторизации, что логично. Но spa скрипт видит, что ты авторизован и редиректит обратно.

Я догадался почему так происходит, и действительно все логично. Но не для юзера, который не поймет почему ему эти сообщения показываются. Видимо для этих тостов надо добавить какое-то правило, чтобы они не показывались при первом рендеринге при работе SSR, или как-то так. Или может быть чтобы SSR вообще не работал для приватных роутов (SEO не нужно приватным роутам, а скорость отрисовки у нас и так адекватная, и без SSR).

Ошибка, да, кажется не связана с SSR, а только с SW. Но наверное не очень правильно что SW у нас отрабатывает и не отключается при работе SSR.

2023-01-01 21:53 UTC, sdelfi commented
Тосты отображаются не в отрендеренной части, а уже скрипт поверх это делает и у меня нет пока идей как можно идентифицировать то, что ты описал. Поэтому считаю лучше это обсудить всем на звонке. 

Про SW -  он должен работать и при работающем SSR, потому что цель SWзакешировать, а SSR отрендерить приложение на сервере. Они не зависят друг от друга.

2023-01-01 22:11 UTC, DmitriiNazimov commented
> Поэтому считаю лучше это обсудить всем на звонке.

Ок. Может быть можно проверять глобальную переменную через которую прокидывается initialState для стор? Типа если она существует, то не выводим тосты. Просто озвучил мысль, пока она не убежала. Обсудим на синке третьего числа.

> Про SW - он должен работать и при работающем SSR, потому что цель SWзакешировать, а SSR отрендерить приложение на сервере. Они не зависят друг от друга.

Просто когда я использую ветку develop на 3000 порту у меня в консоли нет никаких сообщений от SW. Появляются только если сымитировать отключение интернета. 
А когда я использую ветку с SSR на 3001 порту у меня 100500 сообщений в консоли от SW. Я не понимаю почему и нормально ли это. 

Если это нормально, то надо наверное отключить эти сообщения в консоли от SW, потому что сложно пользоваться консолью когда там 100500 сообщений при открытии страницы и при каждом переходе на новый роут.

2023-01-01 22:18 UTC, sdelfi commented
По SW ничего не менялось. Сообщения на скрине это не ошибки, а логирование. Я ничего не менял в SW,  возможно, дело в чем-то другом. Алексей подскажет

2023-01-01 22:21 UTC, DmitriiNazimov commented
> Сообщения на скрине это не ошибки, а логирование. 

Да, я вижу, что это не ошибки (хотя одна все-таки была на скрине, но это не принципиально) :)

@sapomaro нужно твое экспертное мнение по SW. Почему он спамит в консоль при  работе SSR.

2023-01-01 22:22 UTC, sdelfi commented
Про состояние, что передает сервер - не уверен, что можно сделать правильно.
Возможно, нужно просто проверять авторизацию, но это логично сделать после внедрения oauth

2023-01-01 22:24 UTC, sdelfi commented
> > Сообщения на скрине это не ошибки, а логирование.
> 
> Да, я вижу, что это не ошибки (хотя одна все-таки была на скрине, но это не принципиально) :)
> 
> @sapomaro нужно твое экспертное мнение по SW. Почему он спамит в консоль при работе SSR.

Это больше похоже на включенное логирование. Возможно, галочка включено или нет логирование тоже кешируется и если его выключить, то нужно обновить SW в браузере. Но это теория.
Не могу проверить, не у компьютера сегодня.

2023-01-02 07:46 UTC, sdelfi commented
> > Сообщения на скрине это не ошибки, а логирование.
> 
> Да, я вижу, что это не ошибки (хотя одна все-таки была на скрине, но это не принципиально) :)
> 
> @sapomaro нужно твое экспертное мнение по SW. Почему он спамит в консоль при работе SSR.

Логирование было включено изначально и не отключалось. Поэтому странно, что у тебя не отображается на develop ветке. 
![Uploading image.png…]()

В остальном по замечаниям подправил, тестирую и заливаю коммит.

2023-01-02 09:17 UTC, DmitriiNazimov approved these changes
Замечаний больше нет. Отлично комментарии расписал по SSR!

2023-01-02 11:07 UTC, sapomaro commented
> > Сообщения на скрине это не ошибки, а логирование.
> 
> Да, я вижу, что это не ошибки (хотя одна все-таки была на скрине, но это не принципиально) :)
> 
> @sapomaro нужно твое экспертное мнение по SW. Почему он спамит в консоль при работе SSR.

@DmitriiNazimov, чтобы не спамилось в консоль нужно отключить REPORTING в самом SW, а также через функцию регистрации в main.tsx (т.е. в двух местах). Плюс я залил в эту ветку небольший фикс для ошибки с chrome-extension, так что после обновления сервис-воркера у тебя её быть не должно. Единственное, новый сервис-воркер загружается не мнгновенно, поэтому она должна пропасть со второго захода на страницу.

2023-01-02 11:39 UTC, sapomaro commented
Добавил ещё один небольшой фикс для SW: с catch при сохранении в кеш - на случай новых непредвиденных исключений.

2023-01-02 17:18 UTC, sapomaro approved these changes
Титанический труд проделан. Проверил - продакшен работает без ошибок.

2023-01-02 17:18 UTC, sapomaro commented on packages/client/package.json
> +    "preview": "vite preview",
Получается, build ушёл из preview в клиентском пакете, т.к. в корневом он, наоборот, появился. Чтобы два раза не собиралось при запуске из-под корня, верно?

2023-01-02 17:24 UTC, sdelfi commented on packages/client/package.json
> +    "preview": "vite preview",
Да, все верно. При сборке сервера тоже сначала идёт билд, поэтому решил вынести в корневой package.json.
Есть вероятность, что при настройке docker нужно будет сделать наоборот, но поменять не сложно.

2023-01-07 11:23 UTC, Olegas requested changes

2023-01-07 11:23 UTC, Olegas commented on package.json
> +    "build": "yarn build:client && yarn build:server",
А разве это не одно и то же? Или тут порядок важен?

2023-01-07 11:23 UTC, Olegas commented on packages/client/src/layouts/Root/Root.tsx
> +     */
А не в том ли дело, что в спрятали асинхронность внутри ответа лоадера? Как система снаружи поймет, что данные у вас еще грузятся? Не правильнее ли было вернуть промис, который зарезолвится объектом { user: .... }? Что-то мне кажется что и все проблемы со staticRouter уйдут и не придется ставить костыли

2023-01-07 11:23 UTC, Olegas commented on packages/client/src/layouts/Root/Root.tsx
> +            {typeof document !== 'undefined' ? <ScrollRestoration /> : null}
А из-за этого не будет ругани постоянно что исходная верстка не соответствует тому, что ожило на клиенте? Почему нельзя ScrollRestoration всегда присовать?

2023-01-07 11:23 UTC, Olegas commented on packages/client/src/store/store.ts
> +const preloadedState = typeof window !== 'undefined' ? window?.__PRELOADED_STATE__ : undefined;
А зачем тут ? после window? Только что проверили что он не undefined же.

2023-01-07 15:22 UTC, sdelfi commented on package.json
> +    "build": "yarn build:client && yarn build:server",
Верно, важен порядок. Сначала надо собрать ssr билд который затем используется при сборке сервера.

2023-01-07 15:24 UTC, sdelfi commented on packages/client/src/layouts/Root/Root.tsx
> +     */
Спасибо, проверю такой вариант.

2023-01-07 15:25 UTC, sdelfi commented on packages/client/src/layouts/Root/Root.tsx
> +            {typeof document !== 'undefined' ? <ScrollRestoration /> : null}
Нет, это проверял. По сути, scroll restoration ничего не рендерит, как я понял. Внутри заложена только логика работы с window.scroll

2023-01-07 15:26 UTC, sdelfi commented on packages/client/src/store/store.ts
> +const preloadedState = typeof window !== 'undefined' ? window?.__PRELOADED_STATE__ : undefined;
Верно, поправлю

2023-01-07 16:57 UTC, Olegas commented on packages/client/src/layouts/Root/Root.tsx
> +            {typeof document !== 'undefined' ? <ScrollRestoration /> : null}
А он мешает SSR? Зачем его отключили?

2023-01-07 17:02 UTC, sdelfi commented on packages/client/src/layouts/Root/Root.tsx
> +            {typeof document !== 'undefined' ? <ScrollRestoration /> : null}
Была ошибка при обращении к объекту window при рендере на сервере. Появилась одна мысль, попробую убрать это условие. Но ранее было пару попыток это решить и помог только этот вариант

2023-01-07 17:54 UTC, sdelfi commented on packages/client/src/layouts/Root/Root.tsx
> +            {typeof document !== 'undefined' ? <ScrollRestoration /> : null}
Убрал проверку и все работает. 
Судя по всему, помогло изменение конфигурации (делал для решения другой проблемы с axios)

```js
ssr: {
    format: 'cjs',
},
```

![image](https://user-images.githubusercontent.com/1927032/211163964-9cae906a-86d2-49bd-bdef-778c1fc07092.png)

Сейчас ошибки не возникает

2023-01-07 17:58 UTC, sdelfi commented on packages/client/src/store/store.ts
> +const preloadedState = typeof window !== 'undefined' ? window?.__PRELOADED_STATE__ : undefined;
Убрал знак вопроса, теперь так 
`const preloadedState = typeof window !== 'undefined' ? window.__PRELOADED_STATE__ : undefined;`

Если делать так 
`const preloadedState = window?.__PRELOADED_STATE__;`

то получаю

ReferenceError: window is not defined

2023-01-07 18:05 UTC, sdelfi commented on packages/client/src/layouts/Root/Root.tsx
> +     */
Похоже, что не до конца понял мысль.

Сейчас loader возвращает promise и прописывается в конфиге роутов, как в документации:
![image](https://user-images.githubusercontent.com/1927032/211164236-39bb8bee-7bab-4813-879a-4eab8ba61938.png)

Далее в компоненте читаем объект с user: Promise, ждем результата выполнения и заносим в store данные.
![image](https://user-images.githubusercontent.com/1927032/211164274-8f366575-9898-4ec2-a6c6-3efd6bb57158.png)

Так вот, после интеграции StaticRouterProvider для SSR вот тут в data
let data = useLoaderData() as { user: Promise<ResponseType<UserDTO>> };

возвращается не data: {user: Promise}, а просто data: {user: {}}
Т.е. куда-то исчезает Promise. 

Можно уточнение - что и куда надо добавить/убрать?

2023-01-07 19:09 UTC, Olegas commented on packages/client/src/layouts/Root/Root.tsx
> +     */
> Сейчас loader возвращает promise и прописывается в конфиге роутов, как в документации:

Это не так. loader НЕ возвращет Promise. Он возвращает объект, в котором есть поле user в котором содержится Promise.

2023-01-07 19:17 UTC, sdelfi commented on packages/client/src/layouts/Root/Root.tsx
> +     */
Верно, но в случае сборки SSR (инициализация роутера через createStaticRouter) - возвращается {user: {}}, а не {user: Promise}

![image](https://user-images.githubusercontent.com/1927032/211166869-1652ba54-3dd1-4b18-9b4d-50313c26c0c1.png)
![image](https://user-images.githubusercontent.com/1927032/211166877-dfa6baed-07f6-4827-9ffe-f414575c7700.png)


А вот без SSR (когда роутер инициализируется через createBrowserRouter)
![image](https://user-images.githubusercontent.com/1927032/211166914-f351ab29-bfdd-4bc7-b0ac-d8488bd92691.png)

2023-01-07 19:27 UTC, sdelfi commented on packages/client/src/layouts/Root/Root.tsx
> +     */
Похоже, разобрался. 
Когда выполняется loader на сервере, в catch отдается null. 
А нужно отдавать Promise.resolve(), чтобы не возникало ошибки

2023-01-07 19:27 UTC, Olegas commented on packages/client/src/layouts/Root/Root.tsx
> +     */
По документации loader должен вернуть промис, а не объект с промисом. Промис не может с сервера сериализоваться вот и приходит пустой объект вместо него. Сделайте правильно. Пусть у вас loader возвращает Promise<{user: SomeUserData}> и я уверен, все взлетит без костылей с роутером, ручным запуском лоадера и then в компоненте. Вам из useLoaderData сразу вывалится все готовое и ничего ждать не надо

2023-01-07 19:41 UTC, Olegas commented on packages/client/src/layouts/Root/Root.tsx
> +     */
> Когда выполняется loader на сервере, в catch отдается null.
> А нужно отдавать Promise.resolve(), чтобы не возникало ошибки.

Да не в этом дело. У вас loader не правильный в принципе.
Вот такой надо сделать

```
export const loader = async () => {
   try {
      const user = await API.me();
      return { user }
   } catch() {
      return { user: null }
   }
}
```

2023-01-07 20:27 UTC, sdelfi commented on packages/client/src/layouts/Root/Root.tsx
> +     */
@Olegas 
Спасибо. Теперь стало понятней как работает loader.

Однако, в нашем случае это тоже не заработало.

Проблема 1: сервер вообще не отвечает, если делать await в loader. Причина не ясна, возможно, это на моем окружении и axios виснет при попытке отправить запрос к API, таймаут пробовал ставить на 1-2 секунды).

Что интересно, поменял обращение к другому тестовому API и зависание пропало. Такое ощущение, что Яндекс API не отвечает при запросе со стороны сервера (но почему не работает установка timeout - не понимаю)
![image](https://user-images.githubusercontent.com/1927032/211169096-a0edb65b-8e0a-47a9-afc4-80bdd84da630.png)

 
Проблема 2: если все же решаем проблему 1, то при отправке запроса со стороны сервера ответ будет всегда null, т.е. проверить авторизован ли пользователь или нет - мы не можем.

Далее, на стороне клиента уже не отправляется запрос на получение данных авторизованного юзера и приложение, логично, редиректит на страницу авторизации, где при попытке авторизоваться API говорит, что пользователь уже авторизован. 

Выходит, что либо оставлять мой хак (по сути он делает запрос и на клиенте, если на сервере запрос не прошел), либо переделывать предзагрузку данных о пользователе иным способом, без использования функционала роутера, т.к. для SSR нужно использовать именно StaticRouter (согласно документации + делал эксперименты)

Я правильно мыслю или что-то упускаю?

2023-01-08 14:57 UTC, Olegas commented on packages/client/src/layouts/Root/Root.tsx
> +     */
Хм... а ведь и верно... Авторизация ведь в cookie, а значит если сервер пойдет в апишку Яндекса, у него не будет этой cookie. Получается что данные о пользователе мы никогда тут не получим. Видимо в текущей ситуации никак на этапе SSR мы данные получить не можем (

2023-01-08 15:46 UTC, sdelfi commented on packages/client/src/layouts/Root/Root.tsx
> +     */
Значит я в верном направлении мыслю.
Сделал ещё ряд экспериментов, чтобы, например, данные пользователя все же подгружать через клиентский код, но тогда возникает проблема, что при hydrate вываливается ошибка несоответствия верстки клиента с версткой сервера.
И ещё множество проблем ловил, пока экспериментировал с разными подходами.
Предлагаю тогда оставить мой начальный вариант с хаком, т.к. из всех опробованных он генерирует код открытых разделов и во всех вариациях запуска приложения не вызывал ошибок.

2023-01-08 20:02 UTC, Olegas commented on packages/client/src/layouts/Root/Root.tsx
> +     */
Да, давай оставим как было. Но вообще у меня кажется появилось решение....

2023-01-08 20:47 UTC, sdelfi commented on packages/client/src/layouts/Root/Root.tsx
> +     */
Откатил на ту версию, что обсуждали.
Про потенциальное решение интересно послушать, посмотреть. 
У меня пока идеи иссякли.
Пробовал еще сделать по такому принципу https://reactrouter.com/en/main/guides/deferred#deferred-data-guide , но безрезультатно.
У меня ни в какую не заработало вот это, пробовал с defer и без, пробовал await в loader или уже в Root ждать результат - на 3001 порту (SSR) приложение не запускалось, ошибок не было, на 3000 - отрабатывало
![image](https://user-images.githubusercontent.com/1927032/211218221-7b849017-5325-421d-bba7-42a384cd3fc3.png)

Но в любом случае - статус авторизации на сервере не узнать, поэтому даже если заставить работать этот код, то будут ошибки из-за несоответствия версии сервера с клиентской версией при вызове метода hydrate.


Вспомнил еще - data.user - должен содержать Promise, потому что в Root.tsx используется React.Suspense -> Await, который как раз ожидает завершения Promise, показывая в это время компонент Loader. Плюс во всех тестах, где рендерится <Root> сделан код, который ожидает завершения отображения этого Loader и затем уже начинается тест. 
Предпоследний commit мой как раз задел это поведение, поэтому пришлось прилично поменять тесты. Но решение с коммита как раз на всех страницах рендерит код лоадера, а сами страницы нет (это корректное поведение в том случае, но смысл SSR в таком случае сводится на нет)

2023-01-10 16:01 UTC, sdelfi commented on packages/client/src/layouts/Root/Root.tsx
> +     */
@Olegas ап

2023-01-10 19:59 UTC, Olegas approved these changes

2023-01-10 20:04 UTC, merged