Add Leaderboard page
FrontHeads/tanchiki pull request #6
Opened 2022-11-26 08:52 UTC by andreyatx

Добавил страницу лидерборда.

2022-11-26 08:59 UTC, sdelfi requested changes
Файл RatingRow.css если не используется, то лучше убрать + линтер ругается на это. 

Пару замечаний по стилям, надо слить develop к себе сначала, в остальном все хорошо.

2022-11-26 08:59 UTC, sdelfi commented on packages/client/src/index.css
> +#root {
Вот тут у тебя "вернулись" старые стили, которые менял Дмитрий.
Лучше слей в свою ветку свежую develop сначала.

2022-11-26 09:44 UTC, sdelfi approved these changes

2022-11-26 09:58 UTC, DmitriiNazimov requested changes

2022-11-26 09:58 UTC, DmitriiNazimov commented on packages/client/src/config/constants.tsx
> +export const DUMMY_LEADERBOARD = [
Данные конкретного компонента не стоит класть в общий файл конфига/констант. Они же ведь не нужны остальному приложению и вообще это временно необходимая штука. 

Лучше в папке со страницей создать файл DummyData.tsx и положить данные туда. А когда фейковые данные перестанут быть нужны этот файл просто удалить.

2022-11-26 10:27 UTC, DmitriiNazimov approved these changes

2022-11-26 20:34 UTC, DmitriiNazimov requested changes

2022-11-26 20:34 UTC, DmitriiNazimov commented on packages/client/src/pages/Leaderboard/Leaderboard.test.tsx
> +describe('Leaderboard', () => {
Названия тестов должны начинаться с 'it' или 'should'.

2022-11-27 18:57 UTC, DmitriiNazimov approved these changes

2022-11-28 09:31 UTC, Olegas requested changes

2022-11-28 09:31 UTC, Olegas commented on packages/client/src/index.css
> +root,
Здесь что-то не так. Нет такого тэга root. Возможно это опечатка от `#root`

2022-11-28 09:31 UTC, Olegas commented on packages/client/src/index.css
> +main {
И здесь что-то не так. Нет такого тэга - main. Может пропустили класс или идентификатор?

2022-11-28 09:31 UTC, Olegas commented on packages/client/src/pages/Leaderboard/Leaderboard.css
> +@import url("../../variables.css");
Отдельный файл с переменными - супер! 👍

2022-11-28 09:31 UTC, Olegas commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +                key={row.place}
Предложение: рассмотрите вариант выделить тип, описывающий бизнес-сущность "запись лидерборда" и передавать его отдельным пропсом `<LeaderboardRow item={row} ... />`

Так не надо будет менять постоянно пропсы при рефакторинге сущности, код будет короче + будет понятная сущность выделена.

2022-11-28 09:31 UTC, Olegas commented on packages/client/src/pages/Leaderboard/LeaderboardRow/LeaderboardRow.tsx
> +    <tr className="leaderboard__row">
А где объявлен этот класс? Как обеспечивается что файл с данным классам точно подгружен? Лучше стили для LeaderboardRow хранить в отдельном файле и подключать его в самом компоненте. Так а) вы точно будете уверены что стили подключены б) будет понятен скоуп этого стиля - кто его использует в) проще рефакторить, проще ограничить скоуп изменений

2022-11-28 09:31 UTC, Olegas commented on packages/client/src/pages/Leaderboard/typings.ts
> +};
Предложение: рассмотрите вариант хранить тайпинги для пропсов всегда месте с компонентом. Так проще читать код - в одном файле сразу все видно: что придет, что может не прийти, какие у этого типы. Когда тайпинги в другом файле - сложнее читать.

Выделять в отдельный файлы имеет смысл какие-то общие штуки, бизнес-сущности и т.п.

2022-11-28 10:09 UTC, DmitriiNazimov commented on packages/client/src/pages/Leaderboard/typings.ts
> +};
Мы рассматривали варианты как хранить типы и пришли к выводу, что лучше в отдельном файле. Всем в коллективе так удобнее. Наверное не стоит менять ранее принятое сознательное решение.

2022-11-28 10:19 UTC, Olegas commented on packages/client/src/pages/Leaderboard/typings.ts
> +};
Как я и написал - это предложение, я не буду тут настаивать. Ну и к слову - менять какие-то практики организации проекта - нормально. Если поработали и поняли что есть вариант лучше и опять же все согласны - можно и поменять.

2022-11-28 10:19 UTC, sdelfi commented on packages/client/src/pages/Leaderboard/typings.ts
> +};
@Olegas @DmitriiNazimov 

Возникает вопрос - если у нас только тип props указан, т.е. можно взять за правило - если 1-2 типа, то в файле компонента, если больше, то выносим.
Или это бардак будет и не практикуется так?

2022-11-28 10:21 UTC, sdelfi commented on packages/client/src/index.css
> +root,
Тут как раз меняли с #root на .root в другом PR, т.к. хорошая практика не привязывать стили к id, хоть тут и корневой элемент гарантированно один и уникален.

2022-11-28 10:26 UTC, Olegas commented on packages/client/src/pages/Leaderboard/typings.ts
> +};
Не думаю что дело в количестве. Моя практика - пропсы всегда с компонентом. Если есть какие-то еще тайпинги и интерфейсы которые нужны соседям (например какая-то структура, которая нужна и Leaderboard и LeaderbordRow) - выносим в файл, кладем рядом с этими компонентами. Если это бизнес-сущность которая идет через все приложение - выносим совсем куда-то наверх.

2022-11-28 10:28 UTC, Olegas commented on packages/client/src/index.css
> +root,
Но в итоге тут ни то и ни другое а явная ошибка в селекторе. А есть этот другой PR?

2022-11-28 10:32 UTC, DmitriiNazimov commented on packages/client/src/index.css
> +root,
Андрей уже исправляет, скоро сделает пуш. Тут надо добавить точку чтобы ссылаться на класс .root, а не тег root. А выше на 15 строчке есть правила для #root - их надо удалить, т.к. это про одно и тоже.

2022-11-28 10:53 UTC, andreyatx commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +                key={row.place}
Я поправил. Но был бы рад если вы посмотрите, и скажете как можно было лучше

2022-11-28 11:03 UTC, Olegas requested changes

2022-11-28 11:03 UTC, Olegas commented on packages/client/src/pages/Leaderboard/LeaderboardRow/typings.ts
> +export type LeaderboardRowType = {
Я бы вот тут еще поправил по неймингу. Пропсы оставил LeaderboardRowProps а вот тип для данных записи назвал бы LeaderboardItem или LeaderboardRecord. А то получается название (*Props) не соответствует действительности.

2022-11-28 11:03 UTC, Olegas commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +                key={row.place}
Супер! Один небольшой коммент по неймингу и будет 🔥

2022-11-28 11:19 UTC, andreyatx commented on packages/client/src/pages/Leaderboard/LeaderboardRow/typings.ts
> +export type LeaderboardRowType = {
@Olegas у меня такой вопрос: как тут деструктуризацией воспользоваться, чтобы писать 
`<td>{place}</td>` вместо  `<td>{row.place}</td> `

```
export const LeaderboardRow: FC<LeaderboardRecord> = ({ row }) => {
  return (
    <tr className="leaderboard__row">
      <td>{row.place}</td>
      <td>{row.username}</td>
      <td>{row.record}</td>
      <td>{row.time}</td>
      <td>{row.matches}</td>
    </tr>
  );
};
```

2022-11-28 11:30 UTC, Olegas commented on packages/client/src/pages/Leaderboard/LeaderboardRow/typings.ts
> +export type LeaderboardRowType = {
Можно так:
```
const { place, username, record, time, matches } = row;
return (...
```

Можно вот так:
```
export const LeaderboardRow: FC<LeaderboardRecord> = ({ row: { place, username, record, time, matches } }) => {
```

2022-11-28 11:31 UTC, Olegas requested changes

2022-11-28 11:31 UTC, Olegas commented on packages/client/src/pages/Leaderboard/LeaderboardRow/typings.ts
> +export type LeaderboardRecord = {
Нее, не так (
Вот этот тип - это описание пропсов, который идут в компонент. Он должен называться LeaderboardRowProps

А тот что первый в этом файле - вот именно он LeaderboardRecord

2022-11-28 11:38 UTC, Olegas approved these changes

2022-11-28 11:38 UTC, Olegas commented
Все супер, молодцы! 🚀

2022-11-28 11:49 UTC, merged