Adjust game entity movement
FrontHeads/tanchiki pull request #60
Opened 2022-12-30 19:49 UTC by sapomaro

Changelog:
- игровой цикл перешёл на requestAnimationFrame;
- изменена логика нанесения урона;
- изменена логика движения снарядов;
- добавлены методы для регулировки скорости движения и стрельбы танков;
- добавлен класс для танка игрока;
- сделаны небольшие исправления и улучшения (теперь можно играть без загруженной графики).

2022-12-30 20:24 UTC, DmitriiNazimov requested changes
Круто что так быстро получилось реализовать! Отрисовка анимаций стала плавнее, как мне кажется. 
Заметил небольшой баг и оставил пару незначительных замечаний.

2022-12-30 20:24 UTC, DmitriiNazimov commented on packages/client/src/game/entities/Projectile.ts
> +  calculateExposionRect() {
Тут наверное exp**l**osion, а не exposion?

2022-12-30 20:24 UTC, DmitriiNazimov commented on packages/client/src/game/services/Zone.ts
> +  doDamage(rect: Rect, entity: Entity) {
Тут бы пригодился комментарий описывающий метод.

2022-12-30 20:24 UTC, DmitriiNazimov commented on packages/client/src/game/entities/Projectile.ts
> +  calculateExposionRect() {
Не уверен что проблема именно здесь, но взрыв теперь отрисовывается со смещением от попадания снаряда. На скриншоте видно - снаряд попадает в стену на уровне центра танка, однако взрыв отрисовывается правее. Проблема актуальна для разных направлений. 
<img width="249" alt="Снимок экрана 2022-12-30 в 23 20 42" src="https://user-images.githubusercontent.com/49460860/210109288-824993c7-460c-4475-925a-d10e443f2081.png">

2022-12-31 07:50 UTC, sapomaro commented on packages/client/src/game/entities/Projectile.ts
> +  calculateExposionRect() {
Отлично, что заметил! Добавил необходимые корректировки в класс `Explosion`.

2022-12-31 08:17 UTC, sdelfi approved these changes
Все отлично, игра стала значительно плавнее.
Хотел записать на видео, вдруг что найду, но видео, похоже, с малым количеством fps и на нем как будто подтормаживания. Вживую не так.

Единственное показалось, что анимация защитного поля у игрока на старте и мерцание звездочки в месте появления врага слишком быстрая. 
Также при первом запуске у меня танки ехали как-то замедленно, но потом этого не смог повторить

[screen-recorder-sat-dec-31-2022-09-13-01.webm](https://user-images.githubusercontent.com/1927032/210130214-213b460e-6dcb-448f-a56e-ccb0addb7a23.webm)

2022-12-31 08:34 UTC, DmitriiNazimov approved these changes

2022-12-31 08:37 UTC, DmitriiNazimov commented
После слов Станислава заметил еще один баг появился: 
- анимация щита работает нормально пока танк стоит, но если начать движение, то она работает слишком часто. Раньше такой проблемы не было. Видимо теперь появилась какая-то связь между движением танка и работой прикрепленных к нему анимаций, раньше они были независимы.

2022-12-31 08:44 UTC, sdelfi commented
А взрыв игрока так должен быть? Пуля взрывается рядом, в этом плане
![image](https://user-images.githubusercontent.com/1927032/210130817-32987520-76b1-4f27-aec8-564818d65da4.png)

2022-12-31 09:02 UTC, DmitriiNazimov commented
> А взрыв игрока так должен быть?
Взрыв танка сделан со смещением относительно центра танка, чтобы не перекрывать взрыв снаряда. В Cattle Bitty также сделано. Но возможно есть смысл уменьшить это смещение. Мне казалось смещение меньше было, возможно тоже в этом PR немного сбилась коррекция смещения.

2022-12-31 09:13 UTC, DmitriiNazimov commented
>  Видимо теперь появилась какая-то связь между движением танка и работой прикрепленных к нему анимаций, раньше они были независимы.

Нет, они не были независимы. Баг был незаметен т.к. скорость отработки анимации щита равнялось скорости смены кадров при движении танка. 

Наверное надо во View добавить проверку, что перерисовка анимации отрабатывает только если прошло достаточное количество циклов.

2022-12-31 09:36 UTC, DmitriiNazimov commented
Эта пара строк решает проблему лишней (слишком частой) отработки анимации.
<img width="1143" alt="Снимок экрана 2022-12-31 в 12 35 30" src="https://user-images.githubusercontent.com/49460860/210131985-62d24d5d-582e-4134-8f58-20b30c1cbc58.png">

2022-12-31 18:18 UTC, Olegas approved these changes

2022-12-31 18:20 UTC, merged