Add indicators bar
FrontHeads/tanchiki pull request #62
Opened 2023-01-04 21:45 UTC by DmitriiNazimov

Добавил боковую панель с индикаторами, где выводится информация о том, сколько танков противника еще не отспаунились, сколько у игрока осталось жизней и на каком уровне он сейчас находится. 

Также улучшил растягивание канваса под размеры экрана и добавил автоматический ресайз канваса при изменении размера окна.

2023-01-05 10:25 UTC, sapomaro requested changes
Всё работает, супер! Оставил несколько соображений по коду.

2023-01-05 10:25 UTC, sapomaro commented on packages/client/src/game/services/View.ts
> +    });
Методы, которые начинаются с `get`, по идее, должны только производить вычисления. А тут ещё навешивается обработчик на событие `resize`. В будущем это может привести к багам, если кто-то захочет повторно вызвать данный метод, чтобы пересчитать pixelRatio, - тогда на окно навесится ещё один ресайз. 

Соответственно, я предлагаю переименовать `getPixelRatio()` в что-то наподобие `initResizing()`. В нём же можно задавать `this.pixelRatio`, а в конструкторе оставить только вызов самого метода.

2023-01-05 10:25 UTC, sapomaro commented on packages/client/src/game/ui/Overlay.ts
> +  renderSplashScreen(backgroundColor: 'black' | '#636363' = 'black') {
Код нового серого цвета повторяется несколько раз, наверно, его лучше вынести в константу.

2023-01-05 10:25 UTC, sapomaro commented on packages/client/src/game/ui/UIElement.ts
> +    this.type = props.indicatorName ? 'indicator' : 'custom';
Не правильнее ли будет задавать тип "индикатор" при создании сущности в `IndicatorManager.renderElement()`?

2023-01-05 10:25 UTC, sapomaro commented on packages/client/src/game/services/IndicatorManager/IndicatorManager.ts
> +    this.game.loop.registerTimerHandlers(elem);
А индикаторы разве где-то используют задержки/интервалы?

2023-01-05 10:25 UTC, sapomaro commented on packages/client/src/game/services/Scenario.ts
> +          this.indicatorManager.renderPlayerLives(Player.PLAYER2, 0);
А нужно ли при уничтожении флага скидывать жизни игрока в индикаторе до нуля?

2023-01-05 10:25 UTC, sapomaro commented on packages/client/src/game/services/Game.ts
> +  settings: GameSettings = { width: 62, height: 56, boundarySize: 2 };
Может, прописать здесь дополнительное свойство `indicatorsSidebarSize` по аналогии с `boundarySize`? Чтобы было понятно, что из чего складывается. А то переменная `rightBoundarySizeCorrection` в классе `Scenario` недостаточно информативна, и её расположение там не особо логично, т.к. к сценарию как таковому она прямого отношения не имеет.

2023-01-05 10:25 UTC, sapomaro commented on packages/client/src/game/services/IndicatorManager/IndicatorManager.ts
> +      text: lives.toString(),
Надо бы сделать небольшой отступ перед цифрой с жизнью игрока, а то сливается со значком танка. Как вариант, в `posX` можно передать дробное значение, сервис `View` должен это переварить, если я не ошибаюсь.

Ещё нужно подумать над тем, что делать, если жизней будет больше 9. Интересно, в оригинале есть какой-то лимит?

2023-01-05 11:11 UTC, DmitriiNazimov commented on packages/client/src/game/ui/Overlay.ts
> +  renderSplashScreen(backgroundColor: 'black' | '#636363' = 'black') {
Почему-то другие цвета не в константах всем были норм :) Вынес все цвета в константы.

2023-01-05 11:16 UTC, DmitriiNazimov commented on packages/client/src/game/ui/UIElement.ts
> +    this.type = props.indicatorName ? 'indicator' : 'custom';
Если указывать там, то в UIElement перезапишется на 'custom'. В любом случае в UIElement нужно делать какую-то проверку пришел custom или indicator.

2023-01-05 11:17 UTC, DmitriiNazimov commented on packages/client/src/game/services/IndicatorManager/IndicatorManager.ts
> +    this.game.loop.registerTimerHandlers(elem);
Пока нет, но могли бы. Убрал, раз тебя смущает.

2023-01-05 11:19 UTC, DmitriiNazimov commented on packages/client/src/game/services/Scenario.ts
> +          this.indicatorManager.renderPlayerLives(Player.PLAYER2, 0);
Мне кажется это логичным - уничтожение базы означает мгновенную смерть для игроков и геймовер. Могу убрать если есть обоснование почему так не надо делать :)

2023-01-05 11:41 UTC, DmitriiNazimov commented on packages/client/src/game/services/IndicatorManager/IndicatorManager.ts
> +      text: lives.toString(),
> что делать, если жизней будет больше 9

Не делать больше 9 жизней. Это читерство какое-то :)

Отступ сделал 0,3 единицы.

2023-01-05 11:41 UTC, sapomaro commented on packages/client/src/game/services/Scenario.ts
> +          this.indicatorManager.renderPlayerLives(Player.PLAYER2, 0);
Мне кажется, это лишнее. Проигрыш и смерть - не одно и то же. В том же Cattle Bity не обнуляется при уничтожении базы.

2023-01-05 11:45 UTC, sapomaro commented on packages/client/src/game/ui/Overlay.ts
> +  renderSplashScreen(backgroundColor: 'black' | '#636363' = 'black') {
Просто black/grey ещё хоть как-то читалось, а тут непонятное кодовое значение, которое упоминается в разных классах. А так да, правильнее будет всё вынести тогда.

2023-01-05 11:50 UTC, sapomaro commented on packages/client/src/game/services/IndicatorManager/IndicatorManager.ts
> +      text: lives.toString(),
Ну или делать ИИ проворнее и хитрее при каждой подобранной жизни)

2023-01-05 12:07 UTC, DmitriiNazimov commented on packages/client/src/game/services/IndicatorManager/IndicatorManager.ts
> +      text: lives.toString(),
Сносно смотрится с уровнем больше 9. Можно так оставить. Если реально будет больше 9 жизней реализовано, то можно будет отступ поставить 0,2 а не 0,3.

2023-01-05 12:11 UTC, DmitriiNazimov commented
@sapomaro 
1. Внес указанные изменения в код.
2. После выноса всех цветов в константы упали тесты из-за того, что эта константа много где подключается и видимо образуются циклические зависимости. Проблема решается если не подключать константу с цветами в одном файле - Entity, поэтому там цвет указан строкой.
Также в некоторых местах используются цвета вида "color: `rgba(0,0,0,${opacity})`", это пришлось учитывать при типизировании.

2023-01-05 12:39 UTC, sapomaro approved these changes

2023-01-05 12:39 UTC, sapomaro commented on packages/client/src/game/services/Scenario.ts
> +    const entity = new TankEnemy({ role: 'enemy', color: Color.Pink } as EntityDynamicSettings);
Свойства `role` и `color` здесь лишние. Может, вообще их уберём?

2023-01-05 12:39 UTC, sapomaro commented on packages/client/src/game/entities/Entity.ts
> +  color = 'grey';
Тут цвет можно оставить любой. Он здесь нужен, если мы будем наследовать от этого класса какой-нибудь элемент и забудем подключить в нём спрайты (или они не прогрузятся). Тогда будет видно, что он отрисовался. А то у нас уже были ошибки с пустыми непроходимыми и непростреливаемыми квадратами.

2023-01-05 13:38 UTC, DmitriiNazimov commented on packages/client/src/game/services/Scenario.ts
> +    const entity = new TankEnemy({ role: 'enemy', color: Color.Pink } as EntityDynamicSettings);
Если вообще убрать аргументы, то начинает ругаться, что ждет аргументы. Если поставить пустой объект, то начинает ругаться что ему не хватает posX, posY. Если поставить {} as EntityDynamicSettings, то это кринж какой-то. 

Не придумал как тут элегантно решить вопрос.

2023-01-05 14:01 UTC, sdelfi approved these changes
Классно сделано. 
Пару небольших замечаний

2023-01-05 14:01 UTC, sdelfi commented on packages/client/src/game/data/constants.ts
> +export enum Color {
Отличная идея

2023-01-05 14:01 UTC, sdelfi commented on packages/client/src/game/services/IndicatorManager/IndicatorManager.ts
> +      let currentPosY = 2;
В константы может вывести? Пока выглядит как магические цифры

2023-01-05 14:01 UTC, sdelfi commented on packages/client/src/game/services/IndicatorManager/IndicatorManager.ts
> +      posX: level > 9 ? 57 : 58,
Для этого можно использовать padLeft,  посмотри как в level selector сделано.
К тому, что тут логичней на мой взгляд это решать не позиционированием.
Хотя пробел может не дать нужной позиции, нужно тестировать

2023-01-05 14:01 UTC, sdelfi commented on packages/client/src/game/typings/index.ts
> +  PLAYER1 = 'PLAYER1',
А именование здесь точно верное? Для enum вроде как решили PascalCase для ключей или что-то путаю?

2023-01-05 14:04 UTC, sapomaro commented on packages/client/src/game/typings/index.ts
> +  PLAYER1 = 'PLAYER1',
PascalCase у нас будет после глобального рефакторинга, который вынесен в отдельную задачу. А пока что делаем, как есть, чтобы не трогать кучу файлов.

2023-01-05 14:08 UTC, sapomaro commented on packages/client/src/game/services/Scenario.ts
> +    const entity = new TankEnemy({ role: 'enemy', color: Color.Pink } as EntityDynamicSettings);
В данном случае не помешает подкорректировать `TankEnemy`. Задача чисто косметическая, можно оставить на потом. @Gramoteev как раз будет вносить изменения в упомянутый класс скоро. Можешь TODO вставить пока что?

2023-01-05 14:15 UTC, DmitriiNazimov commented on packages/client/src/game/services/IndicatorManager/IndicatorManager.ts
> +      let currentPosY = 2;
Не совсем уловил идею. `currentPosY` вынести в константу? 
`const initialPosY = 2;
let currentPosY = initialPosY;`
Типа так? Не очень вижу в этом смысл. 

Магические числа - когда непонятно что это за число и почему оно такое. В данном случае понятно что это координаты где нужно отрисовать элемент и они такие потому что элемент нужно разместить именно здесь.

У нас во всем проекте координаты задаются просто цифрами и до сих пор это всех устраивало :)

2023-01-05 16:15 UTC, DmitriiNazimov commented on packages/client/src/game/services/Scenario.ts
> +    const entity = new TankEnemy({ role: 'enemy', color: Color.Pink } as EntityDynamicSettings);
Добавил TODO.

2023-01-07 11:09 UTC, Olegas requested changes

2023-01-07 11:09 UTC, Olegas commented on packages/client/src/game/entities/Entity.ts
> +  // В этом файле нельзя подключать Color из Constants т.к. образуются циклические зависимости и тесты падают.
А может не собирать все константы в одном файле а разбить на несколько? Цвета вынести в отдельный файл?

2023-01-07 11:09 UTC, Olegas commented on packages/client/src/game/entities/TankEnemy.ts
> +    const actions = [...new Array(1).fill('turn'), ...new Array(5).fill('move')];
Почему просто не написать 'fill'? Зачем тут создавать массив и его потом разбирать ради одного элемента?

2023-01-07 11:09 UTC, Olegas commented on packages/client/src/game/services/IndicatorManager/IndicatorManager.ts
> +    const canvasLayerItem = [...this.game.view.layers[this.layerName].entities].reverse().find(item => {
А для чего reverse? Ведь тут ищется всего лишь один элемент. Какая разница какой будет порядок?

2023-01-07 11:09 UTC, Olegas commented on packages/client/src/game/services/View.ts
> +    const windowSmallerSideSize = window.innerWidth < window.innerHeight ? window.innerWidth : window.innerHeight;
Math.min?

2023-01-07 11:09 UTC, Olegas commented on packages/client/src/game/services/View.ts
> +    });
А не надо ли где-то отписаться от события?

2023-01-07 12:02 UTC, sapomaro commented on packages/client/src/game/entities/TankEnemy.ts
> +    const actions = [...new Array(1).fill('turn'), ...new Array(5).fill('move')];
Тут логика в том, что значение внутри Array с `turn` может меняться со временем. Если мы захотим, чтобы вражеские танки поворачивали чаще, то можем там указать, к примеру, 2 или 3.

2023-01-07 12:09 UTC, sapomaro commented on packages/client/src/game/services/View.ts
> +    });
Думаю, стоит создать в классе `View` метод `unload` с отпиской от события и включить его вызов в соответствующее место в `Game`. У нас по этой логике строится загрузка/выгрузка всех сервисных классов.

2023-01-07 12:10 UTC, DmitriiNazimov commented on packages/client/src/game/entities/TankEnemy.ts
> +    const actions = [...new Array(1).fill('turn'), ...new Array(5).fill('move')];
Как вариант можно так записать: `const actions = new Array(6).fill('turn', 0,1).fill('move', 1)`, будет более лаконично.
Но я пока не стал ничего менять. Нужны более четкие разъяснения.

2023-01-07 12:10 UTC, DmitriiNazimov commented on packages/client/src/game/entities/Entity.ts
> +  // В этом файле нельзя подключать Color из Constants т.к. образуются циклические зависимости и тесты падают.
Это решило проблему. Спасибо!

2023-01-07 12:11 UTC, DmitriiNazimov commented on packages/client/src/game/services/IndicatorManager/IndicatorManager.ts
> +    const canvasLayerItem = [...this.game.view.layers[this.layerName].entities].reverse().find(item => {
Технически будет работать и без reverse(), но визуально красивее когда удаляется последняя иконка танка, а не первая. В оригинале удалялась последняя иконка.

2023-01-07 12:46 UTC, Olegas requested changes

2023-01-07 12:46 UTC, Olegas commented on packages/client/src/game/services/View.ts
> +    document.removeEventListener('resize', this.canvasResizeListener);
Вы подписали одну функцию (результат bind) а отписываете совсем другую (оригинал). Так не будет работать (отписка не произойдет)

2023-01-07 12:46 UTC, Olegas commented on packages/client/src/game/services/IndicatorManager/IndicatorManager.ts
> +    const canvasLayerItem = [...this.game.view.layers[this.layerName].entities].reverse().find(item => {
Тогда может findLast?

2023-01-07 16:59 UTC, DmitriiNazimov commented
Внес исправления.

2023-01-07 17:00 UTC, Olegas approved these changes

2023-01-07 17:01 UTC, merged