Add Web API section to the readme
FrontHeads/tanchiki pull request #64
Opened 2023-01-09 18:51 UTC by sdelfi

2023-01-09 19:15 UTC, andreyatx approved these changes

2023-01-09 19:15 UTC, andreyatx commented on README.md
> +- `Full Screen API` - разворачивания игры на полный экран
```suggestion
- `Fullscreen API` - разворачивание игры на полный экран
```

2023-01-09 19:34 UTC, DmitriiNazimov requested changes

2023-01-09 19:34 UTC, DmitriiNazimov commented on README.md
> +- `Service workers` - работа приложения в offline
1. Мне кажется здесь нужно единственное число - worker, а не workers. https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API

2. Не хватает точки в конце описания каждого API.

2023-01-09 20:05 UTC, sdelfi commented on README.md
> +- `Service workers` - работа приложения в offline
1. https://w3c.github.io/ServiceWorker/ тут где-то во множественном числе, где-то в кдинственном. Поменял на единственное
2. Добавил.
3. Обновил, но тогда получается, что в разделе "Реализованный функционал" тоже нужно точки ставить.

2023-01-09 20:07 UTC, DmitriiNazimov commented on README.md
> +- `Service workers` - работа приложения в offline
Можно еще добавить https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API

Да, в реализованный функционал тоже бы точки пригодились.

2023-01-09 20:13 UTC, DmitriiNazimov approved these changes

2023-01-10 12:12 UTC, Olegas approved these changes

2023-01-10 12:20 UTC, merged