Refactor enums, add consistent type imports
FrontHeads/tanchiki pull request #65
Opened 2023-01-12 16:22 UTC by andreyatx

Рефактор enum, по выбранному стилю.
Явный импорт типов.

2023-01-12 22:05 UTC, DmitriiNazimov commented on packages/client/src/game/typings/index.ts
> +export enum Direction { //zone
Тут и в некоторых местах остались комментарии. Например `//view`

2023-01-12 22:05 UTC, DmitriiNazimov commented on packages/client/src/utils/HTTP/HTTP.tsx
> +  Get = 'GET',
Тут наверное не стоило переводить в PascalCase, а стоило оставить UpperCase, потому что методы HTTP запросов всегда пишутся заглавными буквами. 
https://developer.mozilla.org/ru/docs/Web/HTTP/Methods/GET

2023-01-13 08:02 UTC, andreyatx commented on packages/client/src/game/typings/index.ts
> +export enum Direction { //zone
Это комментарии мне на следующий таск, чтобы я не забыл куда что ложить

2023-01-14 08:05 UTC, sdelfi approved these changes

2023-01-14 09:16 UTC, sapomaro requested changes
Это непростой, но важный рефакторинг. Автозамена кое-где затронула лишнее - отписал в комментах.

2023-01-14 09:16 UTC, sapomaro commented on packages/client/src/game/data/constants.ts
> +  //screens
Несмотря на то, что мы это обсуждали на последнем синке, такие комментарии следует расписывать поподробнее, а то суть может потом забыться, когда дело дойдёт до выполнения соответствующей задачи. Лучше ставить пометку TODO, чтобы можно было потом легко найти похожие фрагменты, а сам комментарий - поместить перед строкой `export const screenClasses`.

```suggestion
  //TODO: переместить эту переменную в папку screens
  export const screenClasses = {
```

2023-01-14 09:16 UTC, sapomaro commented on packages/client/src/game/data/spriteCoordinates.ts
> +  'terrain.Concrete': {
В этом файле автозамена сработала неудачно. Надо привести всё обратно к единому виду.

2023-01-14 09:16 UTC, sapomaro commented on packages/client/src/game/entities/Tank.test.ts
> +    const Ice = new Terrain({ type: 'Ice', posX: 0, posY: 1, width: 9, height: 9 });
Переменные с заглавной для инстансов классов - это не айс. Другие замены - тоже надо вернуть обратно.

2023-01-14 09:16 UTC, sapomaro commented on packages/client/src/game/services/Game.ts
> +      this.statistics.startSession(this.mainMenuState === MainMenuState.Singleplayer ? 'Singleplayer' : 'Multiplayer');
Мы же, вроде, договорились оставлять значения капсом ('SINGLEPLAYER', 'MULTIPLAYER' )?

2023-01-14 09:16 UTC, sapomaro commented on packages/client/src/game/services/Resources/data.ts
> +  hitBrick = '/assets/sounds/hit-Brick.mp3',
Винда такое скушает, т.к. там пути case-insensitive, а вот в Линуксах из-за такого могут возникнуть проблемы.

2023-01-14 09:16 UTC, sapomaro commented on packages/client/src/game/typings/index.ts
>  export type ExplosionVariant = 'TANK_EXPLOSION' | 'PROJECTILE_EXPLOSION';
А такие вещи в enum не будем переделывать? Вроде как, в текущей задаче это предусматривалось. Если нет, то строковые значения надо сделать обратно заглавными для консистентности.

2023-01-15 20:13 UTC, DmitriiNazimov approved these changes
Если набрать команду `yarn lint --stream`, то там выдает 5 warnings. Они, кажется не связаны с этим PR, но раз уж тут 130 файлов задействовано, то можно заодно и warnings поправить.
Там где warnings с any - сложно будет исправить и наверное смысла нет, а вот два других исправить будет очень просто и думаю стоит это сделать.

2023-01-16 09:15 UTC, sapomaro approved these changes
Всё супер.

2023-01-16 09:15 UTC, sapomaro commented on packages/client/src/game/typings/index.ts
> +export type PlayerVariant = 'PLAYER1' | 'PLAYER2'; //playertank
В некоторых местах остались такие вот комменты, суть которых стороннему читающему может быть неясна.

2023-01-16 11:04 UTC, Olegas approved these changes
Я посмотрел на идею в описании - это супер! Честно - все 10к строк изменений не смотрел )

2023-01-16 12:06 UTC, sapomaro commented
Я слил ветку с лидербордом и появились конфликты. Я могу сегодня вечерком сделать коммит, чтобы их исправить.

2023-01-16 12:49 UTC, sapomaro commented
> Я слил ветку с лидербордом и появились конфликты. Я могу сегодня вечерком сделать коммит, чтобы их исправить.

Подправил. Там должна была остаться мелочёвка из серии добавления слова `type` в импортах.

2023-01-16 17:07 UTC, merged