Show menu items based on user auth status
FrontHeads/tanchiki pull request #79
Opened 2023-01-25 09:36 UTC by sdelfi

2023-01-25 19:41 UTC, sapomaro approved these changes

2023-01-25 19:41 UTC, sapomaro commented on packages/client/src/utils/navigationUtils.ts
> +};
А может, перенести эту функцию в components/Navigation?

2023-01-25 20:03 UTC, sdelfi commented on packages/client/src/utils/navigationUtils.ts
> +};
@sapomaro У меня была такая мысль, но эта функция используется в двух тестах за пределами Navigation, поэтому подумал, что пусть будет в утилитах. Собственно, как упали тесты - было решено вынести её в утилиту. 

Можно обсудить еще, в принципе

2023-01-26 04:26 UTC, sapomaro commented on packages/client/src/utils/navigationUtils.ts
> +};
> @sapomaro У меня была такая мысль, но эта функция используется в двух тестах за пределами Navigation, поэтому подумал, что пусть будет в утилитах. Собственно, как упали тесты - было решено вынести её в утилиту.
> 
> Можно обсудить еще, в принципе



> @sapomaro У меня была такая мысль, но эта функция используется в двух тестах за пределами Navigation, поэтому подумал, что пусть будет в утилитах. Собственно, как упали тесты - было решено вынести её в утилиту.
> 
> Можно обсудить еще, в принципе

Те тесты тоже связаны с навигацией. Но я не настаиваю.

2023-01-26 07:14 UTC, sdelfi commented on packages/client/src/utils/navigationUtils.ts
> +};
Согласен, что связаны, но сами тексты, например, в Home.test.tsx, т.е.   компонент будет идти за функцией в соседний компонент, что на мой взгляд не очень хорошо. 
С другой стороны, ради одной функции выносить это в отдельный файл - тоже сомнительное решение.

2023-01-26 09:59 UTC, sapomaro commented on packages/client/src/utils/navigationUtils.ts
> +};
На мой взгляд, вынести в отдельный файл - хорошо, но вопрос в том, где он должен лежать.

2023-01-27 07:10 UTC, Olegas requested changes

2023-01-27 07:10 UTC, Olegas commented on packages/client/src/components/MenuLink/typings.ts
> +  public?: boolean;
А если не тот и не другой это какой? Т.е. вы тут закодировали 4 состояния но по факту кажется только два: либо protected либо public.

2023-01-27 07:46 UTC, sdelfi commented on packages/client/src/components/MenuLink/typings.ts
> +  public?: boolean;
3 состояния - доступно всем, доступно только авторизованным, не доступно авторизованному (страница регистрации, логина)

2023-01-27 11:43 UTC, sdelfi commented on packages/client/src/components/MenuLink/typings.ts
> +  public?: boolean;
В целом, согласен, не очевидные параметры. Поменял структуру, залил

2023-01-27 15:22 UTC, Olegas approved these changes
👍

2023-01-27 15:31 UTC, andreyatx approved these changes
У меня замечаний нет

2023-01-27 16:16 UTC, merged