Add themization
FrontHeads/tanchiki pull request #83
Opened 2023-01-29 00:41 UTC by DmitriiNazimov

1. Добавил светлую тему.
2. Добавил возможность смены темы. Выбранная тема запоминается в localStorage, а если пользователь залогинен, то еще и в базу данных. Если в localStorage есть запись о выбранной теме, то к базе данных не обращаемся. За счет этого пользователь может иметь на разных устройствах разную тему. А если он зайдет с нового устройства/браузера (где пустой localStorage), то у него подтянется тема записанная в БД. 
3. Закрыл ручки для управления выбором темы за авторизацией. 
4. Мелкие правки по верстке.

2023-01-29 15:11 UTC, sdelfi approved these changes
Пару мыслей написал, но они либо незначительные, либо для более глобального размышления

2023-01-29 15:11 UTC, sdelfi commented on packages/client/index.html
> +<html lang="ru" theme="DARK">
Может лучше data-theme? 
На сколько помню, HTML5 более лоялен к кастомным атрибутам, но вроде это не касается штатных. А все допы пишутся через data-* атрибуты

2023-01-29 15:11 UTC, sdelfi commented on packages/server/api/services/Themization.ts
> +    if (authUserId !== userId) {
Здесь супер, теперь не взломают.

Только у меня typeof authUserId - number, а typeof userId  - string.

Я бы поменял на что-то вроде

```suggestion
    if (+authUserId !== +userId) {
```

2023-01-29 15:11 UTC, sdelfi commented on packages/server/middlewares/checkAuth.ts
> +export const checkAuthMiddleware: RequestHandler = async (req, res, next) => {
Отлично.

У меня есть еще идея разделить их на 2 middleware - getUserMiddleWare, вынести туда получение данных юзера.

Если эксперимент мой пройдет успешно, то опишу почему я вижу это разделение более правильным.

Как минимум, если мы в цепочке .use случайно поставили в двух местах checkAuthMiddleware, то в текущем виде это будет два запроса на получение пользователя, а если разделить получение и проверку и цепочка будет, скажем getUserMiddleWare -> checkAuthMiddleware -> checkAuthMiddleware, то будет лишь один запрос.

Также getUserMiddleWare нужен без checkAuthMiddleware  для SSR (это и тестирую, но там не все так однозначно, как обычно :) )

2023-01-29 15:46 UTC, sapomaro approved these changes
Всё супер.

2023-01-29 15:46 UTC, sapomaro commented on packages/client/src/components/BurgerMenu/BurgerMenu.tsx
> +        <ThemeToggle />
Можно второй такой тумблер поместить в настройки профиля.

2023-01-29 15:46 UTC, sapomaro commented on packages/client/src/components/ThemeToggle/ThemeToggle.tsx
> +    </div>
Для повышения юзабилити я бы сюда ещё добавил всплывающую подсказку (title=""), что это переключатель темы - для тех, кто не догадался и боится нажимать, чтоб не поломалось.

2023-01-29 15:46 UTC, sapomaro commented on packages/client/src/variables.css
> +  --burger-menu-lines-border: var(--background-color);
Может, в название переменных добавить `-color` по аналогии с другими?

2023-01-29 15:46 UTC, sapomaro commented on packages/server/config/constants.ts
> +export const allowedHosts = ['localhost', '127.0.0.1'];
👍

2023-01-29 16:35 UTC, Olegas requested changes

2023-01-29 16:35 UTC, Olegas commented on packages/client/src/components/ThemeToggle/ThemeToggle.tsx
> +        const response = await themizationAPI.getUserTheme(userId);
Может сразу с API-слоя вернуть строку с названием темы?

2023-01-29 16:35 UTC, Olegas commented on packages/client/src/components/ThemeToggle/ThemeToggle.tsx
> +        const response = await themizationAPI.getUserTheme(userId);
Кстати, а зачем аргумент userId? То есть API позволяет доставать тему любого пользователя? Почему просто не узнать кто просит тему и ему ответить?

2023-01-29 16:35 UTC, Olegas commented on packages/server/api/services/Themization.ts
> +    const { themeName, userId } = req.body;
Зачем передавать ид пользователя? Просто ставьте текущему и все

2023-01-29 16:35 UTC, Olegas commented on packages/server/models/Themes.ts
> +}
Для чего тут везде ! после полей?

2023-01-29 16:35 UTC, Olegas commented on packages/server/models/UserThemes.ts
> +  deleted_at!: Date;
Просто интересно - зачем вам эти три поля: created_at, updated_at, deleted_at. И самое интересное - как может быть что поле deleted_at заполнено у записи в БД?

2023-01-29 17:09 UTC, sdelfi commented on packages/server/middlewares/checkAuth.ts
> +export const checkAuthMiddleware: RequestHandler = async (req, res, next) => {
По этой части пока отбой. Для моего PR это не нужно будет. А разделять ради разделения на данном этапе не нужно.

2023-01-29 18:58 UTC, DmitriiNazimov commented on packages/server/models/Themes.ts
> +}
Без восклицательного знака TS выдает ошибку "Property 'theme_id' has no initializer and is not definitely assigned in the constructor.ts(2564)".

Можно делать запись такой: `theme_id: number | undefined;`, тогда не ругается. 

Или можно внести изменения в tsconfig вот такие:
`"compilerOptions": {
	// ...
    "strictPropertyInitialization": false,
   	// ...
}`

Не знаю какой вариант лучше, выбрал тот, который лаконичнее и локальнее.

2023-01-29 19:00 UTC, DmitriiNazimov commented on packages/server/models/UserThemes.ts
> +  deleted_at!: Date;
В рамках задачи по темизации при текущей реализации эти поля не нужны. Но такие поля будут использоваться в задаче по форуму и там они необходимы. Сюда эти поля добавил для консистентности, чтобы модели были похожими. Если это лишнее - могу убрать.

2023-01-29 19:44 UTC, DmitriiNazimov commented on packages/client/src/components/BurgerMenu/BurgerMenu.tsx
> +        <ThemeToggle />
Это лишнее, мне кажется. Чтобы попасть на страницу профиля в любом случае нужно открыть меню и увидеть тумблер. Остальные замечания реализовал.

2023-01-29 20:15 UTC, DmitriiNazimov commented on packages/client/src/components/ThemeToggle/ThemeToggle.tsx
> +        const response = await themizationAPI.getUserTheme(userId);
API слоя теперь возвращает строку. UserId больше не передаю.

2023-01-29 20:17 UTC, DmitriiNazimov commented
@Olegas все замечания реализованы.

2023-01-30 05:35 UTC, Olegas approved these changes

2023-01-30 05:55 UTC, merged