SSR user authentication
FrontHeads/tanchiki pull request #85
Opened 2023-01-29 18:22 UTC by sdelfi

add SSR store state preloading
update leaderboard structure (preload leaderboard data) update leaderboard tests

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-01-29 19:15 UTC, Olegas requested changes

2023-01-29 19:15 UTC, Olegas commented on packages/client/ssr.tsx
> +  }
Опасно. Представь что тебе одновременно пришло два запроса на рендер страницы от разных пользователей. И вот у тебя уже для первого пользователя полетели данные от второго

2023-01-29 19:15 UTC, Olegas commented on packages/client/ssr.tsx
>    const context = await query(remixRequest);
А что это за магия? Расскажи плз? Тут какие-то части от фреймворка Remix?

2023-01-29 19:18 UTC, sdelfi commented on packages/client/ssr.tsx
>    const context = await query(remixRequest);
Это взял с примеров React router, чтобы завелся createStaticRouter,  без которого не работал корректно SSR, поэтому, увы, не подскажу что за магия, сам не до конца разобрался, а в документации у них этого ещё не написано, т.к. createStaticRouter только недавно внедрили.

2023-01-29 19:23 UTC, sdelfi commented on packages/client/ssr.tsx
> +  }
А как быть?
Как я понимаю, этот код выполнится для конкретного запроса. Разве нет?

Мне нужно для запросов на сервере, которые делаются в пакете client отправлялись авторизационные куки, как это происходит от клиента.

В данном случае render из ssr.ts вызывается сервером в момент запроса от пользователя. Т.е. берутся куки из запроса пользователя, что пришли на сервер и пробрасываются в клиентскую часть, где делаются запросы в режиме реального времени именно для этого запроса.
Т.е. запрос от другого пользователя пойдет по такой же цепочке и запросы будут именно с его куками идти.
Это как я понял принцип работы.

2023-01-29 19:25 UTC, sdelfi commented on packages/client/ssr.tsx
>    const context = await query(remixRequest);
https://github.com/remix-run/react-router/blob/main/examples/ssr-data-router/src/entry.server.tsx

2023-01-29 19:35 UTC, Olegas commented on packages/client/ssr.tsx
> +  }
> Как я понимаю, этот код выполнится для конкретного запроса. Разве нет?

Этот код - для конкретного. Но вот axios ты правишь глобальный.

Что можно попробовать.
1. Используя axios.create создать экземпляр axios с конкретными настройками
2. Обернуть приложение контекстом, в который положить этот экземпляр
3. В точках, где нужен axios, брать не глобальный, а вот этот вот из контекста. 

Кажется это можно сделать. Ведь загрузка у тебя в loader'ах а их ты передаешь в параметры роута уже внутри приложения. Можно в этой точке добраться до axios из контекста и на основе него сделать loader

Как-то так
```  
 const leaderboardLoader = useLeaderboardLoader()

 function useLeaderboardLoader() {
       const localAxios = useLocalAxios(); // тут достаем его из контекста
       return useMemo(() => {
           return function loader() { 
              // load smth with localAxios
           }
       }, [localAxios]);
}
```

2023-01-29 19:35 UTC, Olegas commented on packages/client/ssr.tsx
> +  }
https://axios-http.com/docs/instance

2023-01-29 19:41 UTC, sdelfi commented on packages/client/ssr.tsx
> +  }
Спасибо за пояснение, попробую разобраться.
Пока все ещё не понимаю, как куки одного пользователя попадет в запрос другому, ведь глобальные настройки axios устанавливаются в рамках текущего запроса. Завтра на свежую голову ещё посмотрю.
Но тема интересная

2023-01-29 19:44 UTC, Olegas commented on packages/client/ssr.tsx
> +  }
> ведь глобальные настройки axios устанавливаются в рамках текущего запроса

Вот здесь ошибка. Это не верное утверждение.

Смотри, node выполняет все запросы в рамках одного процесса. Ты можешь это проверить сделав глобальную переменную и меняя ее на каждый запрос и возвращая пользователю. 

когда ты пишешь `import axios from 'axios'` ты создаешь глобальную переменную. Когда мы меняешь axios.defaults ты меняешь их все так же в рамках глобальной переменной.

2023-01-29 19:55 UTC, sdelfi commented on packages/client/ssr.tsx
> +  }
Теперь понятно, интересно.

2023-01-30 16:48 UTC, sdelfi commented on packages/client/ssr.tsx
> +  }
@Olegas спасибо за разъяснение. Провел эксперимент и проблема воспроизвелась, просто открыв в двух браузерах сайт. 
Очень полезное замечание и "тонкость", которая могла бы привести к серьезным проблемам. 

Я залил исправления. Я не стал использовать контекст. У нас есть httpClient файл, где был настроен interceptor для изменения формата ответа ошибок от Яндекс API. А далее мы импортировали axios из этого файла.

Там же сделал инстанс axios и сделал проброс авторизационных cookie в defaults этого инстанса. Проверил - все работает корректно. 
У нас импорт идет только один раз и в данном случае создается только один инстанс, даже при повторном импорте, это дополнительно проверил.

2023-01-30 17:42 UTC, sdelfi commented on packages/client/ssr.tsx
> +  }
Плюс если использовать контекст, то у меня получается проблема с очередностью.

Мне нужно ставить заголовки вначале render. Если я делал это ниже по коду, например, то не работало. Полагаю, в этой магии, что здесь - что-то происходит и уже после этого httpClient.defaults.header не задать. Вернее, задать можно, но в запросы не попадают дефолтные заголовки:
![image](https://user-images.githubusercontent.com/1927032/215546294-60c2b3b0-dfe4-4b67-ad11-a3626914617c.png)

А контекст провайдер оборачивает уже ниже приложение. В том числе
![image](https://user-images.githubusercontent.com/1927032/215545775-f4e01715-eea3-43ed-ac30-847ea09ad17c.png)


В целом, это решаемо.

Но дальше есть 2 момента: 
В rootLoader нельзя использовать хуки, в т.ч. и контекст, т.е. туда не получить инстанс клиента. 
Также у нас есть обертка HTTP.ts, внутри которой тоже импортируется клиент. Так вот там useContext, логично, тоже не заиспользовать.

Т.е. либо у нас архитектурно как-то неверно сделано и переделывать много кода (при этом не ясно как в loader прокинуть инстанс клиента, либо использовать сделанный мною вариант (если, конечно, в нем нет каких-то критичных моментов, которые мне неизвестны)

2023-01-31 15:28 UTC, Olegas commented on packages/client/ssr.tsx
> +  }
> Там же сделал инстанс axios и сделал проброс авторизационных cookie в defaults этого инстанса. Проверил - все работает корректно.

А чем это отличается от того что было? Был один глобальный инстанс, стал другой такой же глобальный, пусть и со своими интерцепторами

2023-01-31 15:39 UTC, sdelfi commented on packages/client/ssr.tsx
> +  }
В таком виде авторизационные куки не делились между разными клиентами. 
Тогда не понимаю как можно еще реализовать, если есть в текущей реализации проблемы.
Описал выше о проблемах реализации через контекст, где доступ к инстансу внутри контекста из route loader не получить, т.к. там нельзя использовать хуки

2023-01-31 16:52 UTC, Olegas commented
> Т.е. данные подгрузились корректно, но React почему-то не поставил на место таблицу с данными.

Это "последствия" того, что используется Suspense и renderToPipeableStream
Штука в том что React доставляет приложение кусками. Если приглядеться то видно что рядом идет скрипт, который один кусок заменяет на другой. Мы просто как будто сразу видим результат, по факту он прилетает к нам частями.

Что бы все прилетело разом, надо использовать onAllReady вместо onShellReady. Если поменять в текущей реализации, можно будет увидеть как в результирующем HTML пришла сразу таблица лидерборда например. Правда, без данных. Данные будут только в initialState

2023-01-31 16:54 UTC, sdelfi commented
Спасибо, с onAllReady и onShellReady поэкспериментирую.

2023-01-31 17:23 UTC, Olegas commented on packages/client/ssr.tsx
>    const context = await query(remixRequest);
Кстати, я вижу что вы создаете context и передаете его в роутер.
А вот что я вижу в тайпингах аргументов, которые приходят в loader

```
interface DataFunctionArgs {
  request: Request;
  params: Params;
  context?: any;
}
```

А нет ли там вашего исходного запроса с нужными хэдерами или этого самого контекста? Кажется это тот самый вариант добросить кукисы до точки вызова загрузки данных

2023-01-31 20:59 UTC, sdelfi commented
> Что бы все прилетело разом, надо использовать onAllReady вместо onShellReady. Если поменять в текущей реализации, можно будет увидеть как в результирующем HTML пришла сразу таблица лидерборда например. Правда, без данных. Данные будут только в initialState

@Olegas да, так и есть, как и написали. Но теперь вылезает ошибка hydration. 
Не совсем тогда понятно - почему не происходит рендер данных в таком случае?

2023-02-01 05:54 UTC, Olegas commented
> > Что бы все прилетело разом, надо использовать onAllReady вместо onShellReady. Если поменять в текущей реализации, можно будет увидеть как в результирующем HTML пришла сразу таблица лидерборда например. Правда, без данных. Данные будут только в initialState
> 
> @Olegas да, так и есть, как и написали. Но теперь вылезает ошибка hydration. Не совсем тогда понятно - почему не происходит рендер данных в таком случае?

Я думаю тут проблема в том, что получилось замешано два фреймворка react-router и redux каждый из которых хочет сам управлять жизненным циклом отрисовки. Хоть в доке к react-router и сказано что они не ограничивают как грузить данные, но по факту получается что они не могут дождаться корректно загрузки

Но тут пока только мое ИМХО. Я вчера пару часов сидел с вашим проектом, пытался его по нормальному запустить - ничего лучше не вышло (

2023-02-01 13:00 UTC, sdelfi commented
Спасибо за попытку разобраться. С leaderboard, полагаю, пока можно пренебречь.
А вот с Axios еще провожу эксперименты.

2023-02-01 18:29 UTC, Olegas commented
> Спасибо за попытку разобраться. С leaderboard, полагаю, пока можно пренебречь. А вот с Axios еще провожу эксперименты.

"по нормальному" я не имел ввиду что плохо сделано, имел ввиду что хотелось сделать что бы все дожидалось и грузилось. Вообще у вас там титанический труд конечно, вы молодцы )

2023-02-01 18:53 UTC, DmitriiNazimov approved these changes

2023-02-04 20:07 UTC, sdelfi commented on packages/client/ssr.tsx
>    const context = await query(remixRequest);
@Olegas 

В request действительно есть исходные куки. Спасибо за наводку.

Тогда возникает другой вопрос. 

У нас часть запросов есть в лоадере, часть вне его.
Т.е. получается, что в лоадере мы во все запросы прокидываем из request.header.cookie авторизационную куку. 
А в остальное через контекст? 

Вариант 
authAPI.me(cookie) мне не нравится, т.к. делать для каждого api запроса параметр cookie, затем его пробрасывать так
![image](https://user-images.githubusercontent.com/1927032/216781591-7bb4e1cc-50f4-4956-a907-4e8e6cbf8e10.png)

Где дальше идет проброс запроса через HTTP._send -> httpClient - это выглядит костыльно как-то.

Была еще мысль сделать базовый класс BaseApi и в нем делать addCookie метод, от него ветвить AuthApi и другие, чтобы не дублировать код.
Но все равно получается, что в каждом методе AuthApi и других учесть наличие static cookie параметра, добавленного через addCookie - тоже выглядит как-то неправильно.

При этом, классы статичные, т.к. в контекст их инстансы не сохранить, т.к. нужен доступ из loader и тут встает вопрос - если статичный класс, мы в него добавили авторизационную куку - не будет ли такой же проблемы, как и с дефолтными настройками axios, где кука шарится между разными запросами?

..................

В общем, ряд экспериментов показал, что проблема осталась после последних правок, Вы правы.

Решил взглянуть на проблему иначе, отойдя от старых попыток.
Попробовал еще сделать класс с HTTP клиентом (где инициализируется инстанс axios) с использованием singleton, но тоже не работает.
Заметил, что первая инициализация - создание инстанса идет при запуске сервера, а дальше уже берется этот же инстанс. Откатывать не стал, хоть и не решило проблему.

В общем, проблему решил несколько проще. Я делал проверку, что если кука с запроса есть, то пишем в дефолт её. Убрал проверку. Т.е. теперь пишем в дефолт всегда, даже если в запросе куки пустые. Т.е. можно сказать, что мы в дефолт ставим всегда именну ту куку, которая прилитела в этом запросе. Проверил - все работает.

По факту. со стороны сервера, это единственная точка входа, где после используется axios, т.е. в других местах эта дефолтная кука не всплывает, а тут всегда записываются актуальные куки текущего запроса.

2023-02-05 05:29 UTC, sapomaro approved these changes
Потестил, с авторизацией работает. Лидерборд приходит с сервера со всеми данными в __PRELOADED_STATE__. Станислава не останавливают никакие трудности)

2023-02-05 05:29 UTC, sapomaro commented on packages/client/src/config/leaderboardRoute.tsx
> +};
У нас такой же метод есть в `leaderboardThunks`. Насколько я понял, подружить `Redux` и `React Router` не получилось, поэтому нужно дублирование?

2023-02-05 05:29 UTC, sapomaro commented on packages/client/src/utils/HTTP/httpClient.ts
> +}
Столкнулся с такой вещью, которая к SSR отношения не имеет. Если заходить с клиентской сборки (порт 3000), то кидает следующую ошибку в консоли (темизация реализована только у нас на сервере, который не запущен):

```
XHRGEThttps://ya-praktikum.tech/api/v2/themization
[HTTP/2 404 Not Found 15ms]

Uncaught (in promise) Error: Not found
    initInterceptors http://localhost:3000/assets/js/app-a67191d2.js:100
    promise callback*request http://localhost:3000/assets/js/app-a67191d2.js:100
    em http://localhost:3000/assets/js/app-a67191d2.js:98
    _send http://localhost:3000/assets/js/app-a67191d2.js:100
    get http://localhost:3000/assets/js/app-a67191d2.js:100
    getUserTheme http://localhost:3000/assets/js/app-a67191d2.js:104
    rC http://localhost:3000/assets/js/app-a67191d2.js:104
    rC http://localhost:3000/assets/js/app-a67191d2.js:104
    ml http://localhost:3000/assets/js/app-a67191d2.js:32
    Kr http://localhost:3000/assets/js/app-a67191d2.js:32
    Kd http://localhost:3000/assets/js/app-a67191d2.js:32
    qn http://localhost:3000/assets/js/app-a67191d2.js:30
    py http://localhost:3000/assets/js/app-a67191d2.js:32
    er http://localhost:3000/assets/js/app-a67191d2.js:32
    nh http://localhost:3000/assets/js/app-a67191d2.js:32
    _ http://localhost:3000/assets/js/app-a67191d2.js:17
    ge http://localhost:3000/assets/js/app-a67191d2.js:17
    EventHandlerNonNull* http://localhost:3000/assets/js/app-a67191d2.js:17
    <anonymous> http://localhost:3000/assets/js/app-a67191d2.js:17
app-a67191d2.js:100:14058
```

Получается, что ошибки при неполучении данных через API на клиенте никак не обрабатываются. Предлагаю рассмотреть этот момент отдельно - вне текущей задачи.

2023-02-05 07:45 UTC, sdelfi commented on packages/client/src/config/leaderboardRoute.tsx
> +};
Верно, redux и thunks не доступны в лоадере

2023-02-05 07:46 UTC, sdelfi commented on packages/client/src/utils/HTTP/httpClient.ts
> +}
Явно не хватает обработчика ошибок при запросе темы. Возможно, то связано с интерсептором, который ловит и конвертирует ошибки от яндекс api

2023-02-05 08:58 UTC, Olegas commented
Я увидел новые комиты и комментарии. Ушел думать как помочь...

2023-02-08 19:41 UTC, Olegas commented on packages/client/ssr.tsx
>    const context = await query(remixRequest);
Я придумал. Вам не нужен HTTPClient, getInstance и т.п.
Общая идея - добавить на стороне сервера в глобальный (да) axios новый интерцептор, который будет перед запросом добавлять куки.
Где он их будет брать? 
В Node есть возможность сделать "переменную", которая будет локальной по отношению к текущей цепочке асинхронных процессов (называется TLS, Thread Local Storage)
В вашем случае такая цепочка будет = запросу и всем идущим далее асинхронным процессам.
Т.е. на старте запроса вы создаете такое хранилиже, складываете в него кукисы и идете дальше. Axios внутри интерцентора (который объявлен только на сервере и просто отсутствует на клиенте) достает их этого хранилища данные о кукисах и подставляет в запрос.
Материалы по теме:
- https://nodejs.org/dist/latest-v18.x/docs/api/async_context.html#class-asynclocalstorage
- https://pjatk.in/tls-in-node.html

2023-02-08 19:49 UTC, sdelfi commented on packages/client/ssr.tsx
>    const context = await query(remixRequest);
Звучит интересно, ни разу не слышал. 
Спасибо, буду пробовать такой вариант. Получается, что клиент вообще ничего не будет знать о куки, получается, об этом позаботится сервер, как я понял.

2023-02-08 20:03 UTC, Olegas commented on packages/client/ssr.tsx
>    const context = await query(remixRequest);
Да, именно! Прелесть этого решения что оно полностью локализовано на сервере и не потребует правок в клиентской части вообще.

Я вчера пол проекта вашего нарефакторил с целью проброса кукисов до транспорта, и тут до меня дошло как вообще на изи все сделать )

2023-02-08 20:08 UTC, sdelfi commented on packages/client/ssr.tsx
>    const context = await query(remixRequest);
Отлично, спасибо еще раз за вовлеченность :)

Главное, чтобы Thread Local Storage хранил именно для цепочки запросов клиента. Смущает, что в названии Thread, ведь один thread обрабатывает как раз запросы от разных клиентов и шарит между ними данные. 
Но для начала изучу матчасть и попробую реализовать, выводы напишу после.

2023-02-09 14:36 UTC, Olegas commented on packages/client/ssr.tsx
>    const context = await query(remixRequest);
Да, ты абсолютно прав, Thread тут немного смущает. Но по факту все работает ) Thread Local это "калька" аналогичного поняти из других стэков, но суть в том что позволяет держать переменные в рамках обработки одного запроса.

2023-02-09 14:43 UTC, sdelfi commented on packages/client/ssr.tsx
>    const context = await query(remixRequest);
Тогда отлично. В выходные займусь этим, руки чешутся привести в порядок и влить этот PR в develop :)

2023-02-10 08:58 UTC, sdelfi commented
@Olegas залил обновление, внедрил TLS. Спасибо за подсказку. 

Единственный момент смущает, правильно ли сделал: в HTTPClient у нас создается индивидуальный инстанс и к нему не цепляется interceptor, который задал на сервере. В итоге я прикрепил к клиенту request interceptor из глобального инстанса.  Если не сделать, то не работало.
Не хотелось просто на клиенте все-таки использовать глобальный инстанс клиента.

Также перенес SSR на сервере в отдельный файл, чтобы index.ts был почище. Давно хотел сделать это.

2023-02-10 17:43 UTC, Olegas commented
> Не хотелось просто на клиенте все-таки использовать глобальный инстанс клиента.

На клиенте нет ничего плохого в глобальном инстансе клиента.

2023-02-10 17:49 UTC, Olegas approved these changes
👍

2023-02-10 17:50 UTC, merged