Forum
FrontHeads/tanchiki pull request #86
Opened 2023-02-06 11:19 UTC by Gramoteev

Совместно с @andreyatx реализован форум для игры

Тесты для форума еще предстоит починить, часть функционала для этого ожидается от соседнего PR "SSR"
Также будет добавлена защита от XSS

2023-02-06 15:41 UTC, sdelfi commented
@Gramoteev 
Начал чинить тесты.

Попутно слови такоую ошибку при попытке добавить топик в секцию
![image](https://user-images.githubusercontent.com/1927032/217016229-d66c3443-90f0-4a2f-a250-c82a2af99e19.png)

"insert or update on table \"forum_topics\" violates foreign key constraint \"forum_topics_user_id_fkey\""

2023-02-06 17:40 UTC, sdelfi approved these changes
Есть пара не критичных замечаний/предложений.

А так - молодцы, колоссальная работа.

2023-02-06 17:40 UTC, sdelfi commented on packages/server/api/services/ForumSection.ts
> +  .get('/', (_: Request, res: Response, next) => {
Этот запрос (http://localhost:5000/api/forum/section) отдает некорректный тип для двух полей topicCount и messages

![image](https://user-images.githubusercontent.com/1927032/217029306-02b2e77d-62f4-4a69-a4cf-ca2b2d1e8e2e.png)

Хорошо бы настроить, чтобы отдавалось число, как прописано на клиенте в типах

2023-02-06 17:40 UTC, sdelfi commented on packages/server/api/services/User.ts
> +export const userRoute = Router()
Судя по всему - эта ветка роутов не используется. Нужно ли оставлять?

2023-02-06 17:40 UTC, sdelfi commented on packages/client/src/api/forumAPI.ts
> +  getAllSections: () => HTTP.get<ForumSectionItem[]>(API_ENDPOINTS.FORUM.GET_ALL_SECTIONS),
Похоже, что в врзвращаемых типах не все прописано у ForumSectionItem

Возвращается массив объектов со следующей структурой:

    {
        "id": 1,
        "name": "Новости",
        "created_at": "2023-02-06T16:03:55.911Z",
        "updated_at": "2023-02-06T16:03:55.911Z",
        "topicCount": 0,
        "messages": 0
    },


А в типе прописано так: 
export type ForumSectionItem = {
  id: number;
  name: string;
  topicCount: number;
  messages: number;
};

В целом, created_at, updated_at не критичны, т.к. не используются, просто отловил при исправлении тестов

2023-02-06 17:40 UTC, sdelfi commented on packages/client/src/app.typings.ts
> +export type ExpressError = {
Как понимаю, это сделано, потому что на клиенте нет пакета express и тянуть пакет ради его типов не логично?

2023-02-06 17:40 UTC, sdelfi commented on packages/client/src/components/Breadcrumbs/Breadcrumbs.tsx
> +      ): match is {
Странная конструкция. А для чего она?

2023-02-06 17:40 UTC, sdelfi commented on packages/client/src/components/Dropdown/Dropdown.tsx
> +    <div className={`dropdown ${className || ''}`} ref={dropdownRef}>
Может для класоты использовать утилиту classNames? Искать по 'cn(' в коде

2023-02-06 17:40 UTC, sdelfi commented on packages/client/src/pages/Forum/ForumSection/ForumNewTopic/ForumNewTopic.tsx
> +  const messageChangeHandler = useCallback(
Уж очень хочется тут перенос строки добавить :)

2023-02-06 17:40 UTC, sdelfi commented on packages/client/src/pages/Forum/ForumSection/ForumNewTopic/ForumNewTopic.tsx
> +          <form onSubmit={submitHandler} className="new-topic">
Не критично, но может есть смысл форму вынести в отдельный компонент, т.к. этот получился достаточно громоздким.

2023-02-06 17:40 UTC, sdelfi commented on packages/client/src/pages/Forum/ForumSection/ForumNewTopic/ForumNewTopic.tsx
> +  return userId ? (
А для чего такое условие? 
Ведь если нет userId, то роут просто не откроется, т.к. он в ProtectedRoutes зоне или я ошибаюсь?

2023-02-06 17:40 UTC, sdelfi commented on packages/client/src/pages/Forum/ForumSection/ForumSection.tsx
> +  return section ? (
Вместо такой конструкии лучше использовать Supsense -> Await. Как в Root компоненте.
Но тогда еще тесты нужно еще подправить. Есть пример тут https://github.com/FrontHeads/tanchiki/pull/85/files , в компоненте Leaderboard. Но если переделывать так, то нужно будет тесты проверить, скорей всего сломаются.

2023-02-06 17:40 UTC, sdelfi commented on packages/client/src/pages/Forum/ForumSection/ForumSection.tsx
> +  return section ? (
А лучше потому что во время того как loader подгружает данные - можно отобразить loader, чтобы клиент не подумал, что браузер завис

2023-02-06 17:40 UTC, sdelfi commented on packages/client/src/pages/Forum/ForumTopic/EmoteMenu/EmoteMenu.tsx
> +import './EmoteMenu.css';
Круто получилось!

2023-02-06 17:40 UTC, sdelfi commented on packages/client/src/pages/Forum/ForumTopic/ForumTopic.tsx
> +  }
Уже второй раз вижу данную конструкцию. Может пора вынести куда-нибудь в утилиты, например:

```typescript
export const getAvatar = (path: string, defaultAvatarPath: string = defaultAvatarPath) => {
  if (path) {
    return buildPath(determineAPIHost(), API_ENDPOINTS.USER.GET_AVATAR(path));
  }

  return defaultAvatarPath;
  }
}
```

2023-02-06 17:40 UTC, sdelfi commented on packages/client/src/pages/Forum/ForumTopic/ForumTopicDescription/ForumTopicDescription.tsx
> +        {isEditDescription ? (
Менять не надо, но на тему динамичного изменения структуры html элементов 
https://youtu.be/A0W2n2azH5s?t=293

2023-02-06 17:40 UTC, sdelfi commented on packages/server/middlewares/errorHandler.ts
> +export const errorHandler = (err: ExpressError, _req: Request, res: Response, _next: NextFunction) => {
Отлично придумано

2023-02-06 17:40 UTC, sdelfi commented on packages/server/middlewares/proxy.ts
> +        if (user && user.id) {
А так можно? 

```suggestion
        if (user?.id) {
```

2023-02-06 17:52 UTC, Gramoteev commented on packages/client/src/app.typings.ts
> +export type ExpressError = {
Это было сделано для серверной части. мне нужно было как-то типизировать мой errorHandler. Я думаю нужно его куда-то перенести из клиентской папки
![image](https://user-images.githubusercontent.com/51950012/217047273-fd010824-039f-410c-be43-baadd5a7662d.png)

2023-02-06 17:55 UTC, Gramoteev commented on packages/client/src/components/Breadcrumbs/Breadcrumbs.tsx
> +      ): match is {
Хороший вопрос.
match.handle по умолчанию имеет тип unknown,  но т.к. далее по цепочке нам нужно вызывать функцию match.handle.crumbs я написал данный guard
Выглядит конечно сомнительно, но по логике кажется верно, т.к. не хотелось бы делать ts-ignore либо any

2023-02-06 17:59 UTC, Gramoteev commented on packages/server/middlewares/proxy.ts
> +        if (user && user.id) {
Оператор опциональной последовательности ?. позволяет получить значение свойства, находящегося на любом уровне вложенности в цепочке связанных между собой объектов, без необходимости проверять каждое из промежуточных свойств в ней на существование.
Отсюда https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Optional_chaining

2023-02-06 18:00 UTC, sdelfi commented on packages/client/src/components/Breadcrumbs/Breadcrumbs.tsx
> +      ): match is {
Выглядит просто громоздко, может как-то можно отдельно вынести этот guard в отдельную функцию.

2023-02-06 18:02 UTC, Gramoteev commented on packages/client/src/app.typings.ts
> +export type ExpressError = {
т.е. я не нашел соответствующего типа для  значения err

2023-02-06 18:03 UTC, sdelfi commented on packages/client/src/app.typings.ts
> +export type ExpressError = {
Лучше, конечно, перенести в серверный пакет, т.к. на клиенте не используется данный тип, как ты и написал.

2023-02-06 18:08 UTC, sdelfi commented on packages/server/middlewares/proxy.ts
> +        if (user && user.id) {
В доке TS есть такое
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining

![image](https://user-images.githubusercontent.com/1927032/217050977-c47f3075-1061-4215-a9e2-d72d2da79c34.png)

2023-02-07 07:03 UTC, Gramoteev commented on packages/server/api/services/ForumSection.ts
> +  .get('/', (_: Request, res: Response, next) => {
Проблема была в том, что по умолчанию Postgre для сгруппированного поля назначает тип bigint,  
BIGINT maximum value is 2^63-1, javascript can safely represent up to 2^53. To be on the safe side libraries return those numbers as strings.

Решил просто, поменяв тип в запросе `SELECT COUNT(*)::integer`

2023-02-07 07:09 UTC, Gramoteev commented on packages/client/src/app.typings.ts
> +export type ExpressError = {
тип оказался не нужен, было достаточно простого Error

2023-02-07 08:40 UTC, andreyatx commented on packages/client/src/api/forumAPI.ts
> +  getAllSections: () => HTTP.get<ForumSectionItem[]>(API_ENDPOINTS.FORUM.GET_ALL_SECTIONS),
Добавил created_at, updated_at

2023-02-07 08:46 UTC, andreyatx commented on packages/client/src/pages/Forum/ForumSection/ForumNewTopic/ForumNewTopic.tsx
> +  return userId ? (
убрал

2023-02-07 09:02 UTC, andreyatx commented on packages/client/src/pages/Forum/ForumTopic/ForumTopic.tsx
> +  }
вынес

2023-02-07 09:31 UTC, andreyatx commented on packages/client/src/pages/Forum/ForumSection/ForumSection.tsx
> +  return section ? (
Сделал, не знаю правильно или нет

2023-02-07 09:34 UTC, andreyatx commented on packages/client/src/pages/Forum/ForumSection/ForumNewTopic/ForumNewTopic.tsx
> +          <form onSubmit={submitHandler} className="new-topic">
Не хочется выносить, т.к. он нигде больше не используется. Да и не особо он большой

2023-02-09 01:10 UTC, DmitriiNazimov approved these changes
Класс! Проделана большая и качественная работа! Оставил несколько не критичных пожеланий.

2023-02-09 01:10 UTC, DmitriiNazimov commented on packages/client/src/components/Breadcrumbs/Breadcrumbs.tsx
> +const hasCrumbHandler = (match: Record<string, unknown>): match is {
Может быть объект который после оператора is стоит вынести в typings? Так будет читабельнее, мне кажется.

2023-02-09 01:10 UTC, DmitriiNazimov commented on packages/client/src/components/Dropdown/Dropdown.tsx
> +    <div className={`dropdown ${className || ''}`} ref={dropdownRef}>
Поддержу, что classNames была бы кстати.

2023-02-09 01:10 UTC, DmitriiNazimov commented on packages/server/api/services/ForumMessage.ts
> +    ForumMessage.findByPk(req.params.id, { include: [{ model: ForumTopic }, { model: User }], logging: true })
Может быть logging уже можно убрать?

2023-02-09 01:10 UTC, DmitriiNazimov commented on packages/server/api/services/ForumSection.ts
> +            Sequelize.literal(`(SELECT COUNT(*)::integer
Не критично, но режет глаз что запросы написаны один в lowerCase, другой в upperCase и оба не соответствуют привычной нотации SQL запросов где команды большими буквами типа WHERE и переменные маленькими буквами.

2023-02-09 09:30 UTC, Gramoteev commented on packages/server/api/services/ForumSection.ts
> +            Sequelize.literal(`(SELECT COUNT(*)::integer
Кажется поправил как следует, использовал данный форматтер, https://www.dpriver.com/pp/sqlformat.htm

2023-02-09 19:38 UTC, Olegas requested changes

2023-02-09 19:38 UTC, Olegas commented on packages/server/models/User.ts
> +  @PrimaryKey
Тут что-то перебор кажется. Primary key сам по себе с индексом, уникальный и не может быть null

2023-02-09 19:38 UTC, Olegas commented on packages/server/models/ForumSection.ts
> +  @Index
Кажется одного unique уже достаточно, не надо говорит еще и index

2023-02-09 19:38 UTC, Olegas commented on packages/server/middlewares/checkAuth.ts
> +        }
Кажется тут не хватает else и вы потеряете next

2023-02-09 19:38 UTC, Olegas commented on packages/server/api/services/ForumTopic.ts
> +    if (res.locals.user && res.locals.user.id === req.body.user_id) {
А для чего нужна такая проверка? Почему просто всегда не создавать топик от текущего пользователя?

2023-02-09 19:38 UTC, Olegas commented on packages/server/api/services/ForumTopic.ts
> +    if (res.locals.user && res.locals.user.id === req.body.user_id) {
А тут лучше бы проверить чей топик в БД. Иначе я ведь могу в теле запроса подменить ид на свой а ид топика оставить чужой и редактировать чужие посты

2023-02-09 19:38 UTC, Olegas commented on packages/server/api/services/ForumTopic.ts
> +    ForumTopic.destroy({ where: { id: req.params.id } })
И вот тут бы проверить что свой топик удаляется. Можно это в where добавить что бы не делать чтение

2023-02-09 19:38 UTC, Olegas commented on packages/client/src/utils/dateUtils.ts
> +      ('0' + date.getDate()).slice(-2) + '.' + ('0' + (date.getMonth() + 1)).slice(-2) + '.' + date.getFullYear();
Добавить нолик а потом взять 2 с конца?
Возможно сделать это чуть более читаемым поможет https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/padStart

2023-02-09 19:38 UTC, Olegas commented on packages/client/src/components/Dropdown/Dropdown.tsx
> +                className={`dropdown__menu-button ${emoteClass || ''}`}
Если что - classnames отлично решает проблему классов, которые могут быть пустыми или отсутствовать.

2023-02-10 06:09 UTC, Gramoteev commented on packages/server/models/User.ts
> +  @PrimaryKey
✅

2023-02-10 06:09 UTC, Gramoteev commented on packages/server/models/ForumSection.ts
> +  @Index
✅

2023-02-10 06:09 UTC, Gramoteev commented on packages/server/middlewares/checkAuth.ts
> +        }
✅

2023-02-10 10:13 UTC, Gramoteev commented on packages/server/api/services/ForumTopic.ts
> +    if (res.locals.user && res.locals.user.id === req.body.user_id) {
Да, проверка, значению которой нельзя доверять не нужна. С сообщениями также поправил. И вообще удалил из клиента отправку юзера.

2023-02-10 10:14 UTC, Gramoteev commented on packages/server/api/services/ForumTopic.ts
> +    if (res.locals.user && res.locals.user.id === req.body.user_id) {
переделал также как с удалением, делаю проверку через where, если топик не найден отправляю ошибку

2023-02-10 10:14 UTC, Gramoteev commented on packages/server/api/services/ForumTopic.ts
> +    ForumTopic.destroy({ where: { id: req.params.id } })
✅

2023-02-10 10:15 UTC, Gramoteev commented on packages/client/src/utils/dateUtils.ts
> +      ('0' + date.getDate()).slice(-2) + '.' + ('0' + (date.getMonth() + 1)).slice(-2) + '.' + date.getFullYear();
Спасибо! Теперь точно запомню

2023-02-11 06:50 UTC, Olegas approved these changes
👍 молодцы

2023-02-11 07:16 UTC, merged