Content Security Policy
FrontHeads/tanchiki pull request #89
Opened 2023-02-11 14:07 UTC by andreyatx

Настройка CSP.

TBD: типизация.

2023-02-12 22:07 UTC, DmitriiNazimov requested changes
Есть небольшие замечания. В основном они касаются того, что я туповат, и мне нужны пояснения в виде комментариев в коде. Ну и @ts-ignore желательно убрать.

2023-02-12 22:07 UTC, DmitriiNazimov commented on packages/server/config/cspDirectives.ts
> +  } else directives['script-src']?.push(NONCE);
Тут нужна пояснительная бригада. Что делает этот блок if-else и зачем? Возможно стоит написать комментарий.

2023-02-12 22:07 UTC, DmitriiNazimov commented on packages/server/utils/expressCspHeader.ts
> +// За основу взят https://github.com/frux/express-csp-header
Этот комментарий наверное стоит удалить.

2023-02-12 22:07 UTC, DmitriiNazimov commented on packages/server/utils/expressCspHeader.ts
> +    //@ts-ignore
Надо постараться убрать @ts-ignore. У нас их ни одного нет на проекте и не хотелось бы чтобы они появились в конце проекта.

2023-02-12 22:07 UTC, DmitriiNazimov commented on packages/server/config/constants.ts
> +export const TLD = '%tld%';
Я думаю стоит написать комментарии что это и для чего. Особенно для TLD.

2023-02-14 11:01 UTC, sdelfi approved these changes

2023-02-14 19:44 UTC, DmitriiNazimov approved these changes

2023-02-17 15:36 UTC, Olegas commented on packages/server/routes/SSR.ts
> +          .replace(`{csp.nonce}`, req.nonce)
А кто и куда вставляет такую строку?

2023-02-17 16:09 UTC, andreyatx commented on packages/server/routes/SSR.ts
> +          .replace(`{csp.nonce}`, req.nonce)
Изначально эта строка должна была заменять плейсхолдер в html на реальное значение nonce. Но я видимо не сохранил изменения в html 🤷.
Поменял метод на replaceAll.

2023-02-17 17:47 UTC, Olegas commented on packages/server/utils/expressCspHeader.ts
> +    req.nonce = crypto.randomBytes(16).toString('base64');
Синхронная версия randomBytes может заблокироваться в ожидании случайных данных. На веб-сервере лучше использовать асинхронную версию.
https://github.com/nodejs/help/issues/457

Не призываю сейчас чинить, скорее на будущее

2023-02-17 17:47 UTC, Olegas approved these changes

2023-02-17 21:02 UTC, merged